### ISSUE TITLE
_InactiveRpcError occuring when trying to save the bento service.

### ISSUE THREAD

**Issue by dalavayi** [bentoml/BentoML#1332]
Hi, 

when I am trying to save the service I keep getting this error.

[2020-12-16 11:29:30,965] WARNING - pip package requirement pandas already exist
[2020-12-16 11:29:30,968] WARNING - pip package requirement onnxruntime already exist
[2020-12-16 11:29:30,971] WARNING - Using remote YataiService at `34.68.200.172:50051`, local YataiService configs including db_url, repo_base_url, s3_endpoint_url and default_namespacewill all be ignored.
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
<ipython-input-106-d4f986eb1e97> in <module>
      9 RF_bm = BigMartOnnx()
     10 RF_bm.pack('model', model_onnx)
---> 11 saved_path = RF_bm.save()

~\Anaconda3\envs\tf\lib\site-packages\bentoml\service\__init__.py in save(self, base_path, version, labels)
    662         :return: saved_path: file path to where the BentoService is saved
    663         """
--> 664         return save(self, base_path, version, labels)
    665 
    666     def save_to_dir(self, path, version=None):

~\Anaconda3\envs\tf\lib\site-packages\bentoml\service\__init__.py in save(bento_service, base_path, version, labels)
    347         yatai_client = YataiClient()
    348 
--> 349     return yatai_client.repository.upload(bento_service, version, labels)
    350 
    351 

~\Anaconda3\envs\tf\lib\site-packages\bentoml\yatai\client\bento_repository_api.py in upload(self, bento_service, version, labels)
     60         with TempDirectory() as tmpdir:
     61             save_to_dir(bento_service, tmpdir, version, silent=True)
---> 62             return self._upload_bento_service(bento_service, tmpdir, labels)
     63 
     64     def _upload_bento_service(self, bento_service, saved_bento_path, labels):

~\Anaconda3\envs\tf\lib\site-packages\bentoml\yatai\client\bento_repository_api.py in _upload_bento_service(self, bento_service, saved_bento_path, labels)
     72             GetBentoRequest(
     73                 bento_name=bento_service_metadata.name,
---> 74                 bento_version=bento_service_metadata.version,
     75             )
     76         )

~\Anaconda3\envs\tf\lib\site-packages\grpc\_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    824         state, call, = self._blocking(request, timeout, metadata, credentials,
    825                                       wait_for_ready, compression)
--> 826         return _end_unary_response_blocking(state, call, False, None)
    827 
    828     def with_call(self,

~\Anaconda3\envs\tf\lib\site-packages\grpc\_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    727             return state.response
    728     else:
--> 729         raise _InactiveRpcError(state)
    730 
    731 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1608098457.106000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1608098457.106000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"

I have a doubt regarding this statement also:
WARNING - Using remote YataiService at `34.68.200.172:50051`, local YataiService configs including db_url, repo_base_url, s3_endpoint_url and default_namespacewill all be ignored.

my YataiService is not running at this url now i have changed it by using the command :
!bentoml config set yatai_service.url=34.123.60.5:50051
even then this is not getting changed.

Do i need the YataiService up whenever i am saving my service? can i just save the service without having any connection with the model management?

Please help me regarding these queries.
Thank you.

**Comment by yubozhao** [comment]
@dalavayi Can you run `bentoml config unset yatai_service.url` and then set it again with the new Yatai service URL? That should fix your issue of not saving to the new yatai service at `34.123.60.5`

**Comment by athulprathap** [comment]
I am also facing similar issue.
Traceback (most recent call last):
  File "/home/aicoe/.conda/envs/clm_bento_3.8/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/home/aicoe/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/aicoe/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aicoe/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aicoe/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aicoe/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aicoe/.local/lib/python3.8/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/home/aicoe/.local/lib/python3.8/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/aicoe/.local/lib/python3.8/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/aicoe/.local/lib/python3.8/site-packages/bentoml/cli/bento_service.py", line 207, in serve
    saved_bundle_path = resolve_bundle_path(
  File "/home/aicoe/.local/lib/python3.8/site-packages/bentoml/utils/__init__.py", line 186, in resolve_bundle_path
    bento_pb = yatai_client.repository.get(bento)
  File "/home/aicoe/.local/lib/python3.8/site-packages/bentoml/yatai/client/bento_repository_api.py", line 283, in get
    result = self.yatai_service.GetBento(
  File "/home/aicoe/.conda/envs/clm_bento_3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "/home/aicoe/.conda/envs/clm_bento_3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/home/aicoe/.conda/envs/clm_bento_3.8/lib/python3.8/site-packages/grpc/_channel.py", line 333, in result
    raise self
  File "/home/aicoe/.conda/envs/clm_bento_3.8/lib/python3.8/site-packages/grpc/_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/home/aicoe/.conda/envs/clm_bento_3.8/lib/python3.8/site-packages/grpc/_channel.py", line 837, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/home/aicoe/.conda/envs/clm_bento_3.8/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1613635560.589837028","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1613635560.589825591","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"

**Comment by chlee1016** [comment]
A similar issue happened to me.

I succeeded in saving my bento service at first, but failed after start YataiService trough docker as below.
```command
docker run -v ~/bentoml:/bentoml \
    -p 3000:3000 \
    -p 50051:50051 \
    bentoml/yatai-service:0.12.1 \
    --db-url=sqlite:///bentoml/storage.db \
    --repo-base-url=/bentoml/repository
```
I tried to delete my docker container and image, change my conda env, re-install bentoml, reset yatai_service.url, but the same problem still happen.

```python
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/pythonProject/bentoml_bug.py", line 19, in <module>
    iris_classifier_service.save(labels = {"model_name":"IrisClassifier"})
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/bentoml/service/__init__.py", line 738, in save
    return yc.repository.upload(self, version, labels)
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/bentoml/yatai/client/bento_repository_api.py", line 144, in upload
    return self.upload_from_dir(tmpdir, labels)
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/bentoml/yatai/client/bento_repository_api.py", line 155, in upload_from_dir
    bento_version=bento_service_metadata.version,
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/grpc/_interceptor.py", line 221, in __call__
    compression=compression)
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/grpc/_channel.py", line 343, in result
    raise self
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/grpc/_interceptor.py", line 247, in continuation
    compression=new_compression)
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/Users/user/opt/anaconda3/envs/chlee_test2_210424/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1619276342.361457000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5420,"referenced_errors":[{"created":"@1619276342.361456000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>

Process finished with exit code 1
```

**Comment by parano** [comment]
@chlee1016 this is likely due to the `bentoml config set yatai_url...` CLI command setting the default save target to a Yatai deployment that is no longer running. This is no longer an issue because we have removed yatai_url from the configuration file and making it a required parameter for yatai related operations

Here's the latest document on how to config BentoML to save to a specific yatai server: https://docs.bentoml.org/en/latest/concepts.html#customizing-model-repository
