### ISSUE TITLE
Failure to containerize model if build-arg value contains multiple `=` characters

### ISSUE THREAD

**Issue by lucascott** [bentoml/BentoML#1403]
**Describe the bug**
Containerization fails due to unpacking issue when passing the `--build-arg` argument with value including multiple `=` characters.

In particular, the string split operation in [bento_service.containerize()](https://github.com/bentoml/BentoML/blob/d8ae9490a834e1aab371a2b69e937acb5c86f19d/bentoml/cli/bento_service.py#L384) fails to assign the resulting values to variables for cases when the input is split into >2 tokens.

**To Reproduce**
The BentoML fails to containerize the model when one wants to set the EXTRA_PIP_INSTALL_ARGS environment variable with argument-value pairs to be passed to `pip install`.

A scenario is the following:
One wants to specify an additional `--extra-index-url` pip argument to specify an internal PyPI server.

A simple example can be extracted from the `bentoml-quick-start-guide.ipynb`.

1. Register a new bento service. i.e. `IrisClassifier` for this scenario
2. Run `bentoml containerize IrisClassifier:latest -t iris-classifier --build-arg EXTRA_PIP_INSTALL_ARGS=--extra-index-url=https://myorgpypi.org/`

The failure occurs (see logs below) due to the splitting of the string `EXTRA_PIP_INSTALL_ARGS=--extra-index-url=https://myorgpypi.org/` as
``` python
[
  "EXTRA_PIP_INSTALL_ARGS",
  "--extra-index-url",
  "https://myorgpypi.org/"
]
```
instead of
``` python
[
  "EXTRA_PIP_INSTALL_ARGS",
  "--extra-index-url=https://myorgpypi.org/"
]
```

**Expected behavior**
With respect to the string split operation in [bento_service.containerize()](https://github.com/bentoml/BentoML/blob/d8ae9490a834e1aab371a2b69e937acb5c86f19d/bentoml/cli/bento_service.py#L384), the solution would be to force the split function to split only once: `key, value = arg.split("=", 1)`

**Screenshots/Logs**

When running: `bentoml containerize IrisClassifier:latest -t iris-classifier --build-arg EXTRA_PIP_INSTALL_ARGS=--extra-index-url=https://myorgpypi.org/`:

```
[2021-01-13 10:26:00,840] DEBUG - Setting debug mode: ON for current session
[2021-01-13 10:26:00,840] DEBUG - Creating local YataiService instance
[2021-01-13 10:26:01,087] DEBUG - Upgrading tables to the latest revision
[2021-01-13 10:26:02,595] INFO - Getting latest version IrisClassifier:20210108154220_FD6FEA
Found Bento: /home/luca/bentoml/repository/IrisClassifier/20210108154220_FD6FEA
Image version not specified, using version parsed from BentoService: '20210108154220_FD6FEA'
Traceback (most recent call last):
  File "/home/luca/PycharmProjects/bentoProject/.venv/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/luca/PycharmProjects/bentoProject/.venv/lib/python3.7/site-packages/bentoml/cli/bento_service.py", line 409, in containerize
    key, value = arg.split("=")
ValueError: too many values to unpack (expected 2)
```

**Environment:**
 - OS: Ubuntu 18.04.4
 - Python Version: Python 3.7.9
 - BentoML Version: BentoML-0.10.1

**Additional context**
No additional context

**Comment by yubozhao** [comment]
@lucascott Thank you for reporting.  I will work on fixing it
