### ISSUE TITLE
BentoML adds wrong requirement for PytorchLightning

### ISSUE THREAD

**Issue by pkolebski** [bentoml/BentoML#1453]
**Describe the bug**
BentoML adds package ```pytorch``` to ```requirements.txt``` file which cannot be installed.

**To Reproduce**
deploy.py
```python
requirements = [
    'bentoml==0.11.0',
    'dask[bag]==2021.1.0',
    'imageio==2.9.0',
    'toolz==0.11.1',
    'torch==1.7.1',
    'numpy==1.18.2',
    'pilgram==1.2.0',
    'pillow==8.1.0',
    'torchvision==0.8.2',
    'pytorch-lightning==1.1.7',
]


@bentoml.env(pip_packages=requirements)
@bentoml.artifacts([PytorchLightningModelArtifact('model')])
class PytorchLightningService(bentoml.BentoService):
    @bentoml.api(input=ImageInput())
    def predict(self, img):
        input_tensor = transform(img)
        return self.artifacts.model(input_tensor).detach().numpy()
```
create_bento_service.py
```python
model = ResnetPL()
model = model.load_from_checkpoint('checkpoint.ckpt')
model.freeze()

svc = PytorchLightningService()
svc.pack('model', model)
svc.save_to_dir(CHECKPOINT_DIR / 'services')
```
```bash
docker build services/.
```

**Expected behavior**
Easily created and built docker image.

**Screenshots/Logs**
```bash
Running setup.py install for pytorch: started
    Running setup.py install for pytorch: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4h0bku66/pytorch_d4dd611406b64330b1aec7fd18f8967c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4h0bku66/pytorch_d4dd611406b64330b1aec7fd18f8967c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ii868i92/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/pytorch
         cwd: /tmp/pip-install-4h0bku66/pytorch_d4dd611406b64330b1aec7fd18f8967c/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4h0bku66/pytorch_d4dd611406b64330b1aec7fd18f8967c/setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4h0bku66/pytorch_d4dd611406b64330b1aec7fd18f8967c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4h0bku66/pytorch_d4dd611406b64330b1aec7fd18f8967c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ii868i92/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/pytorch Check the logs for full command output.
```

**Environment:**
 - OS: Ubuntu 20.04.1 LTS
 - Python 3.8.5
 - BentoML 0.11.0

**Additional context**
I find out that ```pytorch``` is added to ```requirements.txt``` because of:
```python
class PytorchLightningModelArtifact(BentoServiceArtifact):
  def set_dependencies(self, env: BentoServiceEnv):
    env.add_pip_packages(['pytorch'])
```
in ```bentoml.frameworks/pytorch.py:250```. Is it a bug?

**Comment by yubozhao** [comment]
@pkolebski This is a bug. Thanks for reporting it.

I am going to add a fix for this right now

**Comment by yubozhao** [comment]
@pkolebski I updated the requirements and add additional docker integration test for this.  You should able to use this in the next release.

Feel free to reopen, if you run into any additional issue.
