### ISSUE TITLE
Issues with scaling / handling multiple requests

### ISSUE THREAD

**Issue by gregd33** [bentoml/BentoML#1518]
**Describe the bug**
So we have some services that we are trying to use with Dagster. The issue is that as data flows through the DAG, the service will be hit multiple times in parallel. What we see is that a certain number of requests will crash the service (running on k8s). 

We can isolate the issue and reproduce by sending many items in parallel directly to the k8s-deployed service so it is definitely the service itself failing with many simultaneous requests. 

We can also isolate the issue even more by running the service locally in docker and capping the resources via docker args. The behaviour boils down to the service being able to handle 1 request fine (so the model itself can load in memory etc) but fails when it gets multiple requests. So it seems it is trying to process them all instead of queuing them, even if trying to process them all causes it to run out of resources. 

Is there anything you would expect to improve the performance? It's fine if the service simply queues the data and takes a while to process it. But crashing causes the data to not get processed. 

**Screenshots/Logs**

The error seen on crashing in this service is:
 ```
[2021-03-18 22:18:21,759] ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/bentoml/server/api_server.py", line 288, in api_func
    response = api.handle_request(request)
  File "/opt/venv/lib/python3.7/site-packages/bentoml/service/inference_api.py", line 280, in handle_request
    inf_task = self.input_adapter.from_http_request(req)
  File "/opt/venv/lib/python3.7/site-packages/bentoml/adapters/utils.py", line 128, in _method
    return method(self, req)
  File "/opt/venv/lib/python3.7/site-packages/bentoml/adapters/multi_file_input.py", line 152, in from_http_request
    _, _, files = HTTPRequest.parse_form_data(req)
  File "/opt/venv/lib/python3.7/site-packages/bentoml/types.py", line 231, in parse_form_data
    stream, form, files = parse_form_data(environ, silent=False)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 123, in parse_form_data
    ).parse_from_environ(environ)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 207, in parse_from_environ
    return self.parse(get_input_stream(environ), mimetype, content_length, options)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 232, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 131, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 253, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 584, in parse
    return self.cls(form), self.cls(files)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 419, in __init__
    for key, value in mapping or ():
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 582, in <genexpr>
    form = (p[1] for p in formstream if p[0] == "form")
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 537, in parse_parts
    for ellt, ell in self.parse_lines(file, boundary, content_length):
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 482, in parse_lines
    self.fail("unexpected end of stream")
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/formparser.py", line 377, in fail
    raise ValueError(message)
ValueError: unexpected end of stream
```

On a different service, I get:
```
[2021-03-19 14:24:04 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:24)
[2021-03-19 14:24:04 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:25)
[2021-03-19 14:24:04 +0000] [24] [INFO] Worker exiting (pid: 24)
[2021-03-19 14:24:04 +0000] [25] [INFO] Worker exiting (pid: 25)
[2021-03-19 14:24:05 +0000] [100] [INFO] Booting worker with pid: 100
[2021-03-19 14:24:05 +0000] [101] [INFO] Booting worker with pid: 101
```

Increasing the timeout still gives messages indicating the worker has rebooted. 

From the client sending requests, I get 504 and 502 errors

**Environment:**
 - OS: [e.g. MacOS 10.14.3] : Ubuntu / deployed in k8s in dockerised using bento base images
 - Python Version [e.g. Python 3.7.1]: 3.7
 - BentoML Version [e.g. BentoML-0.8.6]: 11.0

**Additional context**

**Comment by gregd33** [comment]
I'm actually going to close this since I think the issue is very coupled with my specific service so it will have a hard time debugging.

**Comment by calclavia** [comment]
I have the same issue:
```
[2021-05-25 01:08:08 +0000] [185] [INFO] Booting worker with pid: 185
[2021-05-25 01:09:08 +0000] [182] [CRITICAL] WORKER TIMEOUT (pid:183)
[2021-05-25 01:09:08 +0000] [182] [CRITICAL] WORKER TIMEOUT (pid:185)
[2021-05-25 01:09:08 +0000] [183] [INFO] Worker exiting (pid: 183)
[2021-05-25 01:09:08 +0000] [185] [INFO] Worker exiting (pid: 185)
[2021-05-25 01:09:08 +0000] [192] [INFO] Booting worker with pid: 192
[2021-05-25 01:09:08 +0000] [193] [INFO] Booting worker with pid: 193
[2021-05-25 01:10:09 +0000] [182] [CRITICAL] WORKER TIMEOUT (pid:192)
[2021-05-25 01:10:09 +0000] [182] [CRITICAL] WORKER TIMEOUT (pid:193)
[2021-05-25 01:10:09 +0000] [193] [INFO] Worker exiting (pid: 193)
[2021-05-25 01:10:09 +0000] [192] [INFO] Worker exiting (pid: 192)
[2021-05-25 01:10:09 +0000] [196] [INFO] Booting worker with pid: 196
[2021-05-25 01:10:09 +0000] [197] [INFO] Booting worker with pid: 197
[2021-05-25 01:11:09 +0000] [182] [CRITICAL] WORKER TIMEOUT (pid:196)
[2021-05-25 01:11:09 +0000] [182] [CRITICAL] WORKER TIMEOUT (pid:197)
[2021-05-25 01:11:11 +0000] [182] [WARNING] Worker with pid 197 was terminated due to signal 9
[2021-05-25 01:11:11 +0000] [205] [INFO] Booting worker with pid: 205
[2021-05-25 01:11:11 +0000] [182] [WARNING] Worker with pid 196 was terminated due to signal 9
[2021-05-25 01:11:11 +0000] [206] [INFO] Booting worker with pid: 206
```
I am loading several large neural networks - not sure if this is a cause. When setting number of workers to 1, it works.

**Comment by gregd33** [comment]
From my experience it is just a resource issue. If your service/worker runs out of memory or CPU then this will happen. Using just 1 worker helps because more workers = more replicas of your model in memory.
