### ISSUE TITLE
[v0.12.0] ModuleNotFoundError when trying to start the dev server

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1529]
**Describe the bug**

> by Matthieu Vanhoutte 
... installed the last bentoML v0.12.0 and when trying to launch bentoml serve $saved_path I got the following error:
[2021-03-24 09:20:31,130] INFO - Starting BentoML API proxy in development mode..
[2021-03-24 09:20:31,131] INFO - Starting BentoML API server in development mode..
Traceback (most recent call last):
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/cli/click_utils.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/cli/bento_service.py", line 232, in serve
    start_dev_server(
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/server/__init__.py", line 68, in start_dev_server
    _start_dev_proxy(
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/server/__init__.py", line 107, in _start_dev_proxy
    container.wire(packages=[marshal])
  File "src/dependency_injector/containers.pyx", line 256, in dependency_injector.containers.DynamicContainer.wire
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/dependency_injector/wiring.py", line 330, in wire
    modules.extend(_fetch_modules(package))
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/dependency_injector/wiring.py", line 553, in _fetch_modules
    module = importlib.import_module(module_info.name)
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/marshal/marshal.py", line 33, in <module>
    from bentoml.tracing.zipkin import make_http_headers
  File "/home/matthieu/anaconda3/envs/test_bentoml_cpu/lib/python3.8/site-packages/bentoml/tracing/zipkin.py", line 23, in <module>
    from py_zipkin import Tracer
ModuleNotFoundError: No module named 'py_zipkin'

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

https://github.com/bentoml/BentoML/blob/batch-inf/setup.py#L89

**Comment by fernandocamargoai** [comment]
I started having this issue when I needed to replace the docker_base_image.

**Comment by fernandocamargoai** [comment]
As a workaround, I added the following to my `pip_packages`:
```
f"bentoml[model_server]=={bentoml.__version__}"
```
