### ISSUE TITLE
Can't load KerasModelArtifact with custom loss function while using store_model_as_json_and_weights

### ISSUE THREAD

**Issue by pietermarsman** [bentoml/BentoML#1559]
**Describe the bug**

I'm trying to store a model with a custom loss function. I'm not interested at the loss function at inference time, so it's ok if the model loading totally ignores the loss function. For that reason I'm using the `store_model_as_json_and_weights=True`. 

But using both `True` and `False` values result in the same error: 

```
ValueError: Unknown loss function: categorical_focal_loss
```

**To Reproduce**

```python
import logging
from tempfile import TemporaryDirectory

import bentoml
import tensorflow as tf
from bentoml import artifacts, BentoService
from bentoml.frameworks.keras import KerasModelArtifact
from tensorflow.python.keras import Sequential, Input
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.losses import categorical_crossentropy


bentoml.config().set('core', 'debug', 'true')
bentoml.configure_logging(logging.DEBUG)


def categorical_focal_loss(y_true, y_pred):
    ce_loss = categorical_crossentropy(y_true, y_pred)
    pt = tf.math.exp(-ce_loss)  # ce_loss gives the ln. We revert that operation
    return ce_loss * tf.pow(1.0 - pt, 2.0)


@artifacts([KerasModelArtifact('model', store_as_json_and_weights=True)])
class ClassificationInference(BentoService):
    pass


def test_bento_saving():
    """Test if saving and loading with a custom object works"""
    model = Sequential([Input(10), Dense(10)])
    model.compile(loss=categorical_focal_loss)

    inference = ClassificationInference()
    inference.pack('model', model)

    with TemporaryDirectory() as dir:
        inference.save_to_dir(dir)
        bentoml.load_from_dir(dir)


test_bento_saving()
```

**Expected behavior**

Not raise an error :) 

**Screenshots/Logs**

```
2021-03-31 22:29:03.725375: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-31 22:29:03.725405: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[2021-03-31 22:29:05,578] DEBUG - Loaded logging configuration from default configuration and environment variables.
2021-03-31 22:29:05.588013: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-31 22:29:05.588162: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-03-31 22:29:05.588173: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-31 22:29:05.588186: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (satoru): /proc/driver/nvidia/version does not exist
2021-03-31 22:29:05.588375: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-31 22:29:05.588541: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:From /home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/frameworks/keras.py:122: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

2021-03-31 22:29:05.655776: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
[2021-03-31 22:29:05,654] DEBUG - Using BentoML default docker base image 'bentoml/model-server:0.11.0-py38'
[2021-03-31 22:29:06,752] DEBUG - copy_local_py_modules target_module_name: __main__, target_module_file: /home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py
[2021-03-31 22:29:06,753] DEBUG - Updating for __main__ module, target_module_name: scratch_14, target_module_file: /home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py
[2021-03-31 22:29:06,753] DEBUG - Searching for local dependant modules of scratch_14:/home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py
[2021-03-31 22:29:06,755] DEBUG - Find bad module imports that can not be parsed properly: dict_keys(['logging', 'tempfile', 'bentoml', 'tensorflow', 'bentoml.frameworks.keras', 'tensorflow.python.keras', 'tensorflow.python.keras.layers', 'tensorflow.python.keras.losses'])
[2021-03-31 22:29:06,756] DEBUG - Copying user local python dependencies: {'scratch_14': <module '__main__' from '/home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py'>}
[2021-03-31 22:29:06,756] DEBUG - Copying local python module '/home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py'
[2021-03-31 22:29:06,758] DEBUG - Creating empty __init__.py under folder:'/tmp/tmpcyd65mz5/ClassificationInference'
[2021-03-31 22:29:06,759] DEBUG - Creating empty __init__.py under folder:'/tmp/tmpcyd65mz5/ClassificationInference/artifacts'
[2021-03-31 22:29:06,759] DEBUG - Done copying local python dependant modules
[2021-03-31 22:29:06,762] DEBUG - Using Docker Base Image bentoml/model-server:0.11.0-py38
[2021-03-31 22:29:06,776] INFO - BentoService bundle 'ClassificationInference:20210331222905_18189B' created at: /tmp/tmpcyd65mz5
[2021-03-31 22:29:07,676] DEBUG - Loaded logging configuration from default configuration and environment variables.
[2021-03-31 22:29:07,694] DEBUG - Using BentoML default docker base image 'bentoml/model-server:0.11.0-py38'
[2021-03-31 22:29:08,593] DEBUG - Loaded logging configuration from default configuration and environment variables.
[2021-03-31 22:29:08,612] DEBUG - Using BentoML default docker base image 'bentoml/model-server:0.11.0-py38'
[2021-03-31 22:29:09,511] DEBUG - copy_local_py_modules target_module_name: scratch_14, target_module_file: /tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py
[2021-03-31 22:29:09,512] DEBUG - Searching for local dependant modules of scratch_14:/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py
[2021-03-31 22:29:09,514] DEBUG - Find bad module imports that can not be parsed properly: dict_keys(['logging', 'tempfile', 'bentoml', 'tensorflow', 'bentoml.frameworks.keras', 'tensorflow.python.keras', 'tensorflow.python.keras.layers', 'tensorflow.python.keras.losses'])
[2021-03-31 22:29:09,515] DEBUG - Copying user local python dependencies: {'scratch_14': <module 'scratch_14' from '/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py'>}
[2021-03-31 22:29:09,515] DEBUG - Copying local python module '/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py'
[2021-03-31 22:29:09,517] DEBUG - Creating empty __init__.py under folder:'/tmp/tmpt6uuu8y4/ClassificationInference'
[2021-03-31 22:29:09,518] DEBUG - Creating empty __init__.py under folder:'/tmp/tmpt6uuu8y4/ClassificationInference/artifacts'
[2021-03-31 22:29:09,518] DEBUG - Done copying local python dependant modules
[2021-03-31 22:29:09,521] DEBUG - Using Docker Base Image bentoml/model-server:0.11.0-py38
[2021-03-31 22:29:09,535] INFO - BentoService bundle 'ClassificationInference:20210331222908_FD0337' created at: /tmp/tmpt6uuu8y4
[2021-03-31 22:29:10,756] DEBUG - HTTPSConnectionPool(host='api.amplitude.com', port=443): Read timed out. (read timeout=1)
[2021-03-31 22:29:10,793] WARNING - Module `scratch_14` already loaded, using existing imported module.
Traceback (most recent call last):
  File "/home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py", line 41, in <module>
    test_bento_saving()
  File "/home/pieter/.config/JetBrains/PyCharm2020.3/scratches/scratch_14.py", line 38, in test_bento_saving
    bentoml.load_from_dir(dir)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 107, in wrapper
    return func(bundle_path, *args)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 258, in load_from_dir
    svc_cls = load_bento_service_class(bundle_path)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 107, in wrapper
    return func(bundle_path, *args)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 206, in load_bento_service_class
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py", line 41, in <module>
    test_bento_saving()
  File "/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py", line 37, in test_bento_saving
    inference.save_to_dir(dir)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/__init__.py", line 710, in save_to_dir
    return save_to_dir(self, path, version)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/bundler.py", line 228, in save_to_dir
    _write_bento_content_to_dir(bento_service, path)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/bundler.py", line 99, in _write_bento_content_to_dir
    module_name, module_file = copy_local_py_modules(
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/local_py_modules.py", line 85, in copy_local_py_modules
    target_module = _get_module(target_module)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/local_py_modules.py", line 73, in _get_module
    target_module = importlib.import_module(target_module)
  File "/home/pieter/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py", line 41, in <module>
    test_bento_saving()
  File "/tmp/tmpcyd65mz5/ClassificationInference/scratch_14.py", line 38, in test_bento_saving
    bentoml.load_from_dir(dir)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 107, in wrapper
    return func(bundle_path, *args)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 259, in load_from_dir
    svc = svc_cls()
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/__init__.py", line 448, in __init__
    self._config_artifacts()
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/__init__.py", line 519, in _config_artifacts
    self.artifacts.load_all(artifacts_path)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/artifacts/__init__.py", line 275, in load_all
    artifact.load(path)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/artifacts/__init__.py", line 158, in wrapped_load
    ret = original(*args, **kwargs)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/frameworks/keras.py", line 216, in load
    model = keras_module.models.load_model(
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 199, in load_model_from_hdf5
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 218, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 259, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/tensorflow/python/keras/losses.py", line 1854, in deserialize
    return deserialize_keras_object(
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 377, in deserialize_keras_object
    raise ValueError(
ValueError: Unknown loss function: categorical_focal_loss
Exception ignored in: <function BentoService.__del__ at 0x7f467ea93af0>
Traceback (most recent call last):
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/__init__.py", line 814, in __del__
    self.stop_dev_server(skip_log=True)
  File "/home/pieter/projects/orbisk/classification-model-training/.venv/lib/python3.8/site-packages/bentoml/service/__init__.py", line 800, in stop_dev_server
    if self._dev_server_interrupt_event:
AttributeError: 'ClassificationInference' object has no attribute '_dev_server_interrupt_event'
```

**Environment:**
 - OS: debian buster (10)
 - Python Version: 3.8.6
 - BentoML Version: 0.11.0

**Additional context**

I did a little research into the code and it turns out `ArtifactCollection.from_artifact_list()` uses `Artifact._copy()` and this only copies the name of the artifacts but not the other properties. Therefore, artifacts are not saved as json and weights, but just as an single h5 file. 

I've fixed it for now by using a custom artifact: 

```python
class CustomKerasModelArtifact(KerasModelArtifact):
    def __init__(self, name):
        super().__init__(name)
        self._store_as_json_and_weights = True
```

**Comment by pietermarsman** [comment]
Related: 
- https://github.com/bentoml/BentoML/issues/1535
- https://github.com/bentoml/BentoML/issues/1219

**Comment by yubozhao** [comment]
@pietermarsman Thank you for reporting and the extra research about it. 

Just like your additional comments, we are tracking it on #1219.  We are looking for to fix that issue in the upcoming releases.
