### ISSUE TITLE
When Providing Yatai URL, Bento Service "Save" Tries to Write to `/root` (and fails)

### ISSUE THREAD

**Issue by orcaman** [bentoml/BentoML#1594]
**Describe the bug**

I've downloaded the repo and ran the quick-start tutorial (Python version, not noteobok), where the only change was to add a yatai_url to the save function (I have a Yatai server up and running), [here](https://github.com/bentoml/BentoML/blob/master/guides/quick-start/main.py#L22).

```
saved_path = iris_classifier_service.save(yatai_url=my_yatai_url)
```

Before adding the yatai_url, the service saved successfully. I can see that the `response.uri.uri` in the [yatai client](https://github.com/bentoml/BentoML/blob/master/bentoml/yatai/client/bento_repository_api.py#L192) refers to a local path starting with my home dir. 

But when `yatai_url` is added to the save function, the same `response.uri.uri` starts with `/root`, which is a read-only fs (at least on MacOS), and the application throws an exception.

The full stack trace:
```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    saved_path = iris_classifier_service.save(yatai_url=yatai_url)
  File "/Users/orhiltch/github.com/bentoml/guides/quick-start/venv/lib/python3.7/site-packages/bentoml/service/__init__.py", line 738, in save
    return yc.repository.upload(self, version, labels)
  File "/Users/orhiltch/github.com/bentoml/guides/quick-start/venv/lib/python3.7/site-packages/bentoml/yatai/client/bento_repository_api.py", line 145, in upload
    return self.upload_from_dir(tmpdir, labels)
  File "/Users/orhiltch/github.com/bentoml/guides/quick-start/venv/lib/python3.7/site-packages/bentoml/yatai/client/bento_repository_api.py", line 196, in upload_from_dir
    shutil.copytree(saved_bento_path, response.uri.uri)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/root'

```

**To Reproduce**

**Expected behavior**
The model is saved successfully to Yatai. 

**Screenshots/Logs**
Here are the app's logs with debug on:
```
[2021-04-26 12:01:03,152] DEBUG - Loaded logging configuration from default configuration and environment variables.
[2021-04-26 12:01:03,153] DEBUG - Setting debug mode: ON for current session
[2021-04-26 12:01:03,482] DEBUG - Connecting YataiService gRPC server at: http://ab7c3a325ace4469da0195e3c6a2362e-131097832.us-east-1.elb.amazonaws.com:50051
[2021-04-26 12:01:03,490] DEBUG - Created temporary directory: /private/var/folders/gh/551tz8750fj72t3r0jyn1vlc0000gq/T/bentoml-temp-j7_bux0s
[2021-04-26 12:01:04,606] DEBUG - target py file path: /Users/orhiltch/github.com/bentoml/guides/quick-start/iris_classifier.py
[2021-04-26 12:01:04,608] DEBUG - import set: {'pandas', 'bentoml'}
[2021-04-26 12:01:04,610] DEBUG - copy_local_py_modules target_module_name: iris_classifier, target_module_file: /Users/orhiltch/github.com/bentoml/guides/quick-start/iris_classifier.py
[2021-04-26 12:01:04,610] DEBUG - Searching for local dependant modules of iris_classifier:/Users/orhiltch/github.com/bentoml/guides/quick-start/iris_classifier.py
[2021-04-26 12:01:04,611] DEBUG - Find bad module imports that can not be parsed properly: dict_keys(['pandas', 'bentoml', 'bentoml.adapters', 'bentoml.frameworks.sklearn'])
[2021-04-26 12:01:04,611] DEBUG - Copying user local python dependencies: {'iris_classifier': <module 'iris_classifier' from '/Users/orhiltch/github.com/bentoml/guides/quick-start/iris_classifier.py'>}
[2021-04-26 12:01:04,611] DEBUG - Copying local python module '/Users/orhiltch/github.com/bentoml/guides/quick-start/iris_classifier.py'
[2021-04-26 12:01:04,612] DEBUG - Creating empty __init__.py under folder:'/private/var/folders/gh/551tz8750fj72t3r0jyn1vlc0000gq/T/bentoml-temp-j7_bux0s/IrisClassifier'
[2021-04-26 12:01:04,612] DEBUG - Creating empty __init__.py under folder:'/private/var/folders/gh/551tz8750fj72t3r0jyn1vlc0000gq/T/bentoml-temp-j7_bux0s/IrisClassifier/artifacts'
[2021-04-26 12:01:04,612] DEBUG - Done copying local python dependant modules
[2021-04-26 12:01:04,613] DEBUG - Using Docker Base Image bentoml/model-server:0.12.1-py37
/private/var/folders/gh/551tz8750fj72t3r0jyn1vlc0000gq/T/bentoml-temp-j7_bux0s
[2021-04-26 12:01:05,540] DEBUG - BentoML in debug mode, keeping temp directory "/private/var/folders/gh/551tz8750fj72t3r0jyn1vlc0000gq/T/bentoml-temp-j7_bux0s"

```

**Environment:**
 - OS: MacOS 11.2.3 (20D91) Big Sur
 - Python 3.7.3
 - bentoml, version 0.12.1

**Comment by orcaman** [comment]
Update:  Confirming this is probably a macOS issue (readonly /root dir), if I run the same inside a docker container that starts from the official python3.8, everything works well.

**Comment by yubozhao** [comment]
@orcaman There is an FS as storage related enhancement we are working on.

I am going to assign this to me and keep you posted.

**Comment by yubozhao** [comment]
@orcaman We have a PR open and going under review for this issue https://github.com/bentoml/BentoML/pull/1586

After the PR merged, yatai will properly handle remote yatai with local FS as repository type.
