### ISSUE TITLE
Model serialization/deserialization with external functions aren't bundled when `serve-gunicorn`

### ISSUE THREAD

**Issue by henrywu2019** [bentoml/BentoML#1659]
**Describe the bug**
Saving the model works well, but serving it caused some issue.

**To Reproduce**
1. Run the following code to save the model:
```
import bentoml
from bentoml.adapters import ImageInput
from bentoml.frameworks.pytorch import PytorchModelArtifact

@bentoml.env(infer_pip_packages=True)
@bentoml.artifacts([PytorchModelArtifact('model')])
class ENetModelService(bentoml.BentoService):

    @bentoml.api(input=ImageInput(), batch=False)
    def predict(self, img):
        print(type(img))
        outputs = self.artifacts.model(img)
        return outputs

svc = ENetModelService()

from efficientnet_pytorch import EfficientNet

model = EfficientNet.from_name('efficientnet-b0')
model.eval().to("cpu")

svc.pack('model', model)
p = svc.save()
```

2. Run the following code to serve the model
```
$ bentoml serve ENetModelService:latest
[2021-06-05 22:11:39,950] INFO - Getting latest version ENetModelService:20210605221048_58C1E4
[2021-06-05 22:11:39,985] INFO - Starting BentoML API proxy in development mode..
[2021-06-05 22:11:40,880] INFO - Your system nofile limit is 256, which means each instance of microbatch service is able to hold this number of connections at same time. You can increase the number of file descriptors for the server process, or launch more microbatch instances to accept more concurrent connection.
======== Running on http://0.0.0.0:5000 ========
(Press CTRL+C to quit)
[2021-06-05 22:11:41,092] INFO - Starting BentoML API server in development mode..
[2021-06-05 22:11:41,445] WARNING - pip package requirement `imageio` not found in current python environment
[2021-06-05 22:11:41,445] WARNING - BentoML by default does not include spacy and torchvision package when using PytorchModelArtifact. To make sure BentoML bundle those packages if they are required for your model, either import those packages in BentoService definition file or manually add them via `@env(pip_packages=['torchvision'])` when defining a BentoService
Process Process-1:
Traceback (most recent call last):
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/server/__init__.py", line 85, in _start_dev_server
    bento_service = load_from_dir(saved_bundle_path)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 107, in wrapper
    return func(bundle_path, *args)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 268, in load_from_dir
    svc_cls = load_bento_service_class(bundle_path)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 107, in wrapper
    return func(bundle_path, *args)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/saved_bundle/loader.py", line 206, in load_bento_service_class
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/fuhwu/bentoml/repository/ENetModelService/20210605221048_58C1E4/ENetModelService/enet.py", line 23, in <module>
    p = svc.save()
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/service/__init__.py", line 738, in save
    return yc.repository.upload(self, version, labels)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/yatai/client/bento_repository_api.py", line 143, in upload
    save_to_dir(bento_service, tmpdir, version, silent=True)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/saved_bundle/bundler.py", line 228, in save_to_dir
    _write_bento_content_to_dir(bento_service, path)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/saved_bundle/bundler.py", line 94, in _write_bento_content_to_dir
    bento_service.env.infer_pip_packages(bento_service)
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/service/env.py", line 318, in infer_pip_packages
    dependencies_map = bento_service.infer_pip_dependencies_map()
  File "/Users/fuhwu/miniconda3/envs/bentoml/lib/python3.8/site-packages/bentoml/service/__init__.py", line 867, in infer_pip_dependencies_map
    bento_service_module = sys.modules[self.__class__.__module__]
KeyError: 'enet'
```

**Expected behavior**
be able to serve

**Screenshots/Logs**
above

**Environment:**
 - OS: MacOS 10.14.3
 - Python Version: Python 3.8
 - BentoML Version: 0.12.1

**Additional context**
NA

**Comment by aarnphm** [comment]
can you try adding `efficientnet_pytorch` to `env` decorator under `pip_package=` args?

**Comment by henrywu2019** [comment]
Yes, but the error still happens.

**Comment by aarnphm** [comment]
`outputs = self.artifacts.net(img)` this should be `self.artifacts.model(img)`

**Comment by henrywu2019** [comment]
That is my typo, but the error still happens after I changed `net` to `model`. You can test on your side. Let me know if it really works on your side.

**Comment by henrywu2019** [comment]
It seems I have no permission to reopen the issue. Can you please reopen it?

**Comment by aarnphm** [comment]
can you define your service and model separately. Everything runs fine with my end @henrywu2019

**Comment by aarnphm** [comment]
cc Chaoyu solution to put `if __name__ == "__main__"` before 
``` python
if __name__ == "__main__":
    svc = ENetModelService()
    
    from efficientnet_pytorch import EfficientNet
    
    model = EfficientNet.from_name('efficientnet-b0')
    model.eval().to("cpu")
    
    svc.pack('model', model)
    p = svc.save()
```
would also work

**Comment by aarnphm** [comment]
#1663 FYI. Closing this for now.

**Comment by henrywu2019** [comment]
[yolo.zip](https://github.com/bentoml/BentoML/files/6610154/yolo.zip)

There is another example I got similar error with `if __name__ == "__main__"` added.

yolo_model.py:

```
from bentoml import env, artifacts, api, BentoService
from bentoml.adapters import ImageInput
from bentoml.frameworks.pytorch import PytorchModelArtifact
import imageio
import torch
@env(infer_pip_packages=True)
@artifacts([PytorchModelArtifact("torch_model")])
class YoloObjectDetector(BentoService):
    @api(input=ImageInput(), batch=False)
    def predict_single_image(self, img: imageio.core.util.Array):
        img = img[:, :, ::-1]  # RGB = > BGR
        img = torch.from_numpy(img).to("cpu")
        pred = self.artifacts.torch_model(img)[0]
        return ""
```

yolo_packer.py:

```
from yolo_model import YoloObjectDetector
from yolov5.models.experimental import attempt_load
if __name__ == "__main__":
    detector = YoloObjectDetector()
    model_path = "yolov5s.pt"
    model = attempt_load(model_path, map_location="cpu")
    detector.pack("torch_model", model)
    saved_path = detector.save()
    print(saved_path)
```

The error:

![image](https://user-images.githubusercontent.com/47995124/121043581-9ded4c00-c769-11eb-9561-d3155056b519.png)

**Comment by aarnphm** [comment]
did `attempt_load` changed `model` to `eval`? Either that your forgot to `model.eval()` for evaluation step. Refers to [In 17](https://github.com/bentoml/gallery/blob/master/pytorch/news-classification-gpu/news-classification.ipynb) for loading and setting up model for evaluation.

**Comment by henrywu2019** [comment]
Sorry, I don't understand why it is related to `eval` mode and `attempt_loads` implementation. Are there some basic rules about the model packing I am not aware of? Do you mean `yolo_model.py` and `yolo_pack.py` are implemented wrongly? I can run them without any issue.

**Comment by aarnphm** [comment]
In the function `attempt_load` from `utralytics/yolov5` if you take a look in the way they implements it, they are lazy loading `models` with [L144](https://github.com/ultralytics/yolov5/blob/abb2a96e91340df74b2526d925f2ecba24973dec/models/experimental.py#L114). This is the error you see `ModuleNotFoundError`

wrt `eval` mode, I was just wondering at the time whether `attempt_load` also sets the model to `eval` mode.

So the solution is to basically implements `attempt_load` yourself, or create a YOLO model class to load the weight saved

**Comment by aarnphm** [comment]
@parano This occurs when users want to deserialize PyTorch model with a function from a library. And the bundle doesn't have any knowledge of class definition.

For now users have to explicit define their model class in order to serve with BentoML.

**Comment by BakingBrains** [comment]
> Sorry, I don't understand why it is related to `eval` mode and `attempt_loads` implementation. Are there some basic rules about the model packing I am not aware of? Do you mean `yolo_model.py` and `yolo_pack.py` are implemented wrongly? I can run them without any issue.

@henrywu2019 were you able to solve this issue??
