### ISSUE TITLE
Inference in SageMaker model server fails with missing attribute error when using JsonInput

### ISSUE THREAD

**Issue by tjcarroll11** [bentoml/BentoML#1715]
**Describe the bug**
When using `JsonInput` (or, I believe, any input that uses `@decompress_gzip_request`), inference fails.

**To Reproduce**
Steps to reproduce the issue:
1. Follow steps outlined in [this tutorial](https://course.fast.ai/deployment_bento)
2. Add a JsonInput
3. Deploy 
4. Hit endpoint (`aws sagemaker-runtime invoke-endpoint --region 'us-east-1' --endpoint-name 'dev-psc-baseline-2' --body 'eyJ0ZXh0IjogIm5ldyBsYXB0b3BzIn0K' --content-type=application/json test.txt`)

**Expected behavior**
Inference returns a prediction

**Screenshots/Logs**
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/yatai/deployment/sagemaker/model_server.py", line 20, in view_function
    return api.handle_request(request)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/inference_api.py", line 294, in handle_request
    inf_task = self.input_adapter.from_http_request(request)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/adapters/utils.py", line 117, in _method
    if req.headers.content_encoding in {"gzip", "x-gzip"}:
```

**Environment:**
 - Linux (Amazon Linux AMI 2018.03, Fedora)
 - Python 3.7.10
 - BentoML 0.13.0

**Comment by aarnphm** [comment]
@tjcarroll11 can you confirm that your PR fixed this ticket?

**Comment by tjcarroll11** [comment]
@aarnphm would you be able to release a patch? When I tried building from a local install (with this fix applied), I got errors. I think it had to do with the fact that the dockerfile installed from pip.

**Comment by parano** [comment]
@tjcarroll11 if you re-create the bento bundle with this branch and run the deployment CLI to deploy again, it will reflect the changes in your PR and you will be able to test it out. BentoML actually bundles itself if it has detected that it's running from an `editable` installation -- e.g. if you install your branch with `pip install -e .` in the root directory of the git repo.

**Comment by aarnphm** [comment]
for now https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md

**Comment by tjcarroll11** [comment]
Confirmed that the issue is resolved.
