### ISSUE TITLE
BentoService.pack throws "Expected a value of type 'Tensor'.." exception after pack_padded_sequence is used

### ISSUE THREAD

**Issue by BartlomiejSkwira** [bentoml/BentoML#1741]
**Describe the bug**
I have a Pytorch Lightning module implementing the forward function. When I try to `.pack` from a BentoService I get an exception. 
```
RuntimeError:

type(Tensor 0) -> (Tensor 0):
Expected a value of type 'Tensor' for argument '0' but instead found type '__torch__.torch.nn.utils.rnn.PackedSequence'.
:
  File "test_upload_models.py", line 64
            X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        print(type(X))  # exception is here
              ~~~~ <--- HERE
        if self.use_gpu:
            X = X.cuda()
```
The issue happens after line:
```
def forward(self, X, X_lengths):
        X_lengths = X_lengths.flatten()
        X = nn.utils.rnn.pack_padded_sequence(
            X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
        )
```

This looks like `pack_padded_sequence` is causing some sort of issue with X

**To Reproduce**
My code:
```python
import bentoml
import torch
from bentoml.adapters import DataframeInput
from bentoml.frameworks.pytorch import PytorchLightningModelArtifact
from lstm.lstm_model_lightning import LSTMClassifier
import pytorch_lightning as pl
from torch.autograd import Variable
import torch.nn as nn


class LSTMClassifier(pl.LightningModule):
    def __init__(
        self,
        input_dim,
        hidden_dim,
        batch_size,
        num_layers=3,
        use_gpu=True,
        seed: int = 37,
    ):
        super(LSTMClassifier, self).__init__()
        self.hidden_dim = hidden_dim
        self.batch_size = batch_size
        self.use_gpu = use_gpu
        self.num_layers = num_layers
        self.seed = seed

        self.loss_function = nn.BCELoss()

        self.lstm = nn.LSTM(
            input_dim,
            hidden_dim,
            batch_first=True,
            num_layers=self.num_layers,
            dropout=0.3,
        )
        self.dropout = nn.Dropout(0.4)
        self.hidden2label = nn.Linear(hidden_dim, 1)
        self.hidden = self.init_hidden()
        self.save_hyperparameters()

    def init_hidden(self):
        if self.use_gpu:
            h0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).cuda()
            )
            c0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).cuda()
            )
        else:
            h0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim)
            )
            c0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim)
            )
        return h0, c0

    def forward(self, X, X_lengths):
        X_lengths = X_lengths.flatten()
        X = nn.utils.rnn.pack_padded_sequence(
            X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        print(type(X))  # exception is here
        if self.use_gpu:
            X = X.cuda()
        lstm_out, self.hidden = self.lstm(X, self.hidden)
        lstm_out_unpacked, _ = nn.utils.rnn.pad_packed_sequence(lstm_out)
        y = self.dropout(lstm_out_unpacked[-1])
        y = self.hidden2label(y)
        y = torch.sigmoid(y)
        return y

model = LSTMClassifier(input_dim=19,hidden_dim=500, batch_size=512, use_gpu=False)


@bentoml.env(infer_pip_packages=True)
@bentoml.artifacts([PytorchLightningModelArtifact('model')])
class PytorchLightingService(bentoml.BentoService):
    @bentoml.api(input=DataframeInput(), batch=True)
    def predict(self, df):
        input_tensor = torch.from_numpy(df.to_numpy())
        return self.artifacts.model(input).numpy()

bento_service = PytorchLightingService()

# Pack Pytorch Lightning model instance
bento_service.pack('model', model) # exception is here

bento_service.save()
```
Exception:
```bash
[2021-07-09 12:15:51,162] DEBUG - Configured logging with simple configuration, level=DEBUG, directory=/root/bentoml/logs, console_enabled=True, file_enabled=True
[2021-07-09 12:15:52,731] DEBUG - Using BentoML default docker base image 'bentoml/model-server:0.13.0-py37'
[2021-07-09 12:15:52,733] INFO - PytorchLightningArtifact is packing a pytorch lightning model instance as torchscript module
/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py:169: LightningDeprecationWarning: The `LightningModule.datamodule` property is deprecated in v1.3 and will be removed in v1.5. Access the datamodule through using `self.trainer.datamodule` instead.
  "The `LightningModule.datamodule` property is deprecated in v1.3 and will be removed in v1.5."
Traceback (most recent call last):
  File "test_upload_models.py", line 88, in <module>
    bento_service.pack('model', model)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/__init__.py", line 764, in pack
    self.artifacts.get(name).pack(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 128, in wrapped_pack
    ret = original(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/frameworks/pytorch.py", line 240, in pack
    self._model = path_or_model.to_torchscript()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1807, in to_torchscript
    torchscript_module = torch.jit.script(self.eval(), **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_script.py", line 1097, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 478, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 355, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:

type(Tensor 0) -> (Tensor 0):
Expected a value of type 'Tensor' for argument '0' but instead found type '__torch__.torch.nn.utils.rnn.PackedSequence'.
:
  File "test_upload_models.py", line 64
            X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        print(type(X))  # exception is here
              ~~~~ <--- HERE
        if self.use_gpu:
            X = X.cuda()
```

**Expected behavior**
Pack should work without exceptions.

**Environment:**
 - OS: docker image `pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel` with `Ubuntu 18.04.5 LTS` 
 - Python Version: 3.7.10
 - BentoML Version: 0.13.0
- model: LSTM wrapped in Pytorch Lightning 
- Pytorch Lightning version: `1.3.8`
- Docker image: `pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel`
- hardware: I have a GPU: `nvidia-smi` shows it's working, python code returns `torch.cuda.is_available() => True`

**Comment by BartlomiejSkwira** [comment]
I have added a logger to the script with:
```
logger = logging.getLogger("prepare_models")
logger.setLevel(logging.INFO)
logger.addHandler(get_console_handler())
```
And do:
```
    def forward(self, X, X_lengths):
        X_lengths = X_lengths.flatten()
        logger.info("%%%%%%%%%%%%%%%%")
        .....
```
And get exception:
```
RuntimeError:
attribute lookup is not defined on python value of type 'Logger':
  File "test_upload_models.py", line 68
    def forward(self, X, X_lengths):
        X_lengths = X_lengths.flatten()
        logger.info("%%%%%%%%%%%%%%%%5")
        ~~~~~~~~~~~ <--- HERE
        logger.info(type(X))
        logger.info(type(X_lengths))
```
Weird 🤔

**Comment by aarnphm** [comment]
can you try out this project structure first? https://docs.bentoml.org/en/latest/quickstart.html#preface

**Comment by larme** [comment]
Hi, Bartek

BentoML use `to_torchscript` Internally when packing a model, I tried your code and even without using BentoML, the model still throw an error when calling `to_torchscript` like this:

```python
import bentoml
import torch
from bentoml.adapters import DataframeInput
from bentoml.frameworks.pytorch import PytorchLightningModelArtifact
from lstm.lstm_model_lightning import LSTMClassifier
import pytorch_lightning as pl
from torch.autograd import Variable
import torch.nn as nn


class LSTMClassifier(pl.LightningModule):
    def __init__(
        self,
        input_dim,
        hidden_dim,
        batch_size,
        num_layers=3,
        use_gpu=True,
        seed: int = 37,
    ):
        super(LSTMClassifier, self).__init__()
        self.hidden_dim = hidden_dim
        self.batch_size = batch_size
        self.use_gpu = use_gpu
        self.num_layers = num_layers
        self.seed = seed

        self.loss_function = nn.BCELoss()

        self.lstm = nn.LSTM(
            input_dim,
            hidden_dim,
            batch_first=True,
            num_layers=self.num_layers,
            dropout=0.3,
        )
        self.dropout = nn.Dropout(0.4)
        self.hidden2label = nn.Linear(hidden_dim, 1)
        self.hidden = self.init_hidden()
        self.save_hyperparameters()

    def init_hidden(self):
        if self.use_gpu:
            h0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).cuda()
            )
            c0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim).cuda()
            )
        else:
            h0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim)
            )
            c0 = Variable(
                torch.zeros(self.num_layers, self.batch_size, self.hidden_dim)
            )
        return h0, c0

    def forward(self, X, X_lengths):
        X_lengths = X_lengths.flatten()
        X = nn.utils.rnn.pack_padded_sequence(
            X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        print(type(X))  # exception is here
        if self.use_gpu:
            X = X.cuda()
        lstm_out, self.hidden = self.lstm(X, self.hidden)
        lstm_out_unpacked, _ = nn.utils.rnn.pad_packed_sequence(lstm_out)
        y = self.dropout(lstm_out_unpacked[-1])
        y = self.hidden2label(y)
        y = torch.sigmoid(y)
        return y

model = LSTMClassifier(input_dim=19,hidden_dim=500, batch_size=512, use_gpu=False)
tmp = model.to_torchscript()
```

will give

```
RuntimeError: 

type(Tensor 0) -> (Tensor 0):
Expected a value of type 'Tensor' for argument '0' but instead found type '__torch__.torch.nn.utils.rnn.PackedSequence'.
:
  File "<ipython-input-7-22e155342c56>", line 63
            X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        print(type(X))  # exception is here
              ~~~~ <--- HERE
        if self.use_gpu:
            X = X.cuda()
```

and if we remove line `print(type(X))`, the output is

```
RuntimeError: 
Tried to access nonexistent attribute or method 'cuda' of type '__torch__.torch.nn.utils.rnn.PackedSequence'.:
  File "<ipython-input-8-3d95a080aae8>", line 65

        if self.use_gpu:
            X = X.cuda()
                ~~~~~~ <--- HERE
        lstm_out, self.hidden = self.lstm(X, self.hidden)
        lstm_out_unpacked, _ = nn.utils.rnn.pad_packed_sequence(lstm_out)
```

I wonder if code

```python
X = nn.utils.rnn.pack_padded_sequence(
       X, X_lengths.cpu(), batch_first=True, enforce_sorted=False
)
```

confused the torchscript compiler

**Comment by aarnphm** [comment]
https://github.com/pytorch/pytorch/issues/41869

**Comment by BartlomiejSkwira** [comment]
@larme thanks for taking the time and reproducing my issue, now I can reproduce it with just PyTorch as well. I'll move the discussion to PyTorch forums. Closing this thread


@aarnphm Just curious: not sure how structuring my code into separate files would help? does Bento depend on project structure?

**Comment by aarnphm** [comment]
> @aarnphm Just curious: not sure how structuring my code into separate files would help? does Bento depend on project structure?

@BartlomiejSkwira I saw you put your model defintion and BentoML service defintion in a same file. It brought up some issues for others in the past by doing that. We are currently working on redesigning a new API for this.

**Comment by BartlomiejSkwira** [comment]
I think I know where the issue is, `Torchscript` has some unsupported constructs, a list is available at https://pytorch.org/docs/stable/jit_unsupported.html#jit-unsupported, in the `PyTorch Unsupported Modules and Classes` we see that `Torchscript` is not supporting `torch.nn.RNN`. 
![image](https://user-images.githubusercontent.com/1316517/125270112-a5c08300-e309-11eb-9747-8b0dda49fb56.png)


LSTM is a RNN-type model, it inherits like this 
```
class LSTM(RNNBase):
    r"""Applies a multi-layer long short-term memory (LSTM) RNN to an input
    sequence.
    """
```

So essentially I think can't do `to_torchscript` on a LSTM model.

Can BentoML serve a model without doing `.pack` on it?

**Comment by BartlomiejSkwira** [comment]
OK, I can't use `PackedSequence`  with `TorchScript`:

![image](https://user-images.githubusercontent.com/1316517/125272436-241e2480-e30c-11eb-98d9-4b961e9a8661.png)


Source - Offical docs:
https://pytorch.org/blog/optimizing-cuda-rnn-with-torchscript/#variable-length-sequences-best-practices

**Comment by aarnphm** [comment]
> **Can BentoML serve a model without doing `.pack` on it?**

This is merely impossible with the current api since we need to bundle the model into the service in order to serve the bundle. We are currently working on a new API with packaging so stay tuned.
