### ISSUE TITLE
SageMaker cannot hit the endpoint

### ISSUE THREAD

**Issue by NaxAlpha** [bentoml/BentoML#1822]
**Describe the bug**

After deploying the dev endpoint (ref: #1821), I cannot get the response with this:
```bash
curl -i \
    -X POST \
    -F image=@data/mobile-sample.png \
    https://123.execute-api.region.amazonaws.com/prod/predict
```
Looking at couldwatch: logs show this error:
![image](https://user-images.githubusercontent.com/11090613/130744271-6c13294b-32c7-4f09-a6ee-2b7cbb57ba54.png)

**To Reproduce**

1. Deploy an API on SageMaker that takes an image as input.
2. Call the API by sending an Image

**Expected behavior**

Running the API by using `bentoml server Model:latest` works but is not reproducible for the deployed API on SageMaker.

**Screenshots/Logs**

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/bento/wsgi.py", line 25, in view_function
    response = api.handle_request(req)
  File "/opt/conda/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 294, in handle_request
    inf_task = self.input_adapter.from_http_request(request)
  File "/opt/conda/lib/python3.8/site-packages/bentoml/adapters/utils.py", line 129, in _method
    return method(self, req)
  File "/opt/conda/lib/python3.8/site-packages/bentoml/adapters/file_input.py", line 148, in from_http_request
    _, _, files = HTTPRequest.parse_form_data(req)
  File "/opt/conda/lib/python3.8/site-packages/bentoml/types.py", line 234, in parse_form_data
    stream, form, files = parse_form_data(environ, silent=False)
  File "/opt/conda/lib/python3.8/site-packages/werkzeug/formparser.py", line 126, in parse_form_data
    return FormDataParser(
  File "/opt/conda/lib/python3.8/site-packages/werkzeug/formparser.py", line 230, in parse_from_environ
    return self.parse(get_input_stream(environ), mimetype, content_length, options)
  File "/opt/conda/lib/python3.8/site-packages/werkzeug/formparser.py", line 265, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/conda/lib/python3.8/site-packages/werkzeug/formparser.py", line 142, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    raise ValueError("Missing boundary")
```

**Environment:**
 - OS: Debian 10
 - Python Version: 3.7.10
 - BentoML Version: 0.13.1
- Using Docker Image: `bentoml/model-server:0.13.1-py38-gpu`

**Additional context**

**Comment by jjmachan** [comment]
Firstly really sorry for the late reply. The issue seems to be a configuration error in the API Gateway. This only happens when you passing data as a `multipart/form-data` type but if you pass it in a binary format it will work. 

I'm working on adding support for `multipart/form-data` too but in the meantime, you can refer https://stackoverflow.com/a/56132015 or https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html to get an idea of how to solve it on your end. 

Again really sorry for the late reply but I hope this helps : )

**Comment by NaxAlpha** [comment]
Thanks a lot for the update. Any timeline for the fix? and is it related to this repo or [bentoml/aws-sagemaker-deploy](https://github.com/bentoml/aws-sagemaker-deploy)?

**Comment by NaxAlpha** [comment]
BTW I also did try the binary method like this:
```
curl -i \
    -X POST \
    --header "Content-Type:application/octet-stream" \
    --data-binary @data/mobile-sample.png \
    https://123.execute-api.region.amazonaws.com/prod/predict
```
But I get this error:
![image](https://user-images.githubusercontent.com/11090613/132175270-f180e724-d560-40aa-b0e7-623a2f0b0214.png)

**Comment by jjmachan** [comment]
which input handler are you using?

**Comment by NaxAlpha** [comment]
Here is the sample service I am using:
```
class Model(bentoml.BentoService):
    @bentoml.api(input=ImageInput(), batch=False)
    def predict(self, image):
        img = np.array(image)
        ...
```
