### ISSUE TITLE
Headers are not decoded by aiohttp.worker.GunicornWebWorker

### ISSUE THREAD

**Issue by Juggernaut1997** [bentoml/BentoML#1827]
**Bug Description**
The headers passed to the request are getting encoded but not decoded. This issue arise for the port on which the application redirects to example: 5000.

Logs
```
[2021-08-26 06:40:04,346] INFO - Starting BentoML proxy in production mode..
[2021-08-26 06:40:04,347] INFO - Starting BentoML API server in production mode..
[2021-08-26 06:40:04,605] INFO - Running micro batch service on :8059
[2021-08-26 06:40:04 +0000] [28006] [INFO] Starting gunicorn 20.0.4
[2021-08-26 06:40:04 +0000] [28006] [INFO] Listening at: http://0.0.0.0:49023 (28006)
[2021-08-26 06:40:04 +0000] [28006] [INFO] Using worker: sync
[2021-08-26 06:40:04 +0000] [28007] [INFO] Booting worker with pid: 28007
[2021-08-26 06:40:04 +0000] [28001] [INFO] Starting gunicorn 20.0.4
[2021-08-26 06:40:04 +0000] [28001] [INFO] Listening at: http://0.0.0.0:8059 (28001)
[2021-08-26 06:40:04 +0000] [28001] [INFO] Using worker: aiohttp.worker.GunicornWebWorker
```

In my case, I am sending a Authorization token. But it is not able to read it because the header looks like:
```
b'\x80\x04\x95\xa8\x01\x00\x00\x00\x00\x00\x00\x8c\rbentoml.types\x94\x8c\x0bHTTPRequest\x94\x93\x94)\x81\x94}\x94(\x8c\x07headers\x94h\x00\x8c\x0bHTTPHeaders\x94\x93\x94]\x94(\x8c\x04Host\x94\x8c\x0e127.0.0.1:8059\x94\x86\x94\x8c\nUser-Agent\x94\x8c\x0bcurl/7.68.0\x94\x86\x94\x8c\rAuthorization\x94\x8c\x84Bearer <token>\x94\x86\x94\x8c\x06accept\x94\x8c\x03*/*\x94\x86\x94\x8c\x0cContent-Type\x94\x8c\x10application/json\x94\x86\x94\x8c\x0eContent-Length\x94\x8c\x0250\x94\x86\x94e\x85\x94R\x94\x8c\x04body\x94C2[[7,0.27,0.36,20.7,0.045,45,170,1.001,3,0.45,8.8]]\x94ub\x85\x94.'
[2021-08-26 06:40:10,643] ERROR - Error caught in API function:
Traceback (most recent call last):
  File "/python3/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 176, in wrapped_func
    return self._user_func(*args, **kwargs)
  File "<Path to serving script>", line 66, in predict
    auth_token = request.headers["Authorization"]
  File "/python3/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_AUTHORIZATION'
```

**To Reproduce**
1. In the predict functionality, add a request.header to read a particular header which will be send via the request.
2. Deploy the application using bentoml serve-gunicorn ... command and try to pass the header while sending the request.
3. It will give the `HTTP_{key}` error

**Serving Scrip**
```
@env(infer_pip_packages=True, docker_base_image="python:3.8.10")
@artifacts([SklearnModelArtifact('model')])
class test:
    @api(input=DataframeInput(), batch=True)
    def predict(self, df: pd.DataFrame):
        """
        An inference API named `predict` with Dataframe input adapter, which codifies
        how HTTP requests or CSV files are converted to a pandas Dataframe object as the
        inference API function input
        """
        start_time = time.time()
        req = HTTPRequest()
        print(req.from_flask_request(request).body)
#         print("request: ", request.headers)
        auth_token = request.headers["Authorization"]
        auth = self.token(auth_token)
        try:
          if auth["message"] == "Success":
            pred = self.artifacts.model.predict(df)[0]
            print("pred time: ", time.time()-start_time)
            return "Prediction: "+str(pred), 200
          else:
            return "Incorrect Bearer Token", 401
        except Exception:
          return "Error occured in the application", 500
```

For BentoML CLI commands.:
```
bentoml serve-gunicorn "<image name>:<tag>" --port 8000
```

**Environment:**
 - Python Version [e.g. Python 3.8.10]
 - BentoML Version [e.g. BentoML-0.13.1]

**Comment by parano** [comment]
Hi @Juggernaut1997 - I think this is expected behavior, you may write another line of code that decode the header value. Note that BentoML actually does not expect users to use the `request` object directly, in BentoML 1.0, we are adding a new abstraction `request_context` which will allow users to access HTTP headers and additional context information, see feature ticket here: https://github.com/bentoml/BentoML/issues/2195

Before #2195 is release, you may also use the mounting custom ASGI or WSGI app feature in BentoML 1.0.  Here are two examples using Flask and FastAPI to add additional endpoints to a BentoML service, where you may have access to the request object in its native form:

## Mounting a Flask App to Service

Use `Service#mount_wsgi_app` to mount flask app to a Service. This works for any WSGI based python web application. 

```python
# hello.py
import bentoml
from bentoml.io import JSON
from flask import Flask

flask_app = Flask("sample_wsgi_app")

@flask_app.route("/hello")
def hello_world():
    return "<p>Hello, World!</p>"


svc = bentoml.Service("bento-server-test")
svc.mount_wsgi_app(flask_app)

@svc.api(input=JSON(), output=JSON())
def predict(input_json):
    return {'input_received': input_json, 'foo': 'bar'}

app = svc.asgi_app
```


## Mounting a FastAPI app to Service

Use `Service#mount_asgi_app` to mount FastAPI app to a Service. This works for any ASGI based python web application. 

```python
import bentoml
from bentoml.io import JSON

from fastapi import FastAPI

fastapi_app = FastAPI()

@fastapi_app.get("/hello")
def hello():
    return {"Hello": "World"}

svc = bentoml.Service("hello")
svc.mount_asgi_app(fastapi_app)

@svc.api(input=JSON(), output=JSON())
def predict(input_json):
    return {'input_received': input_json, 'foo': 'bar'}

app = svc.asgi_app
```
