### ISSUE TITLE
libGL.so.1 does not exist in base docker container

### ISSUE THREAD

**Issue by pat-doyle-idexx** [bentoml/BentoML#1837]
cv2 cannot currently be used as a dependency in bentoml docker container due to libgl1 not being present:

```
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/opt/conda/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
self.load_wsgi()
File "/opt/conda/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
self.wsgi = self.app.wsgi()
File "/opt/conda/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/opt/conda/lib/python3.9/site-packages/bentoml/server/gunicorn_server.py", line 125, in load
bento_service = load_from_dir(self.bento_service_bundle_path)
File "/opt/conda/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 110, in wrapper
return func(bundle_path, *args)
File "/opt/conda/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 271, in load_from_dir
svc_cls = load_bento_service_class(bundle_path)
File "/opt/conda/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 110, in wrapper
return func(bundle_path, *args)
File "/opt/conda/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 209, in load_bento_service_class
spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "./PyTorchCraftCropper/craft_service.py", line 6, in <module>
import cv2
File "/opt/conda/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
from .cv2 import *
```
Could libGL be added to the base container and/or could a feature be planned to allow custom dependencies at the OS level be added to the base?

**Comment by pat-doyle-idexx** [comment]
replacing opencv-python with opencv-python-headless fixes the error.
