### ISSUE TITLE
Pytorch Training model - Error: "daemonic processes are not allowed to have children"

### ISSUE THREAD

**Issue by amarquinar** [bentoml/BentoML#1907]
Hi experts, 

I created a Bento Service to train a Pytorch Object Detect model. But I have a problem when I calling the service, the system shows the message: "daemonic processes are not allowed to have children".

I'm starting my server with the following sentence:

bentoml serve-gunicorn PytorchODTrainer:latest --workers=10 --timeout=900

The complete error message after I call my service:

```
[2021-10-19 12:38:19,407] ERROR - Error caught in API function:
Traceback (most recent call last):
  File "/home/amarquinar/.virtualenvs/pve_pytorch191_py38/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 176, in wrapped_func
    return self._user_func(*args, **kwargs)
  File "/home/amarquinar/bentoml/repository/PytorchODTrainer/20211019113653_B59C82/PytorchODTrainer/pytorch_od_pipeline_srv.py", line 66, in process_pipeline
    model = train_pipe.train_model(data_loader, data_loader_test, data['num_classes'], data['epochs'])
  File "/home/amarquinar/bentoml/repository/PytorchODTrainer/20211019113653_B59C82/PytorchODTrainer/torch_train_pipe_manager.py", line 73, in train_model
    train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=10)
  File "/home/amarquinar/bentoml/repository/PytorchODTrainer/20211019113653_B59C82/PytorchODTrainer/engine.py", line 26, in train_one_epoch
    for images, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/amarquinar/bentoml/repository/PytorchODTrainer/20211019113653_B59C82/PytorchODTrainer/utils.py", line 180, in log_every
    for obj in iterable:
  File "/home/amarquinar/.virtualenvs/pve_pytorch191_py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/amarquinar/.virtualenvs/pve_pytorch191_py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/amarquinar/.virtualenvs/pve_pytorch191_py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 919, in __init__
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
```

If I execute my program without bento serve, it works fine.

On BentoML service, I think the problem is because I use 4 workers when create a Pytorch Dataloader. But If I put workers=0, I have a time out error.

```
data_loader = torch.utils.data.DataLoader(
            dataset, batch_size=2, shuffle=True, num_workers=4, 
            collate_fn=utils.collate_fn)

data_loader_test = torch.utils.data.DataLoader(
            dataset_test, batch_size=1, shuffle=False, num_workers=4,  
            collate_fn=utils.collate_fn)

```     

Environment:

OS: Ubuntu 20.04
Python Version: 3.8
BentoML Version: 0.13.1

Could you help me, please?

Thanks.

**Comment by aarnphm** [comment]
Hi @amarquinar , can you provide your service as well as your project structure for the service?

**Comment by parano** [comment]
I think this one was resolved in the slack community, the user code was creating new thread that's causing the problem. Closing now, feel free to reopen if you continue to run into the problem @amarquinar

**Comment by davidberenstein1957** [comment]
I am experiencing this same issue while using a transformers pipeline to do batch prediction within a batch API. Without the batch prediction of the transformers model it does work, but using batches it doesn't.

**project tree**
```
📦project
 ┣ 📂artifacts
 ┃ ┣ 📜sentiment_classification_model_artifact.py
 ┃ ┗ 📜__init__.py
 ┣ 📜bento_packer.py
 ┗ 📜bento_service.py
``` 


```
import bentoml
from bentoml.adapters import JsonInput
from artifacts import SentimentClassifcationModelArtifact
from typing import List
from bentoml.types import JsonSerializable, InferenceTask

@bentoml.env(infer_pip_packages=True)
@bentoml.artifacts([SentimentClassifcationModelArtifact("model")])
class SentimentClassifierService(bentoml.BentoService):
    @bentoml.api(input=JsonInput(), batch=True) 
    def predict(self, parsed_json_list: List[JsonSerializable], tasks: List[InferenceTask]) -> List[JsonSerializable]:
        """
        Predicts the class of the input text

        Args:
            text (str): input text

        Returns:
            list: list of tuples containing label name and confidence pairs for each label
                        
        example request {"text": "This is a text."}
        >>> list(self.artifacts.model('test')[0].keys())
        ['label', 'score']
        """
        validated_texts = []
        for json, task in zip(parsed_json_list, tasks):
            try:
                validated_texts.append(json['text'])
            except:
                task.discard(http_status=400, err_msg=f'incorrect input check usage: {self.predict.__doc__}')
        predictions = self.artifacts.model(validated_texts)
        return predictions
```

**Comment by parano** [comment]
Thanks for reporting @davidberenstein1957 - this is a known issue and it has been resolved in the next version of BentoML. A workaround for your use case now, is to set the pipeline init parameter num_workers to 1. e.g. `predictions = self.artifacts.model(validated_texts, num_workers=1)`

**Comment by davidberenstein1957** [comment]
Sadly, this approach doesn't resolve the issue for me.

**Comment by roundtable-swk** [comment]
> Thanks for reporting @davidberenstein1957 - this is a known issue and it has been resolved in the next version of BentoML. A workaround for your use case now, is to set the pipeline init parameter num_workers to 1. e.g. `predictions = self.artifacts.model(validated_texts, num_workers=1)`

@parano I have a question. Can you share schedule for next verision of BentoML?
