### ISSUE TITLE
imageio > 2.9.0 breaks ImageInput

### ISSUE THREAD

**Issue by gregd33** [bentoml/BentoML#2084]
**Describe the bug**

If using `imageio > 2.9.0` this breaks ImageInput

**To Reproduce**
Create a minimal service and install the latest `imageio`. e.g.

```
from bentoml import api, BentoService
from bentoml.adapters import ImageInput

class SimpleImage(BentoService):
    @api(input=ImageInput(), batch=False)
    def predict(self, image):
        return {'res' : image.shape}
```

**Expected behavior**

Get an error when trying to predict

**Screenshots/Logs**

```
[2021-12-02 23:16:04,584] ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/plugins/tifffile.py", line 362, in _can_read
    _tifffile.TiffFile(request.get_file(), **request.kwargs)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/plugins/_tifffile.py", line 1822, in __init__
    fh = FileHandle(arg, mode="rb", name=name, offset=offset, size=size)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/plugins/_tifffile.py", line 4951, in __init__
    self.open()
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/plugins/_tifffile.py", line 4997, in open
    self._dir, self._name = os.path.split(self._fh.name)
  File "/home/xxx/envs/p38/lib/python3.8/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/bentoml/server/api_server.py", line 393, in api_func
    resp = api.handle_request(req)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 295, in handle_request
    results = self.infer((inf_task,))
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 232, in infer
    user_args = self.input_adapter.extract_user_func_args(inf_tasks)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/bentoml/adapters/image_input.py", line 215, in extract_user_func_args
    img_array = imageio.imread(task.data, pilmode=self.pilmode)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/core/functions.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/core/imopen.py", line 233, in imopen
    plugin_instance = config.plugin_class(request, **kwargs)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/core/legacy_plugin_wrapper.py", line 62, in __init__
    if not self._format.can_read(request):
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/core/format.py", line 188, in can_read
    return self._can_read(request)
  File "/home/xxx/envs/p38/lib/python3.8/site-packages/imageio/plugins/tifffile.py", line 366, in _can_read
    except _tifffile.TiffFileError:  # pragma: no-cover
AttributeError: module 'imageio.plugins._tifffile' has no attribute 'TiffFileError'
```

**Environment:**
 - OS: Ubuntu
 - Python Version: 3.8
 - BentoML Version: 0.13.1

**Additional context**
It can be fixed by pinning `imageio==2.9.0`

I saw something about Pillow instead of imageio so maybe this isn't need but it is a big bug

**Comment by parano** [comment]
@gregd33 that's true we are not longer using imageio in BentoML 1.0, Pillow will be used to replace it in the Image IO.
