### ISSUE TITLE
aiohttp error: Response payload is not completed

### ISSUE THREAD

**Issue by tomaindow** [bentoml/BentoML#2159]
First of all, thank you so much for all the work on BentoML, it's a fantastic piece of kit.

**Describe the bug**
We've been running a model inference service using `bentoml serve-gunicorn path/to/model --timeout=10` that has been happily running and returning predictions for several weeks, but recently came across the following `aiohttp.client` error:

```
[2022-01-04 08:14:57,686] ERROR - Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.8/site-packages/bentoml/marshal/marshal.py", line 109, in request_dispatcher
    resp = await func(request)
  File "/home/appuser/.local/lib/python3.8/site-packages/bentoml/marshal/marshal.py", line 338, in request_dispatcher
    resp = await self.relay_handler(request)
  File "/home/appuser/.local/lib/python3.8/site-packages/bentoml/marshal/marshal.py", line 358, in relay_handler
    body = await resp.read()
  File "/home/appuser/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/home/appuser/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/home/appuser/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/home/appuser/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

After re-starting the service, everything appears to be fine but I can't quite get to the bottom of what happened. Does anyone have any ideas?

This may not be a bug per se, so apologies if posted in wrong place.

**Environment:**
 - OS: Debian 11 (Bullseye)
 - Python: 3.8.12
 - BentoML: 0.13.1
 - aiohttp: 3.8.1

Any help appreciated. Let me know what additional information if any would be useful for resolving this.

**Comment by parano** [comment]
Thank you for the feedback @tomaindow, that's indeed an important pain point for bentoml users. We plan to add more debugging information to help users understand the real-time batching decisions. This issue is now being tracked here: https://github.com/bentoml/BentoML/issues/1499 will close this one to avoid duplication
