### ISSUE TITLE
[bentoml 1.0.0a2] bentoml serve fails

### ISSUE THREAD

**Issue by alexdivet** [bentoml/BentoML#2200]
**Describe the bug**
I'm testing bentoml 1.0.0a2 following your [quickstart](https://docs.bentoml.org/en/latest/quickstart.html) but I can't serve the model due to an issue with **opentelemetry**

**To Reproduce**
Run `bentoml serve ./bento.py:svc --reload` in the quickstart

**Screenshots/Logs**
```
[15:07:02] INFO     Starting development BentoServer from "./bento.py:svc"                                                                                             
[15:07:03] INFO     Service imported from source: bentoml.Service(name="iris_classifier", import_str="bento:svc", working_dir="/Users/e056232/Projects/test-bento")    
[15:07:03] INFO     Will watch for changes in these directories: ['/Users/e056232/Projects/test-bento']                                                   config.py:342
           INFO     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)                                                                       config.py:564
           INFO     Started reloader process [2155] using statreload                                                                                   basereload.py:56
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/e056232/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/e056232/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/e056232/.pyenv/versions/3.8.12/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/e056232/.pyenv/versions/3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/uvicorn/server.py", line 74, in serve
    config.load()
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/uvicorn/importer.py", line 31, in import_from_string
    instance = getattr(instance, attr_str)
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/bentoml/_internal/service/service.py", line 156, in asgi_app
    return ServiceAppFactory(self)()
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/bentoml/_internal/server/service_app.py", line 323, in __call__
    app = super().__call__()
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/bentoml/_internal/server/base_app.py", line 62, in __call__
    middleware=self.middlewares,
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/bentoml/_internal/server/service_app.py", line 287, in middlewares
    import opentelemetry.instrumentation.asgi as otel_asgi  # type: ignore[import]
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 106, in <module>
    from opentelemetry.instrumentation.utils import http_status_to_status_code
  File "/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/opentelemetry/instrumentation/utils.py", line 21, in <module>
    from opentelemetry.context import _SUPPRESS_INSTRUMENTATION_KEY  # noqa: F401
ImportError: cannot import name '_SUPPRESS_INSTRUMENTATION_KEY' from 'opentelemetry.context' (/Users/e056232/.pyenv/versions/3.8.12/envs/bentoml-env/lib/python3.8/site-packages/opentelemetry/context/__init__.py)
```

**Environment:**
OS: MacOS 11.6
Python Version Python 3.8.12
BentoML Version BentoML-1.0.0a2

opentelemetry versions:
```
opentelemetry-api==1.10a0
opentelemetry-instrumentation==0.27b0
opentelemetry-instrumentation-asgi==0.27b0
opentelemetry-sdk==1.10a0
opentelemetry-semantic-conventions==0.27b0
opentelemetry-util-http==0.27b0
```

**Comment by parano** [comment]
Thank you for reporting the issue @alexdivet, this is an issue with changes from the preview release from opentelemetry, if you install the latest stable release of opentelemetry-api and opentelemetry-sdk, this issue should go away.

```
pip uninstall opentelemetry-api opentelemetry-sdk
pip install opentelemetry-api opentelemetry-sdk
```

cc @bojiang

**Comment by alexdivet** [comment]
thanks for the prompt answer @parano

I confirm it works with the stable release 👌🏻
