### ISSUE TITLE
The bentoml serve-gunicorn argument --timeout is not always respected

### ISSUE THREAD

**Issue by pietermarsman** [bentoml/BentoML#2240]
**Describe the bug**

Disclaimer: I don't fully understand all the inner workings of BentoML but I will try to explain as clearly as possible. 

I'm running into a timeout issue when my "model" (the bento in question is actually an orchestration component) is running for longer than 60 seconds. 

I'm testing this locally using the `bentoml serve-gunicorn` command. 

**To Reproduce**

Create slow bento:

```python
import time

import bentoml
from bentoml import BentoService
from bentoml.adapters import JsonOutput, ImageInput


class TimeoutIssue(BentoService):

    @bentoml.api(input=ImageInput(), output=JsonOutput())
    def predict(self, image):
        time.sleep(65)
        return {}


if __name__ == '__main__':
    bento = TimeoutIssue()
    bento.save()
```

Run the inference server with a long timeout:

```shell
poetry run bentoml serve-gunicorn TimeoutIssue:latest --timeout 540
```

Send an request to the API. 

Observe it crash.

**Expected behavior**

All of the internal workers of a bento server respect the timeout set on the command line. 

**Screenshots/Logs**

```
$ BENTOML_DEBUG=TRUE poetry run bentoml serve-gunicorn TimeoutIssue:latest --timeout 540
[2022-02-02 10:48:41,709] DEBUG - Configured logging with simple configuration, level=DEBUG, directory=/home/pieter/bentoml/logs, console_enabled=True, file_enabled=True
[2022-02-02 10:48:42,538] DEBUG - Creating local YataiService instance
[2022-02-02 10:48:42,773] DEBUG - Upgrading tables to the latest revision
[2022-02-02 10:48:42,794] DEBUG - Session acquired
[2022-02-02 10:48:42,795] DEBUG -       READ on TimeoutIssue_latest
[2022-02-02 10:48:42,805] INFO - Getting latest version TimeoutIssue:20220202104608_C6A498
[2022-02-02 10:48:42,813] DEBUG - Session released after 0.018273353576660156s
[2022-02-02 10:48:42,820] INFO - Starting BentoML proxy in production mode..
[2022-02-02 10:48:42,821] INFO - Starting BentoML API server in production mode..
[2022-02-02 10:48:42,917] DEBUG - Setting up prometheus_multiproc_dir: /home/pieter/bentoml/prometheus_multiproc_dir
[2022-02-02 10:48:42,918] INFO - Running micro batch service on :5000
[2022-02-02 10:48:42,920] DEBUG - Setting up prometheus_multiproc_dir: /home/pieter/bentoml/prometheus_multiproc_dir
[2022-02-02 10:48:42 +0100] [3228569] [INFO] Starting gunicorn 20.1.0
[2022-02-02 10:48:42 +0100] [3228569] [INFO] Listening at: http://0.0.0.0:35777 (3228569)
[2022-02-02 10:48:42 +0100] [3228569] [INFO] Using worker: sync
[2022-02-02 10:48:42 +0100] [3228570] [INFO] Booting worker with pid: 3228570
[2022-02-02 10:48:42,995] WARNING - Python 3.9.7 found in current environment is not officially supported by BentoML. The docker base image used is'bentoml/model-server:0.13.1' which will use conda to install Python 3.9.7 in the build process. Supported Python versions are: f3.6, 3.7, 3.8
[2022-02-02 10:48:43 +0100] [3228493] [INFO] Starting gunicorn 20.1.0
[2022-02-02 10:48:43 +0100] [3228493] [INFO] Listening at: http://0.0.0.0:5000 (3228493)
[2022-02-02 10:48:43 +0100] [3228493] [INFO] Using worker: aiohttp.worker.GunicornWebWorker
[2022-02-02 10:48:43 +0100] [3228571] [INFO] Booting worker with pid: 3228571
[2022-02-02 10:48:43,131] INFO - Your system nofile limit is 1048576, which means each instance of microbatch service is able to hold this number of connections at same time. You can increase the number of file descriptors for the server process, or launch more microbatch instances to accept more concurrent connection.
[2022-02-02 10:48:47,983] DEBUG - Tracing is disabled. Initializing no-op tracer
[2022-02-02 10:48:47,992] DEBUG - Tracing is disabled. Initializing no-op tracer
[2022-02-02 10:49:48,430] ERROR - Traceback (most recent call last):
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/bentoml/marshal/marshal.py", line 109, in request_dispatcher
    resp = await func(request)
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/bentoml/marshal/marshal.py", line 338, in request_dispatcher
    resp = await self.relay_handler(request)
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/bentoml/marshal/marshal.py", line 355, in relay_handler
    async with client.request(
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/home/pieter/projects/orbisk/ai-inference/.venv/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

[2022-02-02 10:49:53,056] INFO - {'service_name': 'TimeoutIssue', 'service_version': '20220202104608_C6A498', 'api': 'predict', 'task': {'data': '{}', 'task_id': '96762c03-d591-4faf-8cfd-febed6c62ca1', 'http_headers': (('Host', '0.0.0.0:5000'), ('User-Agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0'), ('Accept', '*/*'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Referer', 'http://0.0.0.0:5000/'), ('Content-Type', 'application/json'), ('Origin', 'http://0.0.0.0:5000'), ('Content-Length', '2'), ('Dnt', '1'), ('Connection', 'keep-alive'))}, 'result': {'data': '{}', 'http_status': 200, 'http_headers': (('Content-Type', 'application/json'),)}, 'request_id': '96762c03-d591-4faf-8cfd-febed6c62ca1'}

```

**Environment:**

- Ubuntu
- Python 3.8
- BentoML 0.13.1

**Additional context**

I spend some time on figuring out what is happening and think the issue arises at the creation of a `MarshalService`. 

https://github.com/bentoml/BentoML/blob/0.13-line/bentoml/server/marshal_server.py#L108

It is not passing the timeout variable and it is therefore using the default timeout from the bento config.

**Comment by aarnphm** [comment]
can you try `bentoml` 1.0 via `pip install bentoml --pre`? @bojiang this would be fixed in 1.0 right?

**Comment by pietermarsman** [comment]
Since 0.13.1 is LTS is expect the bug also to be fixed in major version 0.

**Comment by aarnphm** [comment]
yes
