### ISSUE TITLE
Exception raised when building Tensorflow project

### ISSUE THREAD

**Issue by sauyon** [bentoml/BentoML#2330]
When building a Tensorflow project with Python 3.9, BentoML will raise an error while attempting to cleanup the `TempFS` used to construct the Bento.

**To Reproduce**
1. Install BentoML with python 3.9
2. Run `bentoml build` in the [BentoML Tensorflow gallery project](https://github.com/bentoml/gallery/tree/main/tensorflow2)

**Trace**
```
Exception ignored in: <function FS.__del__ at 0x7fee0ecd01f0>
Traceback (most recent call last):
  File "/home/sauyon/devel/bentoml/env-3.9/lib/python3.9/site-packages/fs/base.py", line 116, in __del__
  File "/home/sauyon/devel/bentoml/env-3.9/lib/python3.9/site-packages/fs/tempfs.py", line 122, in close
TypeError: super() argument 1 must be type, not None
```

**Environment:**
 - Python 3.9
 - BentoML main

**Comment by sauyon** [comment]
Hm, I think this one is fixed in the RC.
