### ISSUE TITLE
Getting an "TypeError: __init__() got an unexpected keyword argument 'omit_repeated_times'" error

### ISSUE THREAD

**Issue by mgmalana** [bentoml/BentoML#2377]
I have been using BentoML with no problem. However, when I install a library named 'norfair', bentoml CLI raises "TypeError: __init__() got an unexpected keyword argument 'omit_repeated_times'". 

It seems like a namespace problem with the logging module and rich logging module. I'm not sure if this is a problem of bentoml or the other library, so please let me know what you think! Thank you for your work on bentoml, it's a great tool!

**To Reproduce**
To reproduce:
1. Install bentoml by entering "pip install bentoml --pre"
2. Install norfair library by entering "pip install norfair"
3. Try using bentoml CLI

**Expected behavior**
Bentoml CLI not causing an error

**Screenshots/Logs**
```
Traceback (most recent call last):                                                                             
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure                                          
Traceback (most recent call last):                                                                  
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure                                          
    handler = self.configure_handler(handlers[name])                                                           
  File "/usr/lib/python3.8/logging/config.py", line 744, in configure_handler                                  
    result = factory(**kwargs)                                                                                 
TypeError: __init__() got an unexpected keyword argument 'omit_repeated_times'                                 
                                                                                                               
The above exception was the direct cause of the following exception:                                           
                                                                                                               
Traceback (most recent call last):                                                                             
  File "/workspace/21346/bentoml-test/.venv/bin/bentoml", line 5, in <module>                                  
    from bentoml._internal.cli import cli                                                                      
  File "/workspace/21346/bentoml-test/.venv/lib/python3.8/site-packages/bentoml/__init__.py", line 11, in <modu
le>                                                                                                            
    configure_logging()                                                                                        
  File "/workspace/21346/bentoml-test/.venv/lib/python3.8/site-packages/bentoml/_internal/log.py", line 97, in 
configure_logging                                                                                              
    logging.config.dictConfig(LOGGING_CONFIG)                                                                  
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig                                         
    dictConfigClass(config).configure()                                                                        
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure                                          
    raise ValueError('Unable to configure handler '                                                            
ValueError: Unable to configure handler 'internal'
```

**Environment:**
 - OS: Ubuntu 20.04.3 LTS
 - Python Version: 3.8
 - BentoML Version BentoML-1.0.0a6

**Comment by aarnphm** [comment]
can you run `pip show rich`? This is due to the library `norfair` fixes rich versioning at 9.x, whereas we didn't lock the specific version of rich. I believe that rich 9.x will break bentoml, so I will submit a PR to lock set rich version requirements

**Comment by bojiang** [comment]
I believe it is caused by the dependency `rich`.
norfair is requiring rich=9.13.0
https://github.com/tryolabs/norfair/blob/master/poetry.lock#L531

**Comment by bojiang** [comment]
https://github.com/tryolabs/norfair/blob/master/poetry.lock#L531

**Comment by aarnphm** [comment]
#2378

**Comment by aarnphm** [comment]
thanks for raising the issue.
