### ISSUE TITLE
Unable to package sentry-sdk with bentoML serve

### ISSUE THREAD

**Issue by rtindru** [bentoml/BentoML#2425]
**Describe the bug**
I am running into a `ModuleNotFoundError` when I try to serve a bentoML service with `sentry_sdk` installed

```python
%%writefile sentry_service.py

import bentoml

from bentoml.adapters import JsonInput

import sentry_sdk
import logging
from sentry_sdk.integrations.logging import LoggingIntegration

# All of this is already happening by default!
sentry_logging = LoggingIntegration(
    level=logging.INFO,        # Capture info and above as breadcrumbs
    event_level=logging.ERROR  # Send errors as events
)
sentry_sdk.init(
    dsn="https://651a85506d1d4be3876a224d8a92eb2c@o1140265.ingest.sentry.io/6197278",
    integrations=[sentry_logging]
)


@bentoml.env(infer_pip_packages=True)
class SentryService(bentoml.BentoService):

    @bentoml.api(input=JsonInput())
    @bentoml.env(pip_packages=["scikit-learn", "pandas", "sentry-sdk==1.5.4"])
    def predict(self, parsed_json):
        try:
            texts = parsed_json
            return {}
        except:
            sentry_sdk.capture_exception()
```

**Serve the model**
```python
from sentry_service import SentryService

bento_service = SentryService()

saved_path = bento_service.save()

!bentoml serve SentryService:latest
```

**Expected behavior**
I expect BentoML to pack and serve the model service with sentry enabled

**Screenshots/Logs**
```
[2022-04-25 02:42:57,069] WARNING - unknown package dependency for module: sentry_sdk
[2022-04-25 02:42:57,181] INFO - BentoService bundle 'SentryService:20220425024256_5CD55F' saved to: /root/bentoml/repository/SentryService/20220425024256_5CD55F
[2022-04-25 02:42:57,845] INFO - Getting latest version SentryService:20220425024256_5CD55F
[2022-04-25 02:42:57,850] INFO - Starting BentoML API proxy in development mode..
[2022-04-25 02:42:57,851] INFO - Starting BentoML API server in development mode..
[2022-04-25 02:42:57,887] DEBUG - Configured logging with simple configuration, level=DEBUG, directory=/root/bentoml/logs, console_enabled=True, file_enabled=True
[2022-04-25 02:42:57,887] DEBUG - Setting debug mode: ON for current session
[2022-04-25 02:42:57,934] INFO - Your system nofile limit is 1048576, which means each instance of microbatch service is able to hold this number of connections at same time. You can increase the number of file descriptors for the server process, or launch more microbatch instances to accept more concurrent connection.
======== Running on http://0.0.0.0:5000/ ========
(Press CTRL+C to quit)
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/bentoml/server/__init__.py", line 76, in _start_dev_server
    bento_service = load_from_dir(saved_bundle_path)
  File "/usr/local/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 110, in wrapper
    return func(bundle_path, *args)
  File "/usr/local/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 271, in load_from_dir
    svc_cls = load_bento_service_class(bundle_path)
  File "/usr/local/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 110, in wrapper
    return func(bundle_path, *args)
  File "/usr/local/lib/python3.9/site-packages/bentoml/saved_bundle/loader.py", line 209, in load_bento_service_class
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/bentoml/repository/SentryService/20220425024256_5CD55F/SentryService/sentry_service.py", line 19, in <module>
    sentry_sdk.init(
  File "/root/bentoml/repository/SentryService/20220425024256_5CD55F/SentryService/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/root/bentoml/repository/SentryService/20220425024256_5CD55F/SentryService/sentry_sdk/client.py", line 86, in __init__
    self._init_impl()
  File "/root/bentoml/repository/SentryService/20220425024256_5CD55F/SentryService/sentry_sdk/client.py", line 120, in _init_impl
    self.integrations = setup_integrations(
  File "/root/bentoml/repository/SentryService/20220425024256_5CD55F/SentryService/sentry_sdk/integrations/__init__.py", line 107, in setup_integrations
    for integration_cls in iter_default_integrations(
  File "/root/bentoml/repository/SentryService/20220425024256_5CD55F/SentryService/sentry_sdk/integrations/__init__.py", line 41, in iter_default_integrations
    yield getattr(import_module(module), cls)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sentry_sdk.integrations.stdlib'
```

**Environment:**
 - OS: Ubuntu
 - Python 3.9
 - BentoML Version 0.13.1

**Additional context**
I am using the sentry docs here https://docs.sentry.io/platforms/python/usage/

**Comment by rtindru** [comment]
I found the issue. I am running jupyter inside a docker container. Initially, I was installing `sentry-sdk` on the jupyter runtime using `!pip install sentry-sdk`. For some reason, bentoML was unable to locate the package when it is installed this way.
I fixed the issue by installing `sentry-sdk` into the base docker container.
