### ISSUE TITLE
BentoML not working with save model command and even build command on cli

### ISSUE THREAD

**Issue by mashirali** [bentoml/BentoML#2601]
**Describe the bug**

**To Reproduce**
 Traceback (most recent call last):
  File "C:\Users\mashi\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mashi\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mashi\anaconda3\Scripts\bentoml.exe\__main__.py", line 4, in <module>
    from bentoml._internal.cli import cli
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\__init__.py", line 17, in <module>
    from .bentos import get
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\bentos.py", line 19, in <module>
    from ._internal.bento import Bento
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\__init__.py", line 1, in <module>
    from .bento import Bento
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\bento.py", line 33, in <module>
    from .build_config import CondaOptions
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\build_config.py", line 15, in <module>
    from .gen import generate_dockerfile
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\gen.py", line 11, in <module>
    from jinja2 import Environment
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\mashi\anaconda3\lib\site-packages\markupsafe\__init__.py)

(base) C:\Users\mashi>bentoml build
Traceback (most recent call last):
  File "C:\Users\mashi\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mashi\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mashi\anaconda3\Scripts\bentoml.exe\__main__.py", line 4, in <module>
    from bentoml._internal.cli import cli
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\__init__.py", line 17, in <module>
    from .bentos import get
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\bentos.py", line 19, in <module>
    from ._internal.bento import Bento
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\__init__.py", line 1, in <module>
    from .bento import Bento
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\bento.py", line 33, in <module>
    from .build_config import CondaOptions
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\build_config.py", line 15, in <module>
    from .gen import generate_dockerfile
  File "C:\Users\mashi\anaconda3\lib\site-packages\bentoml\_internal\bento\gen.py", line 11, in <module>
    from jinja2 import Environment
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\mashi\anaconda3\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\mashi\anaconda3\lib\site-packages\markupsafe\__init__.py)

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. windows 11]
 - Python Version [e.g. Python 3.9]
 - BentoML Version [e.g. BentoML-1.0.0rc1]

**Additional context**

**Comment by aarnphm** [comment]
@mashirali do you have `aws-sam-cli` installed? can you send the output of `pip show markupsafe`?

**Comment by aarnphm** [comment]
Hi @mashirali can you try again with bentoml `rc2`? `pip install bentoml==1.0.0rc2`
