### ISSUE TITLE
YOLOv5 Torch Hub Model No module named models

### ISSUE THREAD

**Issue by darkking-park** [bentoml/BentoML#2602]
**Describe the bug**
Getting this error when using a custom YOLOv5 model I trained that I loaded and saved using torch hub.
* same issue
https://github.com/bentoml/BentoML/issues/2386

* @[timliubentoml](https://github.com/timliubentoml) answer
https://github.com/bentoml/BentoML/issues/2386#issuecomment-1086283333
https://github.com/bentoml/BentoML/issues/2386#issuecomment-1090754597

## I proceeded according to Timliubentoml's answer.
* bentoml==1.0.0a7
###  save.py
```python
import bentoml
import torch

model = torch.hub.load("ultralytics/yolov5", 'custom', path='./best_my_model_yolo5l.pt', autoshape=False, force_reload=True)
tag = bentoml.pytorch.save("yolov5", model)
```
### service.py
```python
from typing import List
  
import bentoml
import numpy as np
import torch
from bentoml.io import JSON

runner = bentoml.pytorch.load_runner("yolov5:latest")
service = bentoml.Service("yolov5", runners=[runner])

@service.api(input=JSON(), output=JSON())
def predict(input_dict):
    # Retrieve data from dictionary
    filename = input_dict['filename']
    img = input_dict['image_content']
    input_img = torch.from_numpy(np.asarray(img[0]))
    predictions = runner.run_batch(input_img)
    return predictions
```

### run python save.py
```console
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip
INFO:yolov5:YOLOv5  2022-6-16 Python-3.7.5 torch-1.11.0+cu102 CUDA:0 (Tesla P40, 24452MiB)

YOLOv5  2022-6-16 Python-3.7.5 torch-1.11.0+cu102 CUDA:0 (Tesla P40, 24452MiB)

INFO:yolov5:Fusing layers... 
Fusing layers... 
INFO:yolov5:Model summary: 367 layers, 46119048 parameters, 0 gradients
Model summary: 367 layers, 46119048 parameters, 0 gradients
06/16/22 12:29:44 INFO     [cli] Successfully saved Model(tag="yolov5:aa6vvkhnochwqasc", path="/root/bentoml/models/yolov5/aa6vvkhnochwqasc/")  
```
### run bentoml serve  service.py:service
```console
<bentoml._internal.frameworks.pytorch._PyTorchRunner object at 0x7fc989f72a90>
06/16/22 12:31:35 INFO     [cli] Service imported from source: bentoml.Service(name="yolov5", import_str="service_yolov5:service", working_dir="/home")       
06/16/22 12:31:35 INFO     [cli] Starting development BentoServer from "service_yolov5.py:service" running on http://127.0.0.1:3000 (Press CTRL+C to quit)    
<bentoml._internal.frameworks.pytorch._PyTorchRunner object at 0x7fbc65834c10>
06/16/22 12:31:37 INFO     [dev_api_server] Service imported from source: bentoml.Service(name="yolov5", import_str="service_yolov5:service",   working_dir="/home")                                                                                                                               
06/16/22 12:31:37 INFO     [dev_api_server] Started server process [2209]                                                                                                     
06/16/22 12:31:37 INFO     [dev_api_server] Waiting for application startup.                                                                                                  
06/16/22 12:31:37 INFO     [dev_api_server] Application startup complete.     
```
## BUT  An error occurs when calling
```console
06/16/22 11:47:18 ERROR    [dev_api_server] Exception on /predict [POST] (trace=335788210924982409590970105266588217373,span=17571784936932541778,sampled=0)                  
                           ╭─────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────╮
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/server/service_app.py:325 in api_func                                             │
                           │                                                                                                                                                 │
                           │   322 │   │   │   │   │   if isinstance(api.input, Multipart):                                                                                  │
                           │   323 │   │   │   │   │   │   output: t.Any = await run_in_threadpool(api.func, **input_data)                                                   │
                           │   324 │   │   │   │   │   else:                                                                                                                 │
                           │ ❱ 325 │   │   │   │   │   │   output: t.Any = await run_in_threadpool(api.func, input_data)                                                     │
                           │   326 │   │   │   │   response = await api.output.to_http_response(output)                                                                      │
                           │   327 │   │   │   except BentoMLException as e:                                                                                                 │
                           │   328 │   │   │   │   log_exception(request, sys.exc_info())                                                                                    │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/starlette/concurrency.py:45 in run_in_threadpool                                                    │
                           │                                                                                                                                                 │
                           │   42 │   elif kwargs:  # pragma: no cover                                                                                                       │
                           │   43 │   │   # run_sync doesn't accept 'kwargs', so bind them in here                                                                           │
                           │   44 │   │   func = functools.partial(func, **kwargs)                                                                                           │
                           │ ❱ 45 │   return await anyio.to_thread.run_sync(func, *args)                                                                                     │
                           │   46                                                                                                                                            │
                           │   47                                                                                                                                            │
                           │   48 class _StopIteration(Exception):                                                                                                           │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/anyio/to_thread.py:29 in run_sync                                                                   │
                           │                                                                                                                                                 │
                           │   26 │                                                                                                                                          │
                           │   27 │   """                                                                                                                                    │
                           │   28 │   return await get_asynclib().run_sync_in_worker_thread(func, *args,                                                                     │
                           │      cancellable=cancellable,                                                                                                                   │
                           │ ❱ 29 │   │   │   │   │   │   │   │   │   │   │   │   │   │     limiter=limiter)                                                                 │
                           │   30                                                                                                                                            │
                           │   31                                                                                                                                            │
                           │   32 async def run_sync_in_worker_thread(                                                                                                       │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py:818 in run_sync_in_worker_thread                                        │
                           │                                                                                                                                                 │
                           │    815 │   │   │   context = copy_context()                                                                                                     │
                           │    816 │   │   │   context.run(sniffio.current_async_library_cvar.set, None)                                                                    │
                           │    817 │   │   │   worker.queue.put_nowait((context, func, args, future))                                                                       │
                           │ ❱  818 │   │   │   return await future                                                                                                          │
                           │    819                                                                                                                                          │
                           │    820                                                                                                                                          │
                           │    821 def run_sync_from_thread(func: Callable[..., T_Retval], *args: object,                                                                   │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py:754 in run                                                              │
                           │                                                                                                                                                 │
                           │    751 │   │   │   │   │   result = None                                                                                                        │
                           │    752 │   │   │   │   │   exception: Optional[BaseException] = None                                                                            │
                           │    753 │   │   │   │   │   try:                                                                                                                 │
                           │ ❱  754 │   │   │   │   │   │   result = context.run(func, *args)                                                                                │
                           │    755 │   │   │   │   │   except BaseException as exc:                                                                                         │
                           │    756 │   │   │   │   │   │   exception = exc                                                                                                  │
                           │    757                                                                                                                                          │
                           │                                                                                                                                                 │
                           │ /home/service_yolov5.py:29 in predict                                                                                           │
                           │                                                                                                                                                 │
                           │   26 │   #img = transform(img)                                                                                                                  │
                           │   27 │   # Forward prop                                                                                                                         │
                           │   28 │   input_img = torch.from_numpy(np.asarray(img[0]))                                                                                       │
                           │ ❱ 29 │   predictions = runner.run_batch(input_img)                                                                                              │
                           │   30 │   #predictions = runner.run_batch(img.unsqueeze(0))                                                                                      │
                           │   31 │   # Get boxes                                                                                                                            │
                           │   32 │   #outputs = non_max_suppression(predictions)                                                                                            │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/runner.py:169 in run_batch                                                 │
                           │                                                                                                                                                 │
                           │   166 │                                                                                                                                         │
                           │   167 │   @final                                                                                                                                │
                           │   168 │   def run_batch(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                                                                          │
                           │ ❱ 169 │   │   return self._impl.run_batch(*args, **kwargs)                                                                                      │
                           │   170                                                                                                                                           │
                           │   171                                                                                                                                           │
                           │   172 class Runner(BaseRunner, ABC):                                                                                                            │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/local.py:64 in run_batch                                                   │
                           │                                                                                                                                                 │
                           │   61 │                                                                                                                                          │
                           │   62 │   def run_batch(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                                                                           │
                           │   63 │   │   if self._state is RunnerState.INIT:                                                                                                │
                           │ ❱ 64 │   │   │   self.setup()                                                                                                                   │
                           │   65 │   │   if isinstance(self._runner, Runner):                                                                                               │
                           │   66 │   │   │   return self._runner._run_batch(*args, **kwargs)  # type:                                                                       │
                           │      ignore[reportPrivateUsage]                                                                                                                 │
                           │   67 │   │   if isinstance(self._runner, SimpleRunner):                                                                                         │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/local.py:16 in setup                                                       │
                           │                                                                                                                                                 │
                           │   13 │   │   if self._state != RunnerState.INIT:                                                                                                │
                           │   14 │   │   │   return                                                                                                                         │
                           │   15 │   │   self._state = RunnerState.SETTING_UP                                                                                               │
                           │ ❱ 16 │   │   self._runner._setup()  # type: ignore[reportPrivateUsage]                                                                          │
                           │   17 │   │   self._state = RunnerState.READY                                                                                                    │
                           │   18 │                                                                                                                                          │
                           │   19 │   def shutdown(self) -> None:                                                                                                            │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/common/pytorch.py:111 in _setup                                        │
                           │                                                                                                                                                 │
                           │   108 │   │   │   self._no_grad_context.enter_context(torch.inference_mode())                                                                   │
                           │   109 │   │                                                                                                                                     │
                           │   110 │   │   self._configure()                                                                                                                 │
                           │ ❱ 111 │   │   model = self._load_model()                                                                                                        │
                           │   112 │   │   model.eval()                                                                                                                      │
                           │   113 │   │   if self._on_gpu:                                                                                                                  │
                           │   114 │   │   │   self._model = parallel.DataParallel(model)                                                                                    │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/pytorch.py:171 in _load_model                                          │
                           │                                                                                                                                                 │
                           │   168                                                                                                                                           │
                           │   169 class _PyTorchRunner(BasePyTorchRunner):                                                                                                  │
                           │   170 │   def _load_model(self):                                                                                                                │
                           │ ❱ 171 │   │   return load(self._tag, device_id=self._device_id, model_store=self.model_store)                                                   │
                           │   172                                                                                                                                           │
                           │   173                                                                                                                                           │
                           │   174 def load_runner(                                                                                                                          │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/simple_di/__init__.py:124 in _                                                                      │
                           │                                                                                                                                                 │
                           │   121 │   │   bind = sig.bind_partial(*filtered_args, **filtered_kwargs)                                                                        │
                           │   122 │   │   bind.apply_defaults()                                                                                                             │
                           │   123 │   │                                                                                                                                     │
                           │ ❱ 124 │   │   return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))                                                              │
                           │   125 │                                                                                                                                         │
                           │   126 │   setattr(_, "_is_injected", True)                                                                                                      │
                           │   127 │   return cast(WrappedCallable, _)                                                                                                       │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/pytorch.py:73 in load                                                  │
                           │                                                                                                                                                 │
                           │    70 │   │   │   model: "torch.nn.Module" = cloudpickle.load(file).to(device_id)                                                               │
                           │    71 │   elif model_format == "torch.save:v1":                                                                                                 │
                           │    72 │   │   with Path(weight_file).open("rb") as file:                                                                                        │
                           │ ❱  73 │   │   │   model: "torch.nn.Module" = torch.load(file, map_location=device_id)                                                           │
                           │    74 │   else:                                                                                                                                 │
                           │    75 │   │   raise BentoMLException(f"Unknown model format {model_format}")                                                                    │
                           │    76                                                                                                                                           │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/torch/serialization.py:712 in load                                                                  │
                           │                                                                                                                                                 │
                           │    709 │   │   │   │   │   │   │   │     " silence this warning)", UserWarning)                                                                 │
                           │    710 │   │   │   │   │   opened_file.seek(orig_position)                                                                                      │
                           │    711 │   │   │   │   │   return torch.jit.load(opened_file)                                                                                   │
                           │ ❱  712 │   │   │   │   return _load(opened_zipfile, map_location, pickle_module,                                                                │
                           │        **pickle_load_args)                                                                                                                      │
                           │    713 │   │   return _legacy_load(opened_file, map_location, pickle_module,                                                                    │
                           │        **pickle_load_args)                                                                                                                      │
                           │    714                                                                                                                                          │
                           │    715                                                                                                                                          │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/torch/serialization.py:1046 in _load                                                                │
                           │                                                                                                                                                 │
                           │   1043 │                                                                                                                                        │
                           │   1044 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                                                                          │
                           │   1045 │   unpickler.persistent_load = persistent_load                                                                                          │
                           │ ❱ 1046 │   result = unpickler.load()                                                                                                            │
                           │   1047 │                                                                                                                                        │
                           │   1048 │   torch._utils._validate_loaded_sparse_tensors()                                                                                       │
                           │   1049                                                                                                                                          │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/torch/serialization.py:1039 in find_class                                                           │
                           │                                                                                                                                                 │
                           │   1036 │   │   │   │   except KeyError:                                                                                                         │
                           │   1037 │   │   │   │   │   pass                                                                                                                 │
                           │   1038 │   │   │   mod_name = load_module_mapping.get(mod_name, mod_name)                                                                       │
                           │ ❱ 1039 │   │   │   return super().find_class(mod_name, name)                                                                                    │
                           │   1040 │                                                                                                                                        │
                           │   1041 │   # Load the data (which may in turn use `persistent_load` to load tensors)                                                            │
                           │   1042 │   data_file = io.BytesIO(zip_file.get_record(pickle_file))                                                                             │
                           ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                           ModuleNotFoundError: No module named 'models'   
```
### After "ModuleNotFoundError: No module named 'models' " , an error occurs when calling again as follows.
```console
06/16/22 11:47:18 INFO     [dev_api_server] 127.0.0.1:52900 (scheme=http,method=POST,path=/predict,type=application/json,length=2807777)                                      
                           (status=500,type=application/json,length=110) 0.860ms (trace=335788210924982409590970105266588217373,span=17571784936932541778,sampled=0)          
06/16/22 11:47:19 ERROR    [dev_api_server] Exception on /predict [POST] (trace=225897735478898420879166462161187224573,span=15880002128422342633,sampled=0)                  
                           ╭─────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────╮
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/server/service_app.py:325 in api_func                                             │
                           │                                                                                                                                                 │
                           │   322 │   │   │   │   │   if isinstance(api.input, Multipart):                                                                                  │
                           │   323 │   │   │   │   │   │   output: t.Any = await run_in_threadpool(api.func, **input_data)                                                   │
                           │   324 │   │   │   │   │   else:                                                                                                                 │
                           │ ❱ 325 │   │   │   │   │   │   output: t.Any = await run_in_threadpool(api.func, input_data)                                                     │
                           │   326 │   │   │   │   response = await api.output.to_http_response(output)                                                                      │
                           │   327 │   │   │   except BentoMLException as e:                                                                                                 │
                           │   328 │   │   │   │   log_exception(request, sys.exc_info())                                                                                    │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/starlette/concurrency.py:45 in run_in_threadpool                                                    │
                           │                                                                                                                                                 │
                           │   42 │   elif kwargs:  # pragma: no cover                                                                                                       │
                           │   43 │   │   # run_sync doesn't accept 'kwargs', so bind them in here                                                                           │
                           │   44 │   │   func = functools.partial(func, **kwargs)                                                                                           │
                           │ ❱ 45 │   return await anyio.to_thread.run_sync(func, *args)                                                                                     │
                           │   46                                                                                                                                            │
                           │   47                                                                                                                                            │
                           │   48 class _StopIteration(Exception):                                                                                                           │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/anyio/to_thread.py:29 in run_sync                                                                   │
                           │                                                                                                                                                 │
                           │   26 │                                                                                                                                          │
                           │   27 │   """                                                                                                                                    │
                           │   28 │   return await get_asynclib().run_sync_in_worker_thread(func, *args,                                                                     │
                           │      cancellable=cancellable,                                                                                                                   │
                           │ ❱ 29 │   │   │   │   │   │   │   │   │   │   │   │   │   │     limiter=limiter)                                                                 │
                           │   30                                                                                                                                            │
                           │   31                                                                                                                                            │
                           │   32 async def run_sync_in_worker_thread(                                                                                                       │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py:818 in run_sync_in_worker_thread                                        │
                           │                                                                                                                                                 │
                           │    815 │   │   │   context = copy_context()                                                                                                     │
                           │    816 │   │   │   context.run(sniffio.current_async_library_cvar.set, None)                                                                    │
                           │    817 │   │   │   worker.queue.put_nowait((context, func, args, future))                                                                       │
                           │ ❱  818 │   │   │   return await future                                                                                                          │
                           │    819                                                                                                                                          │
                           │    820                                                                                                                                          │
                           │    821 def run_sync_from_thread(func: Callable[..., T_Retval], *args: object,                                                                   │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py:754 in run                                                              │
                           │                                                                                                                                                 │
                           │    751 │   │   │   │   │   result = None                                                                                                        │
                           │    752 │   │   │   │   │   exception: Optional[BaseException] = None                                                                            │
                           │    753 │   │   │   │   │   try:                                                                                                                 │
                           │ ❱  754 │   │   │   │   │   │   result = context.run(func, *args)                                                                                │
                           │    755 │   │   │   │   │   except BaseException as exc:                                                                                         │
                           │    756 │   │   │   │   │   │   exception = exc                                                                                                  │
                           │    757                                                                                                                                          │
                           │                                                                                                                                                 │
                           │ /home/service_yolov5.py:29 in predict                                                                                           │
                           │                                                                                                                                                 │
                           │   26 │   #img = transform(img)                                                                                                                  │
                           │   27 │   # Forward prop                                                                                                                         │
                           │   28 │   input_img = torch.from_numpy(np.asarray(img[0]))                                                                                       │
                           │ ❱ 29 │   predictions = runner.run_batch(input_img)                                                                                              │
                           │   30 │   #predictions = runner.run_batch(img.unsqueeze(0))                                                                                      │
                           │   31 │   # Get boxes                                                                                                                            │
                           │   32 │   #outputs = non_max_suppression(predictions)                                                                                            │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/runner.py:169 in run_batch                                                 │
                           │                                                                                                                                                 │
                           │   166 │                                                                                                                                         │
                           │   167 │   @final                                                                                                                                │
                           │   168 │   def run_batch(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                                                                          │
                           │ ❱ 169 │   │   return self._impl.run_batch(*args, **kwargs)                                                                                      │
                           │   170                                                                                                                                           │
                           │   171                                                                                                                                           │
                           │   172 class Runner(BaseRunner, ABC):                                                                                                            │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/local.py:66 in run_batch                                                   │
                           │                                                                                                                                                 │
                           │   63 │   │   if self._state is RunnerState.INIT:                                                                                                │
                           │   64 │   │   │   self.setup()                                                                                                                   │
                           │   65 │   │   if isinstance(self._runner, Runner):                                                                                               │
                           │ ❱ 66 │   │   │   return self._runner._run_batch(*args, **kwargs)  # type:                                                                       │
                           │      ignore[reportPrivateUsage]                                                                                                                 │
                           │   67 │   │   if isinstance(self._runner, SimpleRunner):                                                                                         │
                           │   68 │   │   │   raise RuntimeError("shall not call run_batch on a" " simple runner")                                                           │
                           │   69                                                                                                                                            │
                           │                                                                                                                                                 │
                           │ /opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/common/pytorch.py:142 in _run_batch                                    │
                           │                                                                                                                                                 │
                           │   139 │   │   │   return item                                                                                                                   │
                           │   140 │   │                                                                                                                                     │
                           │   141 │   │   params = params.map(_mapping)                                                                                                     │
                           │ ❱ 142 │   │   res = self._predict_fn(*params.args, **kwargs)                                                                                    │
                           │   143 │   │   return res                                                                                                                        │
                           │   144                                                                                                                                           │
                           │   145                                                                                                                                           │
                           ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                           AttributeError: '_PyTorchRunner' object has no attribute '_predict_fn'      
```

### Please check it quickly and let me know if it can be processed in version 0.13.1 as it is currently running in version 1.0.0a7

**Comment by aarnphm** [comment]
Hi @darkking-park, can you try with the new rc1 releases. we recently deprecate `load_runner`, as well as `save` and `load` api in turns for `save_model` and `load_model`.

**Comment by darkking-park** [comment]
hi @aarnphm 
I tried with rc1.
The server is not even popping up due to an error.
### run bentoml serve service.py:service
```console
06/21/22 00:52:12 ERROR    [dev_api_server] Application startup failed. Exiting.                                                                                                                                                                                
06/21/22 00:52:14 WARNING  [dev_api_server] The "bentoml.pytorch.load_runner" method is being deprecated. Use `bentoml.pytorch.get("yolov5:latest").to_runner()` instead                                                                                        
06/21/22 00:52:14 INFO     [dev_api_server] Default runner method set to `__call__`, it can be accessed both via `runner.run` and `runner.__call__.async_run`                                                                                                   
Runner(runnable_class=<class 'bentoml._internal.frameworks.common.pytorch.partial_class.<locals>.NewClass'>, runnable_init_params={}, name='yolov5', models=[Model(tag="yolov5:e2ig47hq7s5dwasc")], resource_config=Resource(cpu=None, nvidia_gpu=None, custom_resources={}), runner_methods=[RunnerMethod(runner=..., name='__call__', config=RunnableMethodConfig(batchable=False, batch_dim=(0, 0), input_spec=None, output_spec=None), max_batch_size=100, max_latency_ms=10000)], scheduling_strategy=<class 'bentoml._internal.runner.strategy.DefaultStrategy'>, _runner_handle=<bentoml._internal.runner.runner_handle.DummyRunnerHandle object at 0x7fc006b15c50>)
06/21/22 00:52:14 INFO     [dev_api_server] Service imported from source: bentoml.Service(name="yolov5", import_str="service_yolov5:service", working_dir="/home")                                                                              
06/21/22 00:52:14 INFO     [dev_api_server] Started server process [444]                                                                                                                                                                                        
06/21/22 00:52:14 INFO     [dev_api_server] Waiting for application startup.                                                                                                                                                                                    
06/21/22 00:52:14 ERROR    [dev_api_server] Traceback (most recent call last):                                                                                                                                                                                  
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/starlette/routing.py", line 624, in lifespan                                                                                                                                     
                               async with self.lifespan_context(app):                                                                                                                                                                                           
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/starlette/routing.py", line 521, in __aenter__                                                                                                                                   
                               await self._router.startup()                                                                                                                                                                                                     
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/starlette/routing.py", line 603, in startup                                                                                                                                      
                               handler()                                                                                                                                                                                                                        
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/runner.py", line 204, in init_local                                                                                                                     
                               self._init_local()                                                                                                                                                                                                               
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/runner.py", line 195, in _init_local                                                                                                                    
                               self._init(LocalRunnerRef)                                                                                                                                                                                                       
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/runner.py", line 189, in _init                                                                                                                          
                               runner_handle = handle_class(self)                                                                                                                                                                                               
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/runner/runner_handle/local.py", line 23, in __init__                                                                                                           
                               self._runnable = runner.runnable_class()                                                                                                                                                                                         
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/common/pytorch.py", line 50, in __init__                                                                                                            
                               self, *inner_args, **inner_kwargs                                                                                                                                                                                                
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/common/pytorch.py", line 74, in __init__                                                                                                            
                               self.model: ModelType = loader(bento_model, device_id=self.device_id)                                                                                                                                                            
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/pytorch.py", line 77, in load_model                                                                                                                 
                               model: "torch.nn.Module" = torch.load(file, map_location=device_id)                                                                                                                                                              
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/torch/serialization.py", line 712, in load                                                                                                                                       
                               return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)                                                                                                                                                    
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/torch/serialization.py", line 1046, in _load                                                                                                                                     
                               result = unpickler.load()                                                                                                                                                                                                        
                             File "/opt/venv/tf2.3/lib/python3.7/site-packages/torch/serialization.py", line 1039, in find_class                                                                                                                                
                               return super().find_class(mod_name, name)                                                                                                                                                                                        
                           ModuleNotFoundError: No module named 'models'                                                                                                                                                                                        
                                                                                                                                                                                                                                                                
Exception ignored in: <function PytorchModelRunnable.__del__ at 0x7fc006bfbf80>
Traceback (most recent call last):
  File "/opt/venv/tf2.3/lib/python3.7/site-packages/bentoml/_internal/frameworks/common/pytorch.py", line 83, in __del__
    self._no_grad_context.close()
AttributeError: 'NewClass' object has no attribute '_no_grad_context'
```

**Comment by aarnphm** [comment]
can you send the service code here?

**Comment by aarnphm** [comment]
torch hub doesn't work reliably since different hub has different implementation. The module `models` is from ultralytics/yolov5, and bentoml doesn't have context of this.

**Comment by darkking-park** [comment]
@aarnphm 
my service code
```python
from typing import List
  
import bentoml
import numpy as np
import torch
from bentoml.io import JSON

punner = bentoml.pytorch.get("yolov5:latest").to_runner()
service = bentoml.Service("yolov5", runners=[runner])


@service.api(input=JSON(), output=JSON())
def predict(input_dict):
    filename = input_dict['filename']
    img = input_dict['image_content']
    input_img = torch.from_numpy(np.asarray(img[0]))
    predictions = runner.run_batch(input_img)
    return predictions
```

I would appreciate it if you could share the service source for Bentoml with the torch model(yolov5.pt).

**Comment by aarnphm** [comment]
You can do this. At your service directory:
```bash
git clone --bare git@github.com:ultralytics/yolov5.git && git --git-dir=./yolov5.git --work-tree=. checkout a2a1ed201d150343a4f9912d644be2b210206984 -- data models utils LICENSE README.md detect.py export.py hubconf.py train.py val.py requirements.txt

rm -rf yolov5.git
```
This will add current data, utils, and models directory to the current directory. You can then add those required files/folder to your bento. This is the workaround for now.

We will provide support for torchhub module after 1.0 release

**Comment by aarnphm** [comment]
https://github.com/bentoml/BentoML/issues/2602#issuecomment-1165259006 should be able to solve your current issue. Development will be tracked at #2704

**Comment by aarnphm** [comment]
You can try out https://github.com/bentoml/gallery/tree/main/custom_runner/torch_hub_yolov5

**Comment by darkking-park** [comment]
@aarnphm 
Thank you from the bottom of my heart.
I'll try using the link you gave me.
