### ISSUE TITLE
bentoml serve with transformer pipeline fails to set GPU device

### ISSUE THREAD

**Issue by thechaos16** [bentoml/BentoML#2620]
**Describe the bug**

`bentoml serve` with transformers pipeline fails running with GPU on the assigning device step.

The available GPU device collected by env variable (https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/transformers.py#L265-L273) is string, and it is not compatible with transformer's code (https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/base.py#L762-L765) because string is not comparable with integer.

**To Reproduce**

1. Save any transformer pipeline with bentoml
2. run `bentoml build` with gpu (exactly same as https://docs.bentoml.org/en/latest/guides/gpu.html#docker-images-options)
3. `bentoml containerize` and deploy the image
4. See error while starting `bentoml serve --production`

**Expected behavior**

Correctly assigns visible GPU and run inference server

**Screenshots/Logs**

Error logs
```
Traceback (most recent call last):             
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 645, in lifespan            
 async with self.lifespan_context(app):           
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 540, in __aenter__             
 await self._router.startup()                     
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 624, in startup                
 handler()                                        
File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runner.py", line 204, in init_local                                           
 self._init_local()                               
File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runner.py", line 195, in _init_local                                          
 self._init(LocalRunnerRef)                       
File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runner.py", line 189, in _init    
 runner_handle = handle_class(self)               
File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runner_handle/local.py", line 23, in __init__                                          
 self._runnable = runner.runnable_class()         
File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/frameworks/transformers.py", line 293, in __init__                                             
 self.pipeline = load_model(bento_model, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/frameworks/transformers.py", line 158, in load_model                                           
 return transformers.pipeline(task=pipeline_task, model=bento_model.path, **pipeline_kwargs)  # type:  ignore                                               
File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/__init__.py", line 684, in pipeline 
 return pipeline_class(model=model, framework=framework, task=task, **kwargs)            
File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/text_classification.py", line 68, in __init__                                             
 super().__init__(**kwargs)                       
File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 765, in __init__     
 self.device = device if framework == "tf" else torch.device("cpu" if device < 0 else f"cuda:{device}")                                 
TypeError: '<' not supported between instances of  'str' and 'int'
```

`NVIDIA_VISIBLE_DEVICES` is originally some string like "GPU-some-hashed-string" and it fails. So I manually put `-e NVIDIA_VISIBLE_DEVICES=0` on `docker run`, but it fails as well (with the same error)

**Environment:**
 - OS: Ubuntu 20.04.4 (Docker container)
 - Python Version: 3.8.10
 - BentoML Version: 1.0.0.rc1

**Additional context**

**Comment by ssheng** [comment]
@thechaos16 fix has been merged in main. Will include in the next release.
