### ISSUE TITLE
bug: ONNX framework guide error in documentation

### ISSUE THREAD

**Issue by l-con** [bentoml/BentoML#2780]
### Describe the bug

I stumbled upon a small mistake in the BentoML ONNX framework guide documentation which caused an error to be displayed that didn't allow me to run a live service locally.

### To reproduce

 I saved my ONNX model with BentoML, created my `service.py` and `bentofile.yaml` files as suggested by the documentation. 

However when I ran `bentoml serve service:svc --reload` to run a live service I would get the following error:

```
 + Exception Group Traceback (most recent call last):
  |   File "<string>", line 1, in <module>
  |   File "/usr/local/lib/python3.9/site-packages/circus/plugins/__init__.py", line 260, in main
  |     plugin = factory(args.endpoint, args.pubsub,
  |   File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/utils/circus/watchfilesplugin.py", line 66, in __init__
  |     self.create_spec()
  |   File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/utils/circus/watchfilesplugin.py", line 88, in create_spec
  |     build_config = BentoBuildConfig.from_yaml(f).with_defaults()
  |   File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/bento/build_config.py", line 715, in from_yaml
  |     return bentoml_cattr.structure(yaml_content, cls)
  |   File "/usr/local/lib/python3.9/site-packages/cattrs/converters.py", line 281, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "<cattrs generated structure bentoml._internal.bento.build_config.BentoBuildConfig>", line 54, in structure_BentoBuildConfig
  |     if errors: raise __c_cve('While structuring BentoBuildConfig', errors, __cl)
  | cattrs.errors.ClassValidationError: While structuring BentoBuildConfig (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "<cattrs generated structure bentoml._internal.bento.build_config.BentoBuildConfig>", line 41, in structure_BentoBuildConfig
    |     res['python'] = __c_structure_python(o['python'], __c_type_python)
    |   File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/bento/build_config.py", line 596, in _python_options_structure_hook
    |     return PythonOptions(**d)
    | TypeError: bentoml._internal.bento.build_config.PythonOptions() argument after ** must be a mapping, not list
    +------------------------------------
```

The mistake in the documentation can be found in the `Building a Service for ONNX` section, where it is suggested `when constructing a bentofile.yaml`, that there way to include ONNX as a dependency with Python is:

```
python:
- onnx
- onnxruntime
```

However the correct way to include ONNX with Python is:

```
python:
   packages:
   - onnx
   - onnxruntime
```

Once I modified my bentofile.yaml that way, I was able to run a live service correctly.

### Environment

python=3.7.3
bentoml=1.0

**Comment by larme** [comment]
@l-con thanks for reporting this bug! Seems that our documentation has several similar mistakes. I will update them all
