### ISSUE TITLE
bug: TypeError: cannot pickle 'ctranslate2.translator.Translator' object

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/BentoML#3061]
### Describe the bug

I have used the CTranslate2 inference within bentoML (https://github.com/OpenNMT/CTranslate2) with custom runner.

This library implements a custom runtime that applies many performance optimization techniques such as weights quantization, layers fusion, batch reordering, etc., to [accelerate and reduce the memory usage](https://github.com/OpenNMT/CTranslate2#benchmarks) of Transformer models on CPU and GPU.

But, when trying to save the model with `cloudpickle`, it results in the following error: 

> converting 'CT2_default_opus_mt_fr_en' to lowercase: 'ct2_default_opus_mt_fr_en'
> Traceback (most recent call last):
>   File "/home/matthieu/Code/Python/CTranslate2/MarianMT.py", line 125, in <module>
>     saved_model = bentoml.picklable_model.save_model(
>   File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/bentoml/_internal/frameworks/picklable.py", line 145, in save_model
>     cloudpickle.dump(model, f)
>   File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
>     CloudPickler(
>   File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
>     return Pickler.dump(self, obj)
> TypeError: cannot pickle 'ctranslate2.translator.Translator' object

### To reproduce

```
import ctranslate2
import transformers

model_path = "/home/matthieu/Deployment/CTranslate2/opus-mt-fr-en/default"

translator = ctranslate2.Translator(model_path, device="cuda")
tokenizer = transformers.AutoTokenizer.from_pretrained(model_id)

saved_model = bentoml.picklable_model.save_model(
    "CT2_default_opus-mt-fr-en",    # model name in the local model store 
    translator,    # model instance being saved
    signatures={    # model signatures for runner inference
        "__call__": {
            "batchable": True,
            }
    }
)

print(f"Model saved: {saved_model}")
```

### Expected behavior

Model should be pickled into bentoml models repository.

### Environment

bentoml: 1.0.6
python: 3.8.13
ubuntu: 18.04.LTS

**Comment by aarnphm** [comment]
`external_modules` can fix this issue here.

```python
save_model = bentoml.pickable_model.save_model(..., external_modules=[ctranslate2])
```

**Comment by Matthieu-Tinycoaching** [comment]
Hi @aarnphm,

I followed your suggestion above:
```
saved_model = bentoml.picklable_model.save_model(
    "CT2_default_opus-mt-fr-en",    # model name in the local model store 
    translator,    # model instance being saved
    custom_objects={    # save additional user-defined python objects
        "tokenizer": tokenizer,
    },
    signatures={    # model signatures for runner inference
        "__call__": {
            "batchable": True,
            "batch_dim": 0,
            }
    },
    external_modules=[ctranslate2],
)
```
But got the same error as previously:
```
converting 'CT2_default_opus-mt-fr-en' to lowercase: 'ct2_default_opus-mt-fr-en'
Traceback (most recent call last):
  File "/home/matthieu/Code/Python/CTranslate2/MarianMT.py", line 81, in <module>
    saved_model = bentoml.picklable_model.save_model(
  File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/bentoml/_internal/frameworks/picklable.py", line 145, in save_model
    cloudpickle.dump(model, f)
  File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
    CloudPickler(
  File "/home/matthieu/anaconda3/envs/ctranslate2_py3.8/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'ctranslate2.translator.Translator' object
```

**Comment by kvasilopoulos** [comment]
Any update here?
