### ISSUE TITLE
bug: UnicodeEncodeError is occured

### ISSUE THREAD

**Issue by smartdolphin** [bentoml/BentoML#3118]
### Describe the bug

When utf-16 characters are sended to api, an UnicodeEncodeError error is occured with running encoding utf-8.

```
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc4f' in position 13: surrogates not allowed
```

### To reproduce

1. text = "\udc4f"
2. send text to predict API
3. see error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bentoml/server/api_server.py", line 394, in api_func
    response = resp.to_flask_response()
  File "/usr/local/lib/python3.9/site-packages/bentoml/types.py", line 288, in to_flask_response
    return flask.Response(
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 206, in __init__
    self.set_data(response)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 332, in set_data
    value = value.encode(self.charset)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc4f' in position 13: surrogates not allowed
```

### Environment

bentoml: 0.13-LTS
python: 3.9
platform: linux

**Comment by frostming** [comment]
This issue is pre-1.0 and is no longer considered valid.
