### ISSUE TITLE
feature: Allow for New relic integration

### ISSUE THREAD

**Issue by kkkarthik6** [bentoml/BentoML#3463]
### Feature request

We are using bentoML for our model serving. We found that it is a great library. However when integrating with new relic we are facing issues. 

### Motivation

We have been using bentoML for our work. It is a great repository thank you for building this. However, when we try to integrate bentoML with new relic monitoring we are getting the following error. We tried mounting a fastapi app/ custom middleware but seems like these efforts are not fruitful. Please help us to integrate newrelic with bentoML

**Debug mode from bentoML:**
```
 /usr/local/lib/python3.8/site-packages/uvicorn/lifespan/on.py:97: RuntimeWarning: coroutine 'middleware_wrapper' was never awaited
self.logger.error(msg, exc_info=exc)
Object allocated at (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/asgiref/compatibility.py", lineno 34
   instance = application(scope)
```

**Complete error Message**
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/newrelic/api/asgi_application.py", line 387, in nr_async_asgi
    return await coro
  File "/usr/local/lib/python3.9/site-packages/newrelic/common/async_proxy.py", line 148, in __next__
    return self.send(None)
  File "/usr/local/lib/python3.9/site-packages/newrelic/common/async_proxy.py", line 120, in send
    return self.__wrapped__.send(value)
  File "/usr/local/lib/python3.9/site-packages/newrelic/api/asgi_application.py", line 70, in __call__
    return await self.app(scope, receive, self.send_inject_browser_agent)
  File "/usr/local/lib/python3.9/site-packages/newrelic/api/asgi_application.py", line 330, in nr_async_asgi
    return await wrapped(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "<string>", line 5, in wrapper
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/framework_starlette.py", line 108, in middleware_wrapper
    return await FunctionTraceWrapper(wrapped, name=name)(*args, **kwargs)
  File "<string>", line 5, in wrapper
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 581, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/usr/local/lib/python3.9/site-packages/asgiref/compatibility.py", line 35, in new_application
    return await instance(receive, send)
TypeError: 'coroutine' object is not callable
/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py:416: RuntimeWarning: coroutine 'middleware_wrapper' was never awaited
  self.transport.close()
Object allocated at (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/compatibility.py", lineno 34
    instance = application(scope)
```

**Comment by ssheng** [comment]
@kkkarthik6 thanks for sharing the use case. Are you using the `@asgi_application` [decorator](https://docs.newrelic.com/docs/apm/agents/python-agent/python-agent-api/asgiapplication-python-agent-api/) to integrate New Relic? Upon a quick Google search, it seems like New Relic also offers a [Python agent](https://docs.newrelic.com/whats-new/2020/10/monitor-asgi-apps-using-python-agent/) for integrating with ASGI applications, like Uvicorn which BentoML was built on top of. Have you evaluated if that works for your use case?

**Comment by kkkarthik6** [comment]
Hi @ssheng , Thanks for the reply. We have the following setup and also tried mounting fastAPI as our asgi middleware. Seems like it always fails to boot with the above warning. 

`import newrelic.agent

newrelic.agent.initialize('/app/newrelic.ini')
import numpy as np
import bentoml
from bentoml.io import NumpyNdarray
import time
import tracemalloc
tracemalloc.start()
from bentoml import Service
async def sleep():
    time.sleep(1)
class ACVService(Service):

    @Service.asgi_app.setter
    def asgi_app(self):
        from bentoml._internal.server.http_app import HTTPAppFactory
        return HTTPAppFactory(self)(enabale_metrics=False)
svc = ACVService("data-bentoml-monitoring")
asgi_bento = svc.asgi_app
@newrelic.agent.asgi_application()
@svc.api(input=NumpyNdarray(), output=NumpyNdarray())
async def classify(input_series: np.ndarray) -> np.ndarray:
   await sleep()
   return input_series`

Start the app using this command
`BENTOML_DEBUG=TRUE uvicorn src.service:asgi_bento --port 5000 --host 0.0.0.0 --reload`

Error log. 

` Traceback (most recent call last):
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
data-bento-monitoring-retail-1  |     result = await app(  # type: ignore[func-returns-value]
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
data-bento-monitoring-retail-1  |     return await self.app(scope, receive, send)
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/api/asgi_application.py", line 363, in nr_async_asgi
data-bento-monitoring-retail-1  |     return await coro
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/common/async_proxy.py", line 148, in __next__
data-bento-monitoring-retail-1  |     return self.send(None)
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/common/async_proxy.py", line 120, in send
data-bento-monitoring-retail-1  |     return self.__wrapped__.send(value)
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/api/asgi_application.py", line 363, in nr_async_asgi
data-bento-monitoring-retail-1  |     return await coro
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/common/async_proxy.py", line 148, in __next__
data-bento-monitoring-retail-1  |     return self.send(None)
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/common/async_proxy.py", line 120, in send
data-bento-monitoring-retail-1  |     return self.__wrapped__.send(value)
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
data-bento-monitoring-retail-1  |     await self.middleware_stack(scope, receive, send)
data-bento-monitoring-retail-1  |   File "<string>", line 5, in wrapper
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
data-bento-monitoring-retail-1  |     raise exc
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
data-bento-monitoring-retail-1  |     await self.app(scope, receive, _send)
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/newrelic/hooks/framework_starlette.py", line 112, in middleware_wrapper
data-bento-monitoring-retail-1  |     return await FunctionTraceWrapper(wrapped, name=name)(*args, **kwargs)
data-bento-monitoring-retail-1  |   File "<string>", line 5, in wrapper
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/server/http/instruments.py", line 111, in __call__
data-bento-monitoring-retail-1  |     self._setup()
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
data-bento-monitoring-retail-1  |     return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/server/http/instruments.py", line 51, in _setup
data-bento-monitoring-retail-1  |     self.legacy_metrics_request_duration = metrics_client.Histogram(
data-bento-monitoring-retail-1  |   File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/server/metrics/prometheus.py", line 151, in Histogram
data-bento-monitoring-retail-1  |     return partial(self.prometheus_client.Histogram, registry=self.registry)
   File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/server/metrics/prometheus.py", line 59, in prometheus_client
     assert os.path.isdir(self.multiproc_dir)
`

**Comment by phitoduck** [comment]
There's an ongoing NewRelic support thread [here](https://discuss.newrelic.com/t/python-cannot-initialize-new-relic-agent-for-bentoml/192417/6), though as of right now, there isn't much there.

**Comment by ssheng** [comment]
Moving some of the conversation we had with @phitoduck here. Hopefully they can be helpful to @kkkarthik6.

Thanks for the insightful post, @phitoduck.  It seems like you are integrating with newrelic through the [Python Agent](https://docs.newrelic.com/docs/apm/agents/python-agent/installation/python-agent-admin-script-advanced-usage/).  Haven’t read a lot into the implementation, it seems like the instrumentation is automatically injected into the ASGI application if the application was started with `newrelic-admin run-program uvicorn`.

Treating BentoML as a simple ASGI application will not work out-of-the-box. BentoML’s runner architecture spawns multiple processes to optimize system resource utilization. Instead of a single uvicorn process, BentoML consists of multiple ASGI processes.

I will need to look into New Relic further to investigate a better integration. Since BentoML is fully compliant to OpenTelemetry and Prometheus standards, I’m hopeful that New Relic has proper supports for those standards.

[New Relic supports OpenTelemetry Protocol](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-introduction/) for exporting trace data. In BentoML, you can [customize the OTLP exporter](https://docs.bentoml.org/en/latest/guides/tracing.html) in the Tracing configuration with New Relic’s endpoint.

New Relic supports exporting Prometheus metrics through their [Prometheus OpenMetrics integration for Docker](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/).

**Comment by phitoduck** [comment]
I opened a ticket with the NewRelic support team. Here's an email I just got from them:

> Hi,
> 
> It looks like that our devs have analyzed the issue and as per their recommendation, we don't support the way BentoML internally creates multiple asgi apps and suggest to use [OTEL](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-introduction/) or [prometheus open metrics](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/) to report trace data.
> 
> However, I can definitely see the advantage of supporting BentoML. I'll be submitting a feature request on your behalf for this capability. At the moment, I don't have a timeline for this feature, but submitting this request will certainly help with its prioritization. We take requests like this very seriously and use them to prioritize what we implement next.
Since we track feature requests internally, I'll mark this ticket to be closed.
> 
> We appreciate you taking the time to bring this to our attention, and hope that you will continue to do so in the future. If you have any further questions or comments about this, please let us know by replying to this ticket and we'll be happy to continue the conversation.
> 
> Best,
Raji Durai
Technical Support Engineer
New Relic, Inc | Portland

**Comment by mihow** [comment]
Hi @phitoduck, I see you got a response from NewRelic and they suggested using OpenTelemetry to report metrics and you created an example in this repo https://github.com/phitoduck/bentoml-opentelemetry-newrelic. Does that work for you, or was it an experiment? I definitely need to monitor our BentoML services with NewRelic! Thank you for investigating this.
