### ISSUE TITLE
bug: client failed to initialization due to lack of signature

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3549]
### Describe the bug

Currently, if users define the following API behaviour:

```python
@svc.api(input=bentoml.io.Text(), output=bentoml.io.JSON())
async def list_model(_:str) -> list[str]:
    return await triton_runner.get_model_repository_index()
```

Client initialization with `from_url` will failed:

```prolog
BentoML does not support loading JSON encoders from URLs; output will be a normal dictionary.
Traceback (most recent call last):
  File "/home/ubuntu/workspace/bentoml/examples/triton_runner/serve_bento.py", line 46, in <module>
    client = bentoml.client.Client.from_url(
  File "/home/ubuntu/workspace/bentoml/src/bentoml/client.py", line 151, in from_url
    api = InferenceAPI(
  File "/home/ubuntu/workspace/bentoml/src/bentoml/_internal/service/inference_api.py", line 57, in __init__
    raise ValueError("Expected API function to take parameters.")
ValueError: Expected API function to take parameters.
```

The above behaviour would still works on OpenAPI.

### Environment

on main

**Comment by RobbieFernandez** [comment]
I am also encountering this issue, no matter what input/output descriptors I use.
Seems like this commit is what causes it: https://github.com/bentoml/BentoML/commit/b0bce42e1e4d7d411d1403d5307de4f9b61fcea5. The error is encountered when trying to inspect the lambda

**Comment by aarnphm** [comment]
Yes. I have a PR up that address this regression 😄 #3583
