### ISSUE TITLE
bug: 'Functional' is not iterable

### ISSUE THREAD

**Issue by alvinmaottd** [bentoml/BentoML#3759]
### Describe the bug

I'm trying to save a model using:
`bentoml.tensorflow.save_model(model, "some_name")`
Model is of type:
`<class 'keras.engine.functional.Functional'>`

However, upon calling `save_model` I get the error mentioned in the title:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/frameworks/tensorflow_v2.py", line 200, in save_model
    with bentoml.models.create(
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/bentoml/models.py", line 245, in create
    res = Model.create(
  File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/models/model.py", line 181, in create
    tag = Tag.from_str(name)
  File "/usr/local/lib/python3.9/site-packages/bentoml/_internal/tag.py", line 100, in from_str
    if ":" not in tag_str:
TypeError: argument of type 'Functional' is not iterable
```

Any suggestions on trouble shooting this?

### To reproduce

For context, I'm also referencing the [tensorflow frameworks page here](https://docs.bentoml.org/en/latest/frameworks/tensorflow.html) and using the example for `Functional keras.Model`. In this example if you paste in the script as is i.e.
```
x = keras.layers.Input((5,), dtype=tf.float64, name="x")
y = keras.layers.Dense(
    6,
    name="out",
    kernel_initializer=keras.initializers.Ones(),
)(x)
model = keras.Model(inputs=x, outputs=y)
opt = keras.optimizers.Adam(0.002, 0.5)
model.compile(optimizer=opt, loss="binary_crossentropy", metrics=["accuracy"])
model.fit(train_x, train_y, epochs=10) # this step doesn't work cause train.* are undefined

bentoml.tensorflow.save(
    model,
    "my_keras_model",
    signatures={"__call__": {"batchable": True, "batch_dim": 0}}
)
```
I confirmed that the sample `model` here is the same type as the production model I'm trying to save.

### Expected behavior

save_model doesn't throw an exception and proceeds with saving the model.

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.0.18
`python`: 3.9.15
`platform`: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
`uid_gid`: 0:0
<details><summary><code>pip_packages</code></summary>

<br>

```
absl-py==1.4.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
appdirs==1.4.4
asgiref==3.6.0
astroid==2.15.3
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
backoff==2.2.1
bentoml==1.0.18
black==23.1.0
boto3==1.26.91
botocore==1.29.114
build==0.10.0
cachetools==5.3.0
cattrs==22.2.0
certifi==2022.12.7
charset-normalizer==3.1.0
circus==0.18.0
click==8.1.3
click-option-group==0.5.5
cloudpickle==2.2.1
contextlib2==21.6.0
coverage==7.2.1
deepmerge==1.1.0
Deprecated==1.2.13
dill==0.3.6
exceptiongroup==1.1.1
fastapi==0.93.0
flatbuffers==23.3.3
frozenlist==1.3.3
fs==2.4.16
gast==0.4.0
google-auth==2.17.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.59.0
grpcio==1.53.0
h11==0.14.0
h5py==3.8.0
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.3
idna==3.4
importlib-metadata==6.4.1
iniconfig==2.0.0
isort==5.12.0
Jinja2==3.1.2
jmespath==1.0.1
keras==2.11.0
lazy-object-proxy==1.9.0
libclang==16.0.0
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mccabe==0.7.0
mdurl==0.1.2
multidict==6.0.4
mypy==1.1.1
mypy-extensions==1.0.0
numpy==1.24.2
oauthlib==3.2.2
opentelemetry-api==1.14.0
opentelemetry-exporter-otlp-proto-http==1.14.0
opentelemetry-instrumentation==0.35b0
opentelemetry-instrumentation-aiohttp-client==0.35b0
opentelemetry-instrumentation-asgi==0.35b0
opentelemetry-proto==1.14.0
opentelemetry-sdk==1.14.0
opentelemetry-semantic-conventions==0.35b0
opentelemetry-util-http==0.35b0
opt-einsum==3.3.0
packaging==23.1
pathspec==0.11.1
pip-requirements-parser==32.0.1
pip-tools==6.13.0
platformdirs==3.2.0
pluggy==1.0.0
prometheus-client==0.16.0
prometheus-fastapi-instrumentator==6.0.0
protobuf==3.19.6
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.10.7
Pygments==2.15.0
pylint==2.17.0
pynvml==11.5.0
pyparsing==3.0.9
pyproject_hooks==1.0.0
pytest==7.2.2
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
PyYAML==6.0
pyzmq==25.0.2
requests==2.28.2
requests-oauthlib==1.3.1
rfc3986==1.5.0
rich==13.3.4
rsa==4.9
s3transfer==0.6.0
schema==0.7.5
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.25.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-cpu==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.32.0
termcolor==2.2.0
tomli==2.0.1
tomlkit==0.11.7
tornado==6.2
typing_extensions==4.5.0
# Editable install with no version control (ufmodels==0.0.0)
-e /lib
urllib3==1.26.15
uvicorn==0.21.0
uvloop==0.17.0
watchfiles==0.19.0
websockets==11.0.1
Werkzeug==2.2.3
wrapt==1.15.0
yarl==1.8.2
zipp==3.15.0
```

**Comment by parano** [comment]
Hi @alvinmaottd, the first parameter should be the model name in BentoML model store, the second parameter is for the model instance. Could you try the following?

```python
bentoml.tensorflow.save(
    "my_keras_model",
    model,
    signatures={"__call__": {"batchable": True, "batch_dim": 0}}
)
```

**Comment by alvinmaottd** [comment]
ah yes - that was it 🤦 

might be worth updating the reference page to have the parameters in the correct order here:
https://docs.bentoml.org/en/latest/frameworks/tensorflow.html

thanks a lot - looking forward to experimenting more with BentoML 😁
