### ISSUE TITLE
bug: runner/service doesn't include mlflow `code_path` modules?

### ISSUE THREAD

**Issue by nadworny** [bentoml/BentoML#3769]
### Describe the bug

My mlflow model has additional dependencies (i.e. util classes) which are included through the `code_path` parameter (see https://mlflow.org/docs/latest/python_api/mlflow.pyfunc.html#mlflow.pyfunc.log_model). The included code doesn't seem to be available when the inference takes place leading to the following error:
```
[api_server:7] Exception on /predict [POST] (trace=ccfa8725f497d488a34b399b6ff94103,span=0e83cdfcd3b8955d,sampled=0)
Traceback (most recent call last):                                                                                             
  File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/server/http_app.py", line 324, in api_func                    
    output = await api.func(input_data)                                                                                        
  File "/home/bentoml/bento/src/my_model/Model.py", line 15, in predict                                     
    return await runner.predict.async_run(input_arr)                                                                           
  File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/runner/runner.py", line 55, in async_run                      
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)                                            
  File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/runner/runner_handle/remote.py", line 279, in async_run_method
    return AutoContainer.from_payload(payload)                                                                                 
  File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/runner/container.py", line 628, in from_payload               
    return container_cls.from_payload(payload)                                                                                 
  File "/usr/local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _                                          
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))                                                       
  File "/usr/local/lib/python3.8/site-packages/bentoml/_internal/runner/container.py", line 500, in from_payload               
    return pickle.loads(payload.data)                                                                                          
ModuleNotFoundError: No module named 'my_python_project'
```

The module `my_python_project` is available in the model itself and I verified that inside the running container:
```bash
$ ls models/my_model/1/mlflow_model/code/
my_python_project
```

Prediction works when I'm loading the model using mlflow.pyfunc flavor.

### To reproduce

1. Build a mlflow model using pyfunc flavor (i.e. https://medium.com/@pennyqxr/how-save-and-load-fasttext-model-in-mlflow-format-37e4d6017bf0) which uses external dependencies during prediction. Those dependencies are logged within the model using `code_path` parameter
2. Load the model into bentoml and run predict

### Expected behavior

Classes/modules included through the `code_path` are resolved properly in the same way as the mlflow.pyfunc would work.

### Environment

bentoml, version 1.0.18
Python 3.8.16
m1 / k8s

**Comment by aarnphm** [comment]
You need to pass `my_python_project` into `custom_modules` when saving the model with `bentoml.mlflow`.

**Comment by frostming** [comment]
yes, you have to make sure all objects are importable by your service, we don't allow to manipulate `sys.path` at runtime. Closing it now
