### ISSUE TITLE
bug: export_bento with s3 throws invalid bucket name error

### ISSUE THREAD

**Issue by NicoG94** [bentoml/BentoML#3777]
### Describe the bug

When using the export bento function with s3 the bucket gets removed from the `dest_uri` [here](https://github.com/bentoml/BentoML/blob/main/src/bentoml/_internal/exportable.py#L311) which causes the function to fail. 

```python
import bentoml

bentoml.export_bento("test_bento:latest", "s3://test_bucket")  
```

I think [this line](https://github.com/bentoml/BentoML/blob/main/src/bentoml/_internal/exportable.py#L272) causes the issue as the bucket name stays in `subpath` and `resource` will be an empty string.

```
Traceback (most recent call last):
  File "/mnt/c/Users/some_path/export_import_test.py", line 44, in <module>
    bentoml.export_bento(bento, s3bucket)
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/some-repo-COtPtbak-py3.9/lib/python3.9/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/bentoml/bentos.py", line 224, in export_bento
    return bento.export(
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/bentoml/_internal/exportable.py", line 327, in export
    destfs = fs.open_fs(dest_uri)
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/fs/opener/registry.py", line 220, in open_fs
    _fs, _path = self.open(
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/fs/opener/registry.py", line 177, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/fs_s3fs/opener.py", line 22, in open_fs
    raise OpenerError("invalid bucket name in '{}'".format(fs_url))
fs.opener.errors.OpenerError: invalid bucket name in 's3://?'
```

### Environment

bentoml: 1.0.16 (or 1.0.18)
python: 3.9.5
OS: wsl

**Comment by aarnphm** [comment]
Did you install bentoml with `pip install 'bentoml[aws]'`?

**Comment by NicoG94** [comment]
yes I did

**Comment by ssheng** [comment]
Thanks for reporting the bug. We will work on a fix. Meanwhile, you can workaround the bug by appending a `/` at the end.

```
import bentoml

bentoml.export_bento("test_bento:latest", "s3://test_bucket/")  
```

**Comment by NicoG94** [comment]
thanks that helped

**Comment by NicoG94** [comment]
what is the best way to specify it when having password + user?

the following leads to the same error:

```
bentoml.export_bento("test_bento:latest, "bentoml-models-prompt-engineering", protocol="s3",
                         user="test_user", passwd="test_pw", subpath="folder")
```

**Comment by NicoG94** [comment]
@ssheng @aarnphm can one of you help me here? For me this is unfortunately not closed yet...
I can also create a new issue regarding how to use it when having passwort and name if that is better
