### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by NicoG94** [bentoml/BentoML#3789]
### Describe the bug

When using the export bento function with s3 and user and password the bucket gets removed from the dest_uri [here](https://github.com/bentoml/BentoML/blob/main/src/bentoml/_internal/exportable.py#L311) which causes the function to fail.

```python
import bentoml

bentoml.export_bento('test_service:latest',
                     'test_bucket', # same happens with 'test_bucket/'
                     protocol='s3', subpath='bentos',
                     user='test_user', passwd='test_pw')
```

I think [this line](https://github.com/bentoml/BentoML/blob/main/src/bentoml/_internal/exportable.py#L272) causes the issue as the bucket name stays in subpath and resource will be an empty string.

```
Traceback (most recent call last):
  File "/mnt/c/Users/some_path/export_import_test.py", line 44, in <module>
    bentoml.export_bento(bento, s3bucket)
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/some-repo-COtPtbak-py3.9/lib/python3.9/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/bentoml/bentos.py", line 224, in export_bento
    return bento.export(
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/bentoml/_internal/exportable.py", line 327, in export
    destfs = fs.open_fs(dest_uri)
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/fs/opener/registry.py", line 220, in open_fs
    _fs, _path = self.open(
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/fs/opener/registry.py", line 177, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
  File "/home/nico_linux/.cache/pypoetry/virtualenvs/ some-repo -COtPtbak-py3.9/lib/python3.9/site-packages/fs_s3fs/opener.py", line 22, in open_fs
    raise OpenerError("invalid bucket name in '{}'".format(fs_url))
fs.opener.errors.OpenerError: invalid bucket name in 's3://test_user:test_pw@?'

```

when attaching "s3://" in front of the bucket name:

```python
import bentoml

bentoml.export_bento('test_service:latest',
                     's3://test_bucket',
                     protocol='s3', subpath='bentos',
                     user='test_user', passwd='test_pw')
```

I get the following error:

```
Traceback (most recent call last):
  File "/mnt/c/Program Files/JetBrains/PyCharm 2022.3.3/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/nico_linux/miniforge3/envs/parrot-main/lib/python3.9/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/nico_linux/miniforge3/envs/parrot-main/lib/python3.9/site-packages/bentoml/bentos.py", line 224, in export_bento
    return bento.export(
  File "/home/nico_linux/miniforge3/envs/parrot-main/lib/python3.9/site-packages/bentoml/_internal/exportable.py", line 203, in export
    raise ValueError(
ValueError: An FS URL was passed as the output path; all additional information should be passed as part of the URL.

```

### Environment

bentoml[aws]: 1.0.16 (or 1.0.18)
python: 3.9.5
OS: wsl

**Comment by NicoG94** [comment]
also when using bentoml.export() locally without a username and password it works fine and takes around 2 min. But when using it in our gitlab ci pipeline it takes 50min. Would you have a guess why that is?

**Comment by sauyon** [comment]
For now you should probably pass a full FS URL:

```python
bentoml.export_bento('test_service:latest', 's3://test_user:test_pw@test_bucket/bentos')
```

But I think this is a bug with our non-OS path handling, I'll put up a quick PR.
