### ISSUE TITLE
bugs: Exception during shutdown

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#3813]
Issuing SIGTERM (Ctrl+C) to a runner server causes the following exception to be raised. 

```
023-05-01T23:27:09-0700 [ERROR] [cli] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x10719e2c0>>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/bentoml/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/opt/miniconda3/envs/bentoml/lib/python3.10/site-packages/circus/util.py", line 1038, in wrapper
    raise ConflictError("arbiter is already running %s command"
circus.exc.ConflictError: arbiter is already running arbiter_stop command
```

**Comment by ConsciousML** [comment]
I still have this error when I'm running BentoML containers on CloudRun.
Any clue how to fix it?

**Comment by parano** [comment]
@ConsciousML what's your BentoML version?

**Comment by Bowser1704** [comment]
I meet same error in `bentoml, version 1.3.10`.
