### ISSUE TITLE
bug: no support of the bentoml v1.0.20 in examples/triton/pytorch/build_bento.py

### ISSUE THREAD

**Issue by alex4men** [bentoml/BentoML#3877]
### Describe the bug

When I follow this tutorial https://github.com/bentoml/BentoML/tree/main/examples/triton/pytorch
I've got the error, described below. 
The problem appeared after the update of the bentoml library from 1.0.19 to 1.0.20.
I guess, that in the #3735 it was forgotten to give the 'embedded' attribute 'False' default value somewhere in the AbstractRunner, or update the triton/pytorch example.

For now, I've fixed the problem by setting the ```bentoml[all]==1.0.19``` in the example's requirements/requirements.txt.

### To reproduce

```
(venv) elena@elena-MS-7D31:~/Code/BentoML/examples/triton/pytorch$ ./export-yolov5-weights
Usage: ./export-yolov5-weights <batch_size>. Set to 1 by default if not passed.
Successfully export YOLOv5 weights for TorchScript.
(venv) elena@elena-MS-7D31:~/Code/BentoML/examples/triton/pytorch$ python3 train.py
Saved model: Model(tag="torchscript-yolov5:dizu2txxxsdl6p4m")
(venv) elena@elena-MS-7D31:~/Code/BentoML/examples/triton/pytorch$ python3 build_bento.py
Traceback (most recent call last):
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/fs/osfs.py", line 647, in open
    return io.open(
FileNotFoundError: [Errno 2] No such file or directory: b'/home/elena/bentoml/bentos/triton-integration-pytorch/latest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/store.py", line 132, in get
    _tag.version = self._fs.readtext(_tag.latest_path())
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/fs/base.py", line 693, in readtext
    self.open(
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/fs/osfs.py", line 647, in open
    return io.open(
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/fs/error_tools.py", line 89, in __exit__
    reraise(fserror, fserror(self._path, exc=exc_value), traceback)
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/fs/osfs.py", line 647, in open
    return io.open(
fs.errors.ResourceNotFound: resource 'triton-integration-pytorch/latest' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/store.py", line 106, in _recreate_latest
    items = self.list(tag.name)
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/store.py", line 83, in list
    raise NotFound(
bentoml.exceptions.NotFound: no Bentos with name 'triton-integration-pytorch' found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_bento.py", line 29, in <module>
    bentos = bentoml.get(tag)
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/bentos.py", line 61, in get
    return _bento_store.get(tag)
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/store.py", line 137, in get
    self._recreate_latest(_tag)
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/store.py", line 108, in _recreate_latest
    raise NotFound(
bentoml.exceptions.NotFound: no Bentos with name 'triton-integration-pytorch' exist in BentoML store <osfs '/home/elena/bentoml/bentos'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_bento.py", line 46, in <module>
    Bento.create(build_config, version=args.tag).save(
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/bento/bento.py", line 182, in create
    svc = import_service(
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/_internal/service/loader.py", line 137, in import_service
    module = importlib.import_module(module_name, package=working_dir)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/elena/Code/BentoML/examples/triton/pytorch/service.py", line 15, in <module>
    triton_runner = bentoml.triton.Runner(
  File "/home/elena/Code/BentoML/examples/triton/pytorch/venv/lib/python3.8/site-packages/bentoml/triton.py", line 147, in __init__
    self.__attrs_init__(
TypeError: __attrs_init__() missing 1 required positional argument: 'embedded'
```

### Expected behavior

```
(venv) elena@elena-MS-7D31:~/Code/BentoML/examples/triton/pytorch$ ./export-yolov5-weights
Usage: ./export-yolov5-weights <batch_size>. Set to 1 by default if not passed.
Successfully export YOLOv5 weights for TorchScript.
(venv) elena@elena-MS-7D31:~/Code/BentoML/examples/triton/pytorch$ python3 train.py
Saved model: Model(tag="torchscript-yolov5:dizu2txxxsdl6p4m")
(venv) elena@elena-MS-7D31:~/Code/BentoML/examples/triton/pytorch$ python3 build_bento.py
Saved bento: Bento(tag="triton-integration-pytorch:fxj6gqhxxsdl6p4m")
```

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.0.20
`python`: 3.8.10
`platform`: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
`uid_gid`: 1000:1000
<details><summary><code>pip_packages</code></summary>

<br>

```
absl-py==1.4.0
aiohttp==3.8.4
aiosignal==1.3.1
albumentations==1.3.0
anyio==3.6.2
appdirs==1.4.4
asgiref==3.6.0
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
backoff==2.2.1
bentoml==1.0.20
blinker==1.6.2
boto3==1.26.136
botocore==1.29.136
Brotli==1.0.9
build==0.10.0
cachetools==5.3.0
cattrs==22.2.0
certifi==2023.5.7
charset-normalizer==3.1.0
circus==0.18.0
click-option-group==0.5.5
click==8.1.3
cloudpickle==2.2.1
cmake==3.26.3
coloredlogs==15.0.1
ConfigArgParse==1.5.3
contextlib2==21.6.0
contourpy==1.0.7
cycler==0.11.0
deepmerge==1.1.0
Deprecated==1.2.13
exceptiongroup==1.1.1
filelock==3.12.0
filetype==1.2.0
Flask-BasicAuth==0.2.0
Flask-Cors==3.0.10
Flask==2.3.2
flatbuffers==23.5.9
fonttools==4.39.4
frozenlist==1.3.3
fs-s3fs==1.1.1
fs==2.4.16
gast==0.4.0
gevent==22.10.2
geventhttpclient==2.0.2
google-auth-oauthlib==1.0.0
google-auth==2.18.1
google-pasta==0.2.0
googleapis-common-protos==1.56.2
greenlet==2.0.2
grpcio-channelz==1.48.2
grpcio-health-checking==1.48.2
grpcio-reflection==1.48.2
grpcio==1.54.2
h11==0.14.0
h5py==3.8.0
humanfriendly==10.0
idna==3.4
imageio==2.28.1
importlib-metadata==6.6.0
importlib-resources==5.12.0
itsdangerous==2.1.2
jax==0.4.10
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.2.0
keras==2.12.0
kiwisolver==1.4.4
lazy_loader==0.2
libclang==16.0.0
lit==16.0.5
locust==2.15.1
markdown-it-py==2.2.0
Markdown==3.4.3
MarkupSafe==2.1.2
matplotlib==3.7.1
mdurl==0.1.2
ml-dtypes==0.1.0
mpmath==1.3.0
msgpack==1.0.5
mss==9.0.1
multidict==6.0.4
networkx==3.1
numpy==1.23.5
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.1.23
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
onnx==1.14.0
onnxruntime-gpu==1.14.1
onnxruntime==1.14.1
opencv-python-headless==4.7.0.72
opencv-python==4.7.0.72
opentelemetry-api==1.14.0
opentelemetry-exporter-jaeger-proto-grpc==1.14.0
opentelemetry-exporter-jaeger-thrift==1.14.0
opentelemetry-exporter-jaeger==1.14.0
opentelemetry-exporter-otlp-proto-grpc==1.14.0
opentelemetry-exporter-otlp-proto-http==1.14.0
opentelemetry-exporter-otlp==1.14.0
opentelemetry-exporter-zipkin-json==1.14.0
opentelemetry-exporter-zipkin-proto-http==1.14.0
opentelemetry-exporter-zipkin==1.14.0
opentelemetry-instrumentation-aiohttp-client==0.35b0
opentelemetry-instrumentation-asgi==0.35b0
opentelemetry-instrumentation-grpc==0.35b0
opentelemetry-instrumentation==0.35b0
opentelemetry-proto==1.14.0
opentelemetry-sdk==1.14.0
opentelemetry-semantic-conventions==0.35b0
opentelemetry-util-http==0.35b0
opt-einsum==3.3.0
packaging==23.1
pandas==2.0.1
pathspec==0.11.1
Pillow==9.5.0
pip-requirements-parser==32.0.1
pip-tools==6.13.0
pkg_resources==0.0.0
prometheus-client==0.16.0
protobuf==3.20.3
psutil==5.9.5
pyarrow==12.0.0
pyasn1-modules==0.3.0
pyasn1==0.5.0
pydantic==1.10.7
Pygments==2.15.1
pynvml==11.5.0
pyparsing==3.0.9
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
python-rapidjson==1.10
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==25.0.2
qudida==0.0.4
requests-oauthlib==1.3.1
requests==2.30.0
rich==13.3.5
roundrobin==0.0.4
rsa==4.9
s3transfer==0.6.1
schema==0.7.5
scikit-image==0.20.0
scikit-learn==1.2.2
scipy==1.9.1
seaborn==0.12.2
sentry-sdk==1.23.1
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.25.0
sympy==1.12
tensorboard-data-server==0.7.0
tensorboard==2.12.3
tensorflow-estimator==2.12.0
tensorflow-io-gcs-filesystem==0.32.0
tensorflow-io==0.32.0
tensorflow==2.12.0
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
tensorrt==8.6.1
termcolor==2.3.0
thop==0.1.1.post2209072238
threadpoolctl==3.1.0
thrift==0.16.0
tifffile==2023.4.12
tomli==2.0.1
torch==2.0.1
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
triton==2.0.0
tritonclient==2.33.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.105
urllib3==1.26.15
uvicorn==0.22.0
watchfiles==0.19.0
Werkzeug==2.3.4
wrapt==1.14.1
yarl==1.9.2
zipp==3.15.0
zope.event==4.6
zope.interface==6.0
```

</details>

**Comment by aarnphm** [comment]
This issue has been fixed on upstream and we will release a new version promptly.
