### ISSUE TITLE
bug: connection refused without any logs

### ISSUE THREAD

**Issue by mattpodolak** [bentoml/BentoML#3890]
### Describe the bug

On my local machine, I am using node (axios) to make POST requests to a locally running bentoml server, each request fails with a connection refused. **However, I can make requests without a problem from Postman.**

There are no logs (even with debug) from bentoml making it very difficult to troubleshoot. Not sure if there is some default config that would be blocking these?

### To reproduce

1. Copy this service: https://modelserving.com/blog/deploying-your-own-stable-diffusion-service-mz9wk
2. Use axios to make a request to the bentoml service `node test.js`:

test.js
```
const axios = require('axios');

axios
  .post(`http://localhost:4000/txt2img`, {
    prompt: 'can'
  })
  .then((response) => {
    console.log(response.data);
  })
  .catch((error) => {
    console.log(error);
  });
```

Running service like this: `BENTOML_CONFIG=configuration.yaml BENTOML_DEBUG=TRUE bentoml serve service:svc --port 4000`

configuration.yml
```
runners:
  timeout: 900

api_server:
  http:
    cors:
      enabled: False
```

### Expected behavior

Some logs or information on why the connection is being refused from bentoml

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.0.19
`python`: 3.10.10
`platform`: Windows-10-10.0.19044-SP0
`is_window_admin`: False
<details><summary><code>pip_packages</code></summary>

<br>

```
aiohttp==3.8.4
aiosignal==1.3.1
alembic==1.10.2
anyio==3.6.2
appdirs==1.4.4
asgiref==3.7.1
async-timeout==4.0.2
attrs==23.1.0
backoff==2.2.1
bentoml==1.0.19
black==23.1.0
build==0.10.0
cairocffi==1.5.0
CairoSVG==2.7.0
cattrs==22.2.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
circus==0.18.0
click==8.1.3
click-option-group==0.5.5
cloudpickle==2.2.1
colorama==0.4.6
contextlib2==21.6.0
cryptography==40.0.1
cssselect2==0.7.0
deepmerge==1.1.0
defusedxml==0.7.1
Deprecated==1.2.13
diffusers==0.16.0
exceptiongroup==1.1.1
fastapi==0.95.1
filelock==3.12.0
frozenlist==1.3.3
fs==2.4.16
fsspec==2023.4.0
ftfy==6.1.1
googleapis-common-protos==1.59.0
greenlet==2.0.2
h11==0.14.0
httptools==0.5.0
huggingface-hub==0.14.1
idna==3.4
importlib-metadata==6.6.0
Jinja2==3.1.2
Mako==1.2.4
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
networkx==3.1
numpy==1.24.3
opentelemetry-api==1.14.0
opentelemetry-exporter-otlp-proto-http==1.14.0
opentelemetry-instrumentation==0.35b0
opentelemetry-instrumentation-aiohttp-client==0.35b0
opentelemetry-instrumentation-asgi==0.35b0
opentelemetry-proto==1.14.0
opentelemetry-sdk==1.14.0
opentelemetry-semantic-conventions==0.35b0
opentelemetry-util-http==0.35b0
packaging==23.0
pathspec==0.11.1
Pillow==9.5.0
pip-requirements-parser==32.0.1
pip-tools==6.13.0
platformdirs==3.1.1
prometheus-client==0.16.0
protobuf==3.20.3
psutil==5.9.5
psycopg2==2.9.5
pycparser==2.21
pydantic==1.10.7
PyGithub==1.58.1
Pygments==2.15.1
PyJWT==2.6.0
PyNaCl==1.5.0
pynvml==11.5.0
pyparsing==3.0.9
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
PyYAML==6.0
pyzmq==25.0.2
regex==2023.3.23
requests==2.28.2
rich==13.3.5
schema==0.7.5
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.7
starlette==0.25.0
sympy==1.11.1
tinycss2==1.2.1
tokenizers==0.13.3
tomli==2.0.1
torch==2.0.0+cu117
torchaudio==2.0.1+cu117
torchvision==0.15.1+cu117
tornado==6.3.2
tqdm==4.65.0
transformers==4.28.1
typing_extensions==4.5.0
urllib3==1.26.15
uvicorn==0.21.1
watchfiles==0.19.0
wcwidth==0.2.6
webencodings==0.5.1
websockets==11.0.2
wrapt==1.15.0
yarl==1.9.2
zipp==3.15.0
```

</details>

**Comment by mattpodolak** [comment]
the AxiosError:

```
AxiosError: connect ECONNREFUSED ::1:4000
    at AxiosError.from (C:\Users\mattp\Documents\Projects\_ONGOING\diffusicon\server\node_modules\axios\dist\node\axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (C:\Users\mattp\Documents\Projects\_ONGOING\diffusicon\server\node_modules\axios\dist\node\axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (C:\Users\mattp\Documents\Projects\_ONGOING\diffusicon\server\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { 
  port: 4000,
  address: '::1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -4078,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.4.0',
      'Content-Length': '54',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://localhost:4000/txt2img',
    data: '{"prompt":"can","num_imgs":3,"height":256,"width":256}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/txt2img',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      lookup: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '4000',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/txt2img'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 54,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '54',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /txt2img HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.4.0\r\n' +
        'Content-Length: 54\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:4000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/txt2img',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:4000/txt2img',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ::1:4000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 4000
  }
}
```

**Comment by parano** [comment]
Have you tried using URL 0.0.0.0:4000 instead?

It does show any log because the request never reaches the server

**Comment by mattpodolak** [comment]
thanks for the quick response @parano , http://0.0.0.0:4000 does work! I'm not sure if I understand why though

**Comment by sauyon** [comment]
I believe this is because we only listen on the IPv4 catchall (0.0.0.0) and not the IPv6 one (::); we may want to fix this at some point @parano.
