### ISSUE TITLE
bug: BentoML Sklearn Example won't work on >= bentoml==1.0.20

### ISSUE THREAD

**Issue by khakimov** [bentoml/BentoML#3940]
### Describe the bug

Following steps from [example](https://github.com/bentoml/BentoML/tree/main/examples/sklearn/pipeline)
 
bentoml serve service.py:svc will produce 

2023-06-08T08:24:26+0000 [ERROR] [runner:20_news_group:1] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/server/runner_app.py", line 74, in _init_metrics_wrappers
    self.legacy_adaptive_batch_size_hist_map = {
  File "/usr/local/lib/python3.10/dist-packages/bentoml/_internal/server/runner_app.py", line 75, in <dictcomp>
    method.name: metrics_client.Histogram(
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/metrics.py", line 558, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/prometheus_client/metrics.py", line 130, in __init__
    raise ValueError('Invalid metric name: ' + self._name)
ValueError: Invalid metric name: 20_news_group_1_predict_adaptive_batch_size

ValueError not appeared on pip3 install bentoml==1.0.19

### To reproduce

pip install bentoml==1.0.21
follow instructions from https://github.com/bentoml/BentoML/tree/main/examples/sklearn/pipeline

### Environment

bentoml==1.0.20 or bentoml==1.0.21
Python 3.10.7
Ubuntu 22.10

**Comment by bojiang** [comment]
Hi @khakimov !
Thank you very much for pointing out this issue. Renaming '20_news_group' to 'news_group_20' in both 'train.py' and 'service.py' will solve this problem. We will also fix this issue in the repository soon.

**Comment by ssheng** [comment]
Thanks for reporting this issue. The reason for this error is that the metric name, generated from the runner name, does not conform to Prometheus rule.

```python
METRIC_NAME_RE = re.compile(r'^[a-zA-Z_:][a-zA-Z0-9_:]*$')
```

However, in `v1.0.19` and before, the problem did not manifest itself because of the embedded runner mode. Since `v1.0.20`, `bentoml serve` runs with `--production` by default. Runners are started on standalone processes so metrics will get emitted, which caused the ValueError to get raised.

The fix is actually quite simple. You can update the runner name to not start with digit, see https://github.com/bentoml/BentoML/pull/3941.
