### ISSUE TITLE
bug: Failed to import module in container

### ISSUE THREAD

**Issue by haydenshimada** [bentoml/BentoML#4082]
### Describe the bug

I have built a Bento and then dockerize it using bentoml containerize. The built Bento can be served perfectly fine, but the docker image can't be run. It returns this error:

`Error: [bentoml-cli] `serve` failed: Failed loading Bento from directory /home/bentoml/bento: Failed to import module "service": libGL.so.1: cannot open shared object file: No such file or directory`

### Environment

bentoml==1.1.0
torch==2.0.1
opencv-python==4.8.0.74
opencv-python-headless==4.8.0.74
numpy==1.25.1 
albumentations==1.3.1

**Comment by parano** [comment]
hi @haydenshimada - could you share your `bentofile.yaml` file?

I guess you may need to add the following packages to the `system_packages` field:

```yaml
...
docker:
  system_packages:
  - ffmpeg
  - libsm6
  - libxext6
```

https://docs.bentoml.com/en/latest/concepts/bento.html#docker-options

**Comment by haydenshimada** [comment]
This is my `bentofile.yaml`.
```
service: "service:ship_segment"
labels:
  owner: Hayade
  stage: dev
include:
  - "*.py"
python:
  packages:
    - numpy
    - opencv-python
    - albumentations
    - torch
  ```
I have tried adding docker as you said, but it gives me an error while containerizing

```
470.1 ERROR: Exception:
470.1 Traceback (most recent call last):
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
470.1     status = run_func(*args)
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
470.1     return func(self, options, args)
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 507, in run
470.1     installed = install_given_reqs(
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
470.1     requirement.install(
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 796, in install
470.1     install_wheel(
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 729, in install_wheel
470.1     _install_wheel(
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
470.1     file.save()
470.1   File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 388, in save
470.1     shutil.copyfileobj(f, dest)
470.1   File "/usr/local/lib/python3.9/shutil.py", line 205, in copyfileobj
470.1     buf = fsrc_read(length)
470.1   File "/usr/local/lib/python3.9/zipfile.py", line 924, in read
470.1     data = self._read1(n)
470.1   File "/usr/local/lib/python3.9/zipfile.py", line 1000, in _read1
470.1     data = self._decompressor.decompress(data, n)
470.1 zlib.error: Error -3 while decompressing data: invalid stored block lengths
470.1 
470.1 [notice] A new release of pip is available: 23.0.1 -> 23.2.1
470.1 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:43
--------------------
  41 |     COPY --chown=bentoml:bentoml ./env/python ./env/python/
  42 |     # install python packages with install.sh
  43 | >>> RUN --mount=type=cache,target=/root/.cache/pip bash -euxo pipefail /home/bentoml/bento/env/python/install.sh
  44 |     COPY --chown=bentoml:bentoml . ./
  45 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c bash -euxo pipefail /home/bentoml/bento/env/python/install.sh" did not complete successfully: exit code: 2

Encountered exception while trying to building image: Command '['/usr/local/bin/docker', 'build', '--tag', 'airbus-segmentation:6cekc2bplclwx6lz', '--file', '/tmp/tmpexuqmbp5fsTempFS/env/docker/Dockerfile', '/tmp/tmpexuqmbp5fsTempFS/']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/huynh/miniconda3/envs/ship/lib/python3.9/site-packages/bentoml/_internal/container/__init__.py", line 234, in build
    return builder.build(**kwargs)
  File "/home/huynh/miniconda3/envs/ship/lib/python3.9/site-packages/bentoml/_internal/container/base.py", line 190, in build
    raise BentoMLException(str(e)) from None
bentoml.exceptions.BentoMLException: Command '['/usr/local/bin/docker', 'build', '--tag', 'airbus-segmentation:6cekc2bplclwx6lz', '--file', '/tmp/tmpexuqmbp5fsTempFS/env/docker/Dockerfile', '/tmp/tmpexuqmbp5fsTempFS/']' returned non-zero exit status 1.
```

**Comment by aarnphm** [comment]
Can you just run `docker builder prune --filter type=exec.cachemount` and try again?

Seems like the builder might have invalid block somewhere.

**Comment by haydenshimada** [comment]
IT WORKS!!!
Thank you for your help
