### ISSUE TITLE
bug: Doctest fails on modules using `bentoml.metrics.Histogram` on Linux

### ISSUE THREAD

**Issue by connorbrinton** [bentoml/BentoML#4234]
### Describe the bug

We recently noticed CI failing for our BentoML app. Digging into the error, it seems like the root cause was enabling doctesting using PyTest with `pytest --doctest-modules`. Trying to produce a reproducible example indicated that (i) the error only occurs on Linux and (ii) only occurs when a module-level `bentoml.metrics` object is present. It seems that when `doctest` is introspecting the module-level metrics object to look for docstrings, it accesses a property of the object that raises an error.

It would be nice if the metrics object definition could be fixed so that it can be introspected by doctest. This would allow us to write quick tests in our docstrings, which can be a convenient way to both test and explain a function.

### To reproduce

1. Run a Linux container with Python installed: `docker run -it --entrypoint /bin/bash python:3.11`
2. Install BentoML: `pip install bentoml`
3. Create the test file: `echo "import bentoml; histogram = bentoml.metrics.Histogram()" > test.py`
4. Run `doctest`: `python -m doctest test.py`

**Expected result:**
Doctest should run successfully without any errors

**Actual result:**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/doctest.py", line 2811, in <module>
    sys.exit(_test())
             ^^^^^^^
  File "/usr/local/lib/python3.11/doctest.py", line 2801, in _test
    failures, _ = testmod(m, verbose=verbose, optionflags=options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/doctest.py", line 1970, in testmod
    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/doctest.py", line 940, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/usr/local/lib/python3.11/doctest.py", line 1012, in _find
    if ((self._is_routine(val) or inspect.isclass(val)) and
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/doctest.py", line 983, in _is_routine
    maybe_routine = inspect.unwrap(maybe_routine)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/inspect.py", line 762, in unwrap
    while _is_wrapper(func):
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/inspect.py", line 753, in _is_wrapper
    return hasattr(f, '__wrapped__')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/.venv/lib/python3.11/site-packages/bentoml/metrics.py", line 412, in __getattr__
    self._proxy = self._load_proxy()
                  ^^^^^^^^^^^^^^^^^^
  File "/repo/.venv/lib/python3.11/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/.venv/lib/python3.11/site-packages/bentoml/metrics.py", line 432, in _load_proxy
    proxy = getattr(client_impl, self._attr)(*self._args, **self._kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/.venv/lib/python3.11/site-packages/bentoml/_internal/server/metrics/prometheus.py", line 149, in Histogram
    return partial(self.prometheus_client.Histogram, registry=self.registry)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/.venv/lib/python3.11/site-packages/bentoml/_internal/server/metrics/prometheus.py", line 57, in prometheus_client
    assert os.path.isdir(self.multiproc_dir)
AssertionError
```

### Expected behavior

See above, no error

### Environment

Within the Docker container:

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.7
`python`: 3.11.3
`platform`: Linux-6.4.16-linuxkit-aarch64-with-glibc2.31
`uid_gid`: 0:0
<details><summary><code>pip_packages</code></summary>

<br>

```
aiohttp==3.8.6
aiosignal==1.3.1
anyio==4.0.0
appdirs==1.4.4
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.1.0
bentoml==1.1.7
build==1.0.3
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.3.0
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==2.2.1
contextlib2==21.6.0
deepmerge==1.1.0
Deprecated==1.2.14
frozenlist==1.4.0
fs==2.4.16
h11==0.14.0
httpcore==0.18.0
httpx==0.25.0
idna==3.4
importlib-metadata==6.8.0
inflection==0.5.1
iniconfig==2.0.0
Jinja2==3.1.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
multidict==6.0.4
numpy==1.25.2
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
packaging==23.2
pathspec==0.11.2
pip-requirements-parser==32.0.1
pip-tools==7.3.0
pluggy==1.3.0
prometheus-client==0.17.1
psutil==5.9.5
Pygments==2.16.1
pynvml==11.5.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
pytest==7.4.2
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.6
PyYAML==6.0.1
pyzmq==25.1.1
requests==2.31.0
rich==13.6.0
schema==0.7.5
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.31.1
tornado==6.3.3
typing_extensions==4.8.0
urllib3==2.0.6
uvicorn==0.23.2
watchfiles==0.20.0
wrapt==1.15.0
yarl==1.9.2
zipp==3.17.0
```

</details>

**Comment by bojiang** [comment]
Hi, should be fixed in 1.3.1 by @frostming .  Feel free to reopen if issue persists.
