### ISSUE TITLE
bug: new `cattrs==23.2.0` breaks `bentoml build` and `bentoml containerize`

### ISSUE THREAD

**Issue by Stannislav** [bentoml/BentoML#4290]
### Describe the bug

The version `cattrs==23.2.0` [was released a few hours ago](https://pypi.org/project/cattrs/23.2.0/) and breaks `bentoml build` and `bentoml containerize`.

### To reproduce

Follow the steps in the official ["Deploy an Iris classification model with BentoML" guide](https://docs.bentoml.org/en/latest/quickstarts/deploy-an-iris-classification-model-with-bentoml.html).

Running the `bentoml build` command leads to an error:
```
$ bentoml build
Locking PyPI package versions.
WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
Traceback (most recent call last):
  File "/Users/user/venv/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/Users/user/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/user/venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml_cli/utils.py", line 362, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml_cli/utils.py", line 333, in wrapper
    return_value = func(*args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml_cli/utils.py", line 290, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/venv/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml_cli/bentos.py", line 370, in build
    bento = Bento.create(
  File "/Users/user/venv/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml/_internal/bento/bento.py", line 271, in create
    yaml.dump(svc.openapi_spec, f)
  File "/Users/user/venv/lib/python3.8/site-packages/yaml/__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/Users/user/venv/lib/python3.8/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/Users/user/venv/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/Users/user/venv/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml/_internal/service/openapi/specification.py", line 340, in _OpenAPISpecification_dumper
    return dumper.represent_dict(spec.asdict())
  File "/Users/user/venv/lib/python3.8/site-packages/bentoml/_internal/service/openapi/specification.py", line 281, in asdict
    return bentoml_cattr.unstructure(self)
  File "/Users/user/venv/lib/python3.8/site-packages/cattrs/converters.py", line 238, in unstructure
    return self._unstructure_func.dispatch(
  File "<cattrs generated unstructure bentoml._internal.service.openapi.specification.OpenAPISpecification>", line 11, in unstructure_OpenAPISpecification
    res['components'] = __c_unstr_components(instance.components)
  File "/Users/user/venv/lib/python3.8/site-packages/cattrs/converters.py", line 960, in unstructure_optional
    return None if val is None else _handler(val)
  File "<cattrs generated unstructure bentoml._internal.service.openapi.specification.Components>", line 3, in unstructure_Components
    'schemas': __c_unstr_schemas(instance.schemas),
AttributeError: 'dict' object has no attribute 'schemas'
```

Other users reported to me that they tested with `bentoml==1.0.15` and their `bentoml build` step succeeded, but `bentoml containerize` failed:
```
bentoml containerize <my-bento> --verbose  --build-arg MY_ARG=value --image-tag my-tag

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml_cli/utils.py", line 334, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml_cli/utils.py", line 305, in wrapper
    return_value = func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml_cli/utils.py", line 262, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml_cli/utils.py", line 56, in wrapper
    return _f(*args, **transformed)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml_cli/containerize.py", line 507, in containerize
    result = container.build(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml/container.py", line 396, in build
    kwargs["tag"] = determine_container_tag(bento_tag, image_tag=image_tag)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml/_internal/container/__init__.py", line 91, in determine_container_tag
    bento = _bento_store.get(bento_tag)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml/_internal/store.py", line 141, in get
    return self._get_item(_tag)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml/_internal/store.py", line 102, in _get_item
    return self._item_type.from_fs(self._fs.opendir(tag.path()))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml/_internal/bento/bento.py", line 293, in from_fs
    info = BentoInfo.from_yaml_file(bento_yaml)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bentoml/_internal/bento/bento.py", line 463, in from_yaml_file
    yaml_content["tag"] = Tag(yaml_content["name"], yaml_content["version"])
KeyError: 'name'
```

### Expected behavior

No errors.

### Environment

bentoml==1.1.9 and bentoml==1.0.15
python=3.8
OS=Linux, macOS

**Comment by aarnphm** [comment]
oh wow...

**Comment by aarnphm** [comment]
omg they change how to unstructuring union https://github.com/bentoml/BentoML/blob/85e59593d8356c26693318cb5408e522b643e9bc/src/bentoml/_internal/service/openapi/specification.py#L252, so essentially all of our logic breaks

**Comment by cldixon** [comment]
Can confirm locking `cattrs` to `23.1.2` solves this issue.

**Comment by aarnphm** [comment]
Yes this has been tested with openllm 0.4.14

**Comment by BeytullahYayla** [comment]
Hi i got the following error, anybody can help? 

#bentoml build


Traceback (most recent call last):
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\Scripts\bentoml.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml_cli\utils.py", line 362, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml_cli\utils.py", line 333, in wrapper
    return_value = func(*args, **kwargs)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml_cli\utils.py", line 290, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml_cli\bentos.py", line 123, in list_bentos
    bentos = bento_store.list(bento_name)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\store.py", line 73, in list
    return [
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\store.py", line 77, in <listcomp>
    for ver in self.list(_d)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\store.py", line 94, in list
    return [self._get_item(t) for t in tags]
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\store.py", line 94, in <listcomp>
    return [self._get_item(t) for t in tags]
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\store.py", line 102, in _get_item
    return self._item_type.from_fs(self._fs.opendir(tag.path()))
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\bento\bento.py", line 307, in from_fs
    info = BentoInfo.from_yaml_file(bento_yaml)
  File "C:\Users\Beytullah\anaconda3\envs\bentoml\lib\site-packages\bentoml\_internal\bento\bento.py", line 540, in from_yaml_file
    yaml_content["tag"] = Tag(yaml_content["name"], yaml_content["version"])
KeyError: 'name'
