### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by wmeints** [bentoml/BentoML#4410]
### Describe the bug

The command `bentoml build --containerize` copies a serious amount of data to the docker build. I'm not entirely sure where it comes from, but it's 29GB while my project directory is less then 100MB. 

The amount of data is so huge that my root file system is out of space by the time the build tries to copy over the project files.

### To reproduce

This is the log I'm getting:

```
❯ bentoml build --containerize > /tmp/bento-build.log
WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
[+] Building 54.5s (13/15)                                                                                                                                                                                               docker:default
 => [internal] load .dockerignore                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                               0.0s
 => => transferring dockerfile: 1.71kB                                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.11-slim                                                                                                                                                                1.4s
 => [base-container  1/11] FROM docker.io/library/python:3.11-slim@sha256:637774748f62b832dc11e7b286e48cd716727ed04b45a0322776c01bc526afc3                                                                                         0.0s
 => [internal] load build context                                                                                                                                                                                                 31.8s
 => => transferring context: 29.29GB                                                                                                                                                                                              31.8s
 => CACHED [base-container  2/11] RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache                                                           0.0s
 => CACHED [base-container  3/11] RUN --mount=type=cache,target=/var/lib/apt --mount=type=cache,target=/var/cache/apt set -eux &&     apt-get update -y &&     apt-get install -q -y --no-install-recommends --allow-remove-essen  0.0s
 => CACHED [base-container  4/11] RUN groupadd -g 1034 -o bentoml && useradd -m -u 1034 -g 1034 -o -r bentoml                                                                                                                      0.0s
 => CACHED [base-container  5/11] RUN mkdir /home/bentoml/bento && chown bentoml:bentoml /home/bentoml/bento -R                                                                                                                    0.0s
 => CACHED [base-container  6/11] WORKDIR /home/bentoml/bento                                                                                                                                                                      0.0s
 => CACHED [base-container  7/11] COPY --chown=bentoml:bentoml ./env/python ./env/python/                                                                                                                                          0.0s
 => CACHED [base-container  8/11] RUN --mount=type=cache,target=/root/.cache/pip bash -euxo pipefail /home/bentoml/bento/env/python/install.sh                                                                                     0.0s
 => ERROR [base-container  9/11] COPY --chown=bentoml:bentoml . ./                                                                                                                                                                21.2s
------
 > [base-container  9/11] COPY --chown=bentoml:bentoml . ./:
------
Dockerfile:44
--------------------
  42 |     # install python packages with install.sh
  43 |     RUN --mount=type=cache,target=/root/.cache/pip bash -euxo pipefail /home/bentoml/bento/env/python/install.sh
  44 | >>> COPY --chown=bentoml:bentoml . ./
  45 |     
  46 |     # Block SETUP_BENTO_ENTRYPOINT
--------------------
ERROR: failed to solve: failed to copy files: userspace copy failed: write /var/lib/docker/overlay2/ookbcxyphwifanadslwb9dq6w/merged/home/bentoml/bento/models/reviews_classifier_rf/jeqarfvu7w5tn4gu/saved_model.pkl: no space left on device

Encountered exception while trying to building image: Command '['/usr/bin/docker', 'build', '--tag', 'review_classifier:7l2y44fva2xu34gu', '--file', '/tmp/tmp30elvep5fsTempFS/env/docker/Dockerfile', '/tmp/tmp30elvep5fsTempFS/']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/willem/repos/review-classification/.venv/lib/python3.11/site-packages/bentoml/_internal/container/__init__.py", line 234, in build
    return builder.build(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willem/repos/review-classification/.venv/lib/python3.11/site-packages/bentoml/_internal/container/base.py", line 190, in build
    raise BentoMLException(str(e)) from None
bentoml.exceptions.BentoMLException: Command '['/usr/bin/docker', 'build', '--tag', 'review_classifier:7l2y44fva2xu34gu', '--file', '/tmp/tmp30elvep5fsTempFS/env/docker/Dockerfile', '/tmp/tmp30elvep5fsTempFS/']' returned non-zero exit status 1.
```

### Expected behavior

I expect bentoml not to copy my whole root filesystem?!

### Environment

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.1.11
`python`: 3.11.6
`platform`: Linux-6.7.0-arch3-1-x86_64-with-glibc2.38
`uid_gid`: 1000:1000
<details><summary><code>pip_packages</code></summary>

<br>

```
aiohttp==3.9.1
aiosignal==1.3.1
alembic==1.13.1
aniso8601==9.0.1
annotated-types==0.6.0
anyio==4.2.0
appdirs==1.4.4
asgiref==3.7.2
attrs==23.2.0
backoff==2.2.1
bentoml==1.1.11
black==23.12.1
blinker==1.7.0
blis==0.7.11
build==1.0.3
catalogue==2.0.10
cattrs==23.1.2
certifi==2023.11.17
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpathlib==0.16.0
cloudpickle==3.0.0
coloredlogs==14.0
confection==0.1.4
contextlib2==21.6.0
contourpy==1.2.0
croniter==2.0.1
cycler==0.12.1
cymem==2.0.8
dagster==1.6.0
dagster-graphql==1.6.0
dagster-pipes==1.6.0
dagster-webserver==1.6.0
databricks-cli==0.18.0
deepmerge==1.1.1
Deprecated==1.2.14
docker==6.1.3
docstring-parser==0.15
entrypoints==0.4
flake8==7.0.0
Flask==3.0.0
fonttools==4.47.2
frozenlist==1.4.1
fs==2.4.16
fsspec==2023.12.2
gitdb==4.0.11
GitPython==3.1.41
gql==3.5.0
graphene==3.3
graphql-core==3.2.3
graphql-relay==3.2.0
greenlet==3.0.3
grpcio==1.60.0
grpcio-health-checking==1.60.0
gunicorn==21.2.0
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.26.0
humanfriendly==10.0
idna==3.6
importlib-metadata==6.11.0
inflection==0.5.1
iniconfig==2.0.0
isort==5.13.2
itsdangerous==2.1.2
Jinja2==3.1.3
joblib==1.3.2
kiwisolver==1.4.5
langcodes==3.3.0
Mako==1.3.0
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
mccabe==0.7.0
mdurl==0.1.2
mlflow==2.9.2
multidict==6.0.4
murmurhash==1.0.10
mypy-extensions==1.0.0
numpy==1.26.3
nvidia-ml-py==11.525.150
oauthlib==3.2.2
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
packaging==23.2
pandas==2.1.4
pathspec==0.12.1
pendulum==2.1.2
pillow==10.2.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
platformdirs==4.1.0
pluggy==1.3.0
preshed==3.0.9
prometheus-client==0.19.0
protobuf==4.25.2
psutil==5.9.7
pyarrow==14.0.2
pycodestyle==2.11.1
pydantic==2.5.3
pydantic_core==2.14.6
pyflakes==3.2.0
Pygments==2.17.2
PyJWT==2.8.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
pytest==7.4.4
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3.post1
pytzdata==2020.1
PyYAML==6.0.1
pyzmq==25.1.2
querystring-parser==1.2.4
requests==2.31.0
requests-toolbelt==1.0.0
-e git+ssh://git@github.com/wmeints/mlops-with-dagster.git@3469f3a4fb579d9bdd11c62c4023bb0b26834e24#egg=review_classification
rich==13.7.0
schema==0.7.5
scikit-learn==1.3.2
scipy==1.11.4
simple-di==0.1.5
six==1.16.0
smart-open==6.4.0
smmap==5.0.1
sniffio==1.3.0
spacy==3.7.2
spacy-legacy==3.0.12
spacy-loggers==1.0.5
SQLAlchemy==2.0.25
sqlparse==0.4.4
srsly==2.4.8
starlette==0.35.1
structlog==24.1.0
tabulate==0.9.0
thinc==8.2.2
threadpoolctl==3.2.0
tomli==2.0.1
toposort==1.10
tornado==6.4
tqdm==4.66.1
typer==0.9.0
typing_extensions==4.9.0
tzdata==2023.4
universal-pathlib==0.1.4
urllib3==2.1.0
uvicorn==0.25.0
uvloop==0.19.0
wasabi==1.1.2
watchdog==3.0.0
watchfiles==0.21.0
weasel==0.3.4
websocket-client==1.7.0
websockets==12.0
Werkzeug==3.0.1
wrapt==1.16.0
yarl==1.9.4
zipp==3.17.0
```

</details>

**Comment by jeffmarshall** [comment]
it's copying the contents of the working directory to the working directory in the container. `copy . ./`

**Comment by aarnphm** [comment]
Do you hae a virtualenv in this directory?

Can you add a `.bentoignore` and ignore this directory if you have one?
