### ISSUE TITLE
bug: Python 3.11 installation fails because `bento.distutils` uses Python 2 syntax

### ISSUE THREAD

**Issue by adstastic** [bentoml/BentoML#4452]
### Describe the bug

Ran `pip install bento` with Python 3.11 and got the following error: 
```
$ pip install bento
Collecting bento
  Using cached bento-0.1.1.tar.gz (582 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Users/adi/code/server/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/adi/code/server/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/adi/code/server/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-build-env-p99w7r01/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-build-env-p99w7r01/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-build-env-p99w7r01/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-build-env-p99w7r01/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-install-5w2yxq_h/bento_3bb15d33b3774cb9a2556d90a9adf2fe/bento/distutils/__init__.py", line 7, in monkey_patch
          import bento.distutils.dist
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-install-5w2yxq_h/bento_3bb15d33b3774cb9a2556d90a9adf2fe/bento/distutils/dist.py", line 97, in <module>
          from bento.distutils.commands.egg_info \
        File "/private/var/folders/rn/mxrqb4zs4c72hk45bl_34dz80000gn/T/pip-install-5w2yxq_h/bento_3bb15d33b3774cb9a2556d90a9adf2fe/bento/distutils/commands/egg_info.py", line 37
          except OSError, e:
                 ^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### Environment

pip: 23.3.1 
Python: 3.11.6
macOS Sonoma 14.1.2

**Comment by shenxiangzhuang** [comment]
Hi @adstastic , I think maybe you install the wrong package here...with `pip install bento`, you'll install the package `bento` at https://pypi.org/project/bento/, which is from https://github.com/cournape/Bento, not BentoML here:)

You can fellow [the doc in README.md](https://github.com/bentoml/BentoML?tab=readme-ov-file#getting-started) to install `bentoml` package.

**Comment by frostming** [comment]
Thanks for the answer @shenxiangzhuang 

Closing it for invalid issue
