### ISSUE TITLE
Bentoml cli containerize not building image

### ISSUE THREAD

**Issue by MuhammadHadiofficial** [bentoml/BentoML#4486]
### Describe the bug

I run `bentoml containerize`

### To reproduce

- I cloned the stable diffusion sample from bentoml guides
- Ran bentoml serve successfully
- Tried to run bentoml build and bentoml containerize 
It failed with following error:
`[+] Building 0.0s (0/0)                                                                                                                                                                      docker:default
ERROR: unable to prepare context: path "/tmp/tmp4wwktt1nfsTempFS/" not found

Encountered exception while trying to building image: Command '['/snap/bin/docker', 'build', '--tag', 'sdxl_turbo:mtidviwd2czczk6s', '--file', '/tmp/tmp4wwktt1nfsTempFS/env/docker/Dockerfile', '/tmp/tmp4wwktt1nfsTempFS/']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/sociail/BentoSDXLTurbo/venv/lib/python3.10/site-packages/bentoml/_internal/container/__init__.py", line 234, in build
    return builder.build(**kwargs)
  File "/home/sociail/BentoSDXLTurbo/venv/lib/python3.10/site-packages/bentoml/_internal/container/base.py", line 190, in build
    raise BentoMLException(str(e)) from None
bentoml.exceptions.BentoMLException: Command '['/snap/bin/docker', 'build', '--tag', 'sdxl_turbo:mtidviwd2czczk6s', '--file', '/tmp/tmp4wwktt1nfsTempFS/env/docker/Dockerfile', '/tmp/tmp4wwktt1nfsTempFS/']' returned non-zero exit status 1.
`

### Environment

Python-3.10.3

**Comment by dhj-git** [comment]
hello，I encountered the same problem, how did you solve it?

**Comment by MuhammadHadiofficial** [comment]
@dhj-git I could not and ended giving up!

**Comment by nengelmann** [comment]
Seems to be a duplicate of https://github.com/bentoml/BentoML/issues/4117, which is still an open issue.
