### ISSUE TITLE
bug: AssertionError

### ISSUE THREAD

**Issue by HCardosoPrologica** [bentoml/BentoML#4502]
### Describe the bug

Hi.
I already created the bentoml model and service and all work as expected. 
but cant containerize the bento due to this error:

after run this command: bentoml containerize gdh_classifier:5hoyogollssqxiea

  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml_cli\utils.py", line 290, in wrapper
PS C:\Projects\Previsão GDH\prevgdh> bentoml containerize gdh_classifier:5hoyogollssqxiea
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Scripts\bentoml.exe\__main__.py", line 7, in <module>
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml_cli\utils.py", line 362, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml_cli\utils.py", line 333, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml_cli\utils.py", line 290, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml_cli\utils.py", line 58, in wrapper
    return _f(*args, **transformed)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml_cli\containerize.py", line 510, in containerize
    container.health(backend)
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml\_internal\container\__init__.py", line 330, in health
    return get_backend(backend).health()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Previsão GDH\prevgdh\bento_ml\Lib\site-packages\bentoml\_internal\container\docker.py", line 50, in health
    assert v is not None
           ^^^^^^^^^^^^^
AssertionError

any suggestion?

### Expected behavior

containerize the bento successfully.

### Environment

PS C:\Projects\Previsão GDH\prevgdh\service> bentoml env
#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.2.2
`python`: 3.11.3
`platform`: Windows-10-10.0.22631-SP0
`is_window_admin`: False
<details><summary><code>pip_packages</code></summary>

<br>

```
aiohttp==3.9.3
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.2.0
appdirs==1.4.4
asgiref==3.7.2
attrs==23.2.0
bentoml==1.2.2
build==1.0.3
catboost==1.2.2
cattrs==23.1.2
certifi==2024.2.2
charset-normalizer==3.3.2
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
colorama==0.4.6
contextlib2==21.6.0
contourpy==1.2.0
cycler==0.12.1
deepmerge==1.1.1
Deprecated==1.2.14
fonttools==4.48.1
frozenlist==1.4.1
fs==2.4.16
graphviz==0.20.1
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
importlib-metadata==6.11.0
inflection==0.5.1
Jinja2==3.1.3
joblib==1.3.2
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.2
mdurl==0.1.2
multidict==6.0.5
numpy==1.26.4
nvidia-ml-py==11.525.150
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
packaging==23.2
pandas==2.2.0
pathspec==0.12.1
pillow==10.2.0
pip-requirements-parser==32.0.1
pip-tools==7.3.0
plotly==5.18.0
prometheus_client==0.20.0
psutil==5.9.8
pydantic==2.6.1
pydantic_core==2.16.2
Pygments==2.17.2
pyodbc==5.1.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
requests==2.31.0
rich==13.7.0
schema==0.7.5
scikit-learn==1.4.0
scipy==1.12.0
simple-di==0.1.5
six==1.16.0
sniffio==1.3.0
starlette==0.37.1
tenacity==8.2.3
threadpoolctl==3.2.0
tornado==6.4
typing_extensions==4.9.0
tzdata==2024.1
urllib3==2.2.0
uvicorn==0.27.1
watchfiles==0.21.0
wrapt==1.16.0
yarl==1.9.4
zipp==3.17.0
```

</details>

**Comment by frostming** [comment]
What's the output of `docker version --format "{{.Server.Version}}"` in your terminal?

**Comment by Sonny-Inkai** [comment]
> What's the output of `docker version --format "{{.Server.Version}}"` in your terminal?
my docker version is greater than 18.09 but i don't know why it still getting error, anybody have any suggestion! Tks4attention.
$ docker version --format "{{.Server.Version}}"
25.0.3
