### ISSUE TITLE
bug: bentoml containerize Dockerfile parse error line 34: Unknown flag: mount

### ISSUE THREAD

**Issue by amybachir** [bentoml/BentoML#4507]
### Describe the bug

I'm running dind in Gitlab CI runner and the bentoml containerize command breaks with the following error:
docker version is: Docker version 25.0.3, build 4debf41
I have `DOCKER_BUILDKIT=1` set as well
```
docker build cmd: '/usr/bin/docker build --platform linux/amd64 --progress plain --tag REDACTED.dkr.ecr.us-east-1.amazonaws.com/llama-2-7b-chat-hf-openllm:0.0.1 --file /tmp/tmplo46608hfsTempFS/env/docker/Dockerfile /tmp/tmplo46608hfsTempFS/'
#0 building with "default" instance using docker driver
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.1s
#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.32kB done
#2 DONE 0.2s
ERROR: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 34: Unknown flag: mount
Encountered exception while trying to building image: Command '['/usr/bin/docker', 'build', '--platform', 'linux/amd64', '--progress', 'plain', '--tag', 'REDACTED.dkr.ecr.us-east-1.amazonaws.com/llama-2-7b-chat-hf-openllm:0.0.1', '--file', '/tmp/tmplo46608hfsTempFS/env/docker/Dockerfile', '/tmp/tmplo46608hfsTempFS/']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/container/__init__.py", line 234, in build
    return builder.build(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/container/base.py", line 190, in build
    raise BentoMLException(str(e)) from None
bentoml.exceptions.BentoMLException: Command '['/usr/bin/docker', 'build', '--platform', 'linux/amd64', '--progress', 'plain', '--tag', 'REDACTED.dkr.ecr.us-east-1.amazonaws.com/llama-2-7b-chat-hf-openllm:0.0.1', '--file', '/tmp/tmplo46608hfsTempFS/env/docker/Dockerfile', '/tmp/tmplo46608hfsTempFS/']' returned non-zero exit status 1.
```

#### Environment variable
```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```
#### System information
`bentoml`: 1.1.11
`python`: 3.8.10
`platform`: Linux-5.10.186-179.751.amzn2.x86_64-x86_64-with-glibc2.29
`uid_gid`: 0:0
<details><summary><code>pip_packages</code></summary>
<br>
```
accelerate==0.27.2
aiohttp==3.9.3
aioprometheus==23.12.0
aiosignal==1.3.1
ansible==2.9.6
anyio==4.2.0
apache-libcloud==2.8.0
appdirs==1.4.4
argcomplete==1.8.1
asgiref==3.7.2
async-timeout==4.0.3
attrs==23.2.0
bentoml==1.1.11
bitsandbytes==0.41.3.post2
build==0.10.0
cattrs==23.1.2
certifi==2019.11.28
chardet==3.0.4
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
coloredlogs==15.0.1
contextlib2==21.6.0
cryptography==2.8
cuda-python==12.3.0
datasets==2.17.0
dbus-python==1.2.16
deepmerge==1.1.1
Deprecated==1.2.14
dill==0.3.8
distlib==0.3.8
distro==1.9.0
distro-info===0.23ubuntu1
dnspython==1.16.0
einops==0.7.0
exceptiongroup==1.2.0
fastapi==0.109.2
fastcore==1.5.29
filelock==3.13.1
frozenlist==1.4.1
fs==2.4.16
fsspec==2024.2.0
ghapi==1.0.4
grpcio==1.60.1
h11==0.14.0
httpcore==1.0.3
httplib2==0.14.0
httpx==0.26.0
huggingface-hub==0.20.3
humanfriendly==10.0
idna==2.8
importlib-metadata==6.11.0
importlib-resources==6.1.1
inflection==0.5.1
Jinja2==3.1.3
jmespath==0.9.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
lockfile==0.12.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.5
multiprocess==0.70.16
mypy-extensions==1.0.0
netaddr==0.7.19
networkx==3.1
ninja==1.11.1.1
ntlm-auth==1.1.0
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==11.525.150
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
openllm==0.4.44
openllm-client==0.4.44
openllm-core==0.4.44
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
optimum==1.17.1
orjson==3.9.14
packaging==23.2
pandas==2.0.3
pathspec==0.12.1
pip-requirements-parser==32.0.1
pip-tools==7.4.0
pkgutil-resolve-name==1.3.10
platformdirs==4.2.0
prometheus-client==0.20.0
protobuf==4.25.3
psutil==5.9.8
pyarrow==15.0.0
pyarrow-hotfix==0.6
pycrypto==2.6.1
pydantic==1.10.13
pygments==2.17.2
PyGObject==3.36.0
pykerberos==1.1.14
pyparsing==3.1.1
pyproject-hooks==1.0.0
python-apt==2.0.0+ubuntu0.20.4.7
python-dateutil==2.8.2
python-json-logger==2.0.7
python-multipart==0.0.9
pytz==2024.1
pywinrm==0.3.0
PyYAML==5.3.1
pyzmq==25.1.2
quantile-python==1.1
ray==2.6.0
referencing==0.33.0
regex==2023.12.25
requests==2.22.0
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-unixsocket==0.2.0
rich==13.7.0
rpds-py==0.18.0
safetensors==0.4.2
schema==0.7.5
scipy==1.10.1
selinux==3.0
sentencepiece==0.1.99
simple-di==0.1.5
simplejson==3.16.0
six==1.14.0
sniffio==1.3.0
starlette==0.37.1
sympy==1.12
tokenizers==0.15.2
tomli==2.0.1
torch==2.2.0
tornado==6.4
tqdm==4.66.2
transformers==4.37.2
triton==2.2.0
typing-extensions==4.9.0
tzdata==2024.1
unattended-upgrades==0.1
urllib3==1.25.8
uvicorn==0.27.1
virtualenv==20.25.0
vllm==0.2.7
watchfiles==0.21.0
wrapt==1.16.0
xformers==0.0.23.post1
xmltodict==0.12.0
xxhash==3.4.1
yarl==1.9.4
zipp==3.17.0
```
</details>

**Comment by amybachir** [comment]
The issue was due to docker dind version. When pinning the dind version to 25.0.3 resolved the issue
