### ISSUE TITLE
bug: bentoml deployment list fails unexpectedly

### ISSUE THREAD

**Issue by kj3moraes** [bentoml/BentoML#4586]
### Describe the bug

When I type in 

`$ bentoml deployment list-instance-types` 

I get this error 

```
Traceback (most recent call last):
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/bin/bentoml", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/bentoml_cli/utils.py", line 380, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/bentoml_cli/utils.py", line 351, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/bentoml_cli/deployment.py", line 664, in list_instance_types
    d_list = Deployment.list_instance_types(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/bentoml/_internal/cloud/deployment.py", line 795, in list_instance_types
    return [
           ^
  File "/Users/kj3moraes/.pyenv/versions/3.11.2/lib/python3.11/site-packages/bentoml/_internal/cloud/deployment.py", line 802, in <listcomp>
    gpu_type=schema.config.gpu_config.type,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type'
```

I have set `BENTOML_DEBUG=1` and I get the same output. I know my `BENTOML_CLOUD_API_KEY` is correct because I have successfully deployed with it before. This seems like an internal bug. My environment is shown below.

### To reproduce

1. Use Python 3.11.2 
2. Install BentoML via pip (I am currently using `bentoml==1.2.6`)
3. Run `bentoml deployment list-instance-types` in your shell

### Expected behavior

I was just following the guide on your docs so I was hoping for something like this 
```
$ bentoml deployment list-instance-types

Name        Price  CPU    Memory  GPU  GPU Type
cpu.1       *      500m   2Gi
cpu.2       *      1000m  2Gi
cpu.4       *      2000m  8Gi
cpu.8       *      4000m  16Gi
gpu.t4.1    *      2000m  8Gi     1    nvidia-tesla-t4
gpu.l4.1    *      4000m  16Gi    1    nvidia-l4
gpu.a100.1  *      6000m  43Gi    1    nvidia-tesla-a100
```

### Environment

bentoml: 1.2.6
python: python 3.11.2

**Comment by frostming** [comment]
This was fixed by #4566, try upgrading to v1.2.7 please.
