### ISSUE TITLE
bug: pydantic/pathlib patching causes `LookupError: <ContextVar name='request_directory' at 0x172a18860>`

### ISSUE THREAD

**Issue by jamt9000** [bentoml/BentoML#4728]
### Describe the bug

We were seeing strange test failures with exceptions coming from bentoml code in tests unrelated to bentoml. It turns out that this was from the behaviour of `import bentoml` adding items to `pydantic._internal. _std_types_schema` which can cause unexpected validation issues. It seems that the [pathlib validator](https://github.com/bentoml/BentoML/blob/dff954e185cc720c425b92ca948203d6d81dc369/src/_bentoml_sdk/_pydantic.py#L153) tries to access a `request_directory` contextvar which doesn't exist.

```
Traceback (most recent call last):
  File "repro.py", line 20, in <module>
    myfunc(S3URI(url="s3://asdf"))
  File ".venv/lib/python3.11/site-packages/pydantic/deprecated/decorator.py", line 55, in wrapper_function
    return vd.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pydantic/deprecated/decorator.py", line 149, in call
    m = self.init_model_instance(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pydantic/deprecated/decorator.py", line 146, in init_model_instance
    return self.model(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File ".venv/lib/python3.11/site-packages/_bentoml_sdk/validators.py", line 155, in decode
    suffix=filename, dir=request_directory.get(), delete=False
                         ^^^^^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='request_directory' at 0x10f82d030>
```

### To reproduce

```python
from pathlib import Path

import bentoml # removing this import will make it succeed
from pydantic import BaseModel, validate_arguments


class S3URI(BaseModel):
    # simplification of real world class
    url: str


CloudPath = Path | S3URI # Note the order here matters, if S3URI is first it doesn't happen


@validate_arguments
def myfunc(x: CloudPath):
    pass


myfunc(S3URI(url="s3://asdf"))

```

### Expected behavior

I'm not sure what is happening with the contextvar issue, but I would expect that to not fail or give an informative error if there is something that should be done differently. It is quite surprising that bentoml affects unrelated code (especially in the case of testing where it creates non-determinism depending on test ordering and when bentoml was imported in other tests) so some documentation or a way to opt in to that (like the `patch_all()` pattern other libs like [gevent](https://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_all) use) could be good.

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.2.15
`python`: 3.11.9
`platform`: macOS-13.6.6-x86_64-i386-64bit
`uid_gid`: 501:20
<details><summary><code>pip_packages</code></summary>

<br>

```
bentoml==1.2.15
pydantic==2.7.1
pydantic_core==2.18.2
```

</details>

**Comment by jamt9000** [comment]
Here is a workaround I found:

```python
import bentoml

from pydantic._internal import _std_types_schema

_std_types_schema.PREPARE_METHODS = tuple(
    [x for x in _std_types_schema.PREPARE_METHODS if "bentoml" not in x.__module__]
)
```
