### ISSUE TITLE
bug: Error run production bentoml with grpc

### ISSUE THREAD

**Issue by jtong99** [bentoml/BentoML#4964]
### Describe the bug

I am deploying a bentoml service with gRPC, it worked normally some weeks ago, but now I am facing an unexpected error. 

Now I am facing this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/bentoml_cli/utils.py", line 359, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/bentoml_cli/utils.py", line 330, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/bentoml_cli/env_manager.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/bentoml_cli/serve.py", line 529, in serve_grpc
    serve_grpc_production(
  File "/usr/local/lib/python3.8/site-packages/simple_di/__init__.py", line 139, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/usr/local/lib/python3.8/site-packages/bentoml/serving.py", line 687, in serve_grpc_production
    loop.run_until_complete(on_service_deployment(svc))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 595, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

It worked normally in HTTP but the error will happen when I run with gRPC.

### To reproduce

This is how I build and run:

1. build: `bentoml build`
2. containerize: `bentoml containerize --enable-features=grpc`
3. docker run with `serve-grpc`

### Expected behavior

It worked with gRPC

### Environment

bentoml: 1.1.6
python: 3.8
platform: Ubuntu 21

**Comment by jtong99** [comment]
@frostming Thanks for the fix. Previously, I installed the Bentoml from PIP, do I need to re-install Bentoml from Git?

**Comment by frostming** [comment]
@jtong99 it's available on PyPI now, just upgrade it.
