### ISSUE TITLE
bug: Regression with handling of numpy input types in a class that inherits from pydantic.BaseModel

### ISSUE THREAD

**Issue by adamliter** [bentoml/BentoML#4974]
### Describe the bug

The following code works fine with `bentoml==1.3.3` and `pydantic<2.9`:

```python
from typing import Annotated, Any

import bentoml
import numpy as np
from pydantic import BaseModel, Field
from bentoml.validators import DType, Shape


class MyModelInput(BaseModel):
    data: Annotated[np.ndarray, Shape((-1, 2)), DType("float32")] = Field(
        default=[[[1, 2], [2, 4]]], description="A (-1, 2) np.ndarray"
    )


@bentoml.service
class MyModelService:
    @bentoml.api(input_spec=MyModelInput)
    def predict(self, **params: Any) -> str:
        return "model prediction"
```

With `bentoml==1.3.3` and `pydantic>=2.9`, `bentoml serve .` gives the following error:

```
Traceback (most recent call last):
  File "/Users/adamliter/git/bentoml-numpy-test/.venv/bin/bentoml", line 5, in <module>
    from bentoml_cli.cli import cli
  File "/Users/adamliter/git/bentoml-numpy-test/.venv/lib/python3.11/site-packages/bentoml_cli/cli.py", line 59, in <module>
    cli = create_bentoml_cli()
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/adamliter/git/bentoml-numpy-test/.venv/lib/python3.11/site-packages/bentoml_cli/cli.py", line 8, in create_bentoml_cli
    from bentoml._internal.configuration import BENTOML_VERSION
  File "/Users/adamliter/git/bentoml-numpy-test/.venv/lib/python3.11/site-packages/bentoml/__init__.py", line 210, in <module>
    import _bentoml_sdk
  File "/Users/adamliter/git/bentoml-numpy-test/.venv/lib/python3.11/site-packages/_bentoml_sdk/__init__.py", line 11, in <module>
    add_custom_preparers()
  File "/Users/adamliter/git/bentoml-numpy-test/.venv/lib/python3.11/site-packages/_bentoml_sdk/_pydantic.py", line 194, in add_custom_preparers
    *_std_types_schema.PREPARE_METHODS,
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pydantic._internal._std_types_schema' has no attribute 'PREPARE_METHODS'
```

With `bentoml==1.3.5` and `pydantic<2.9`, you get this a different (and very long error). The error being raised is:

```
raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'numpy.ndarray'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```

With `bentoml==1.3.5` and `pydantic>=2.9`, you get the same error as you get with `bentoml==1.3.5` and `pydantic<2.9`.

It also seems to be an issue when passing in the subclass of `BaseModel` to the method directly, not just through the `@bentoml.api` decorator:

```python
from typing import Annotated

import bentoml
import numpy as np
from pydantic import BaseModel, Field
from bentoml.validators import DType, Shape


class MyModelInput(BaseModel):
    data: Annotated[np.ndarray, Shape((-1, 2)), DType("float32")] = Field(
        default=[[[1, 2], [2, 4]]], description="A (-1, 2) np.ndarray"
    )


@bentoml.service
class MyModelService:
    @bentoml.api()
    def predict(self, data: MyModelInput) -> str:
        return "model prediction"
```

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.3.5
`python`: 3.11.10
`platform`: macOS-14.6.1-arm64-arm-64bit
`uid_gid`: 501:20
<details><summary><code>pip_packages</code></summary>

<br>

```
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
aiosqlite==0.20.0
annotated-types==0.7.0
anyio==4.4.0
appdirs==1.4.4
asgiref==3.8.1
attrs==24.2.0
bentoml==1.3.5
-e file:///Users/adamliter/git/bentoml-numpy-test
cattrs==23.1.2
certifi==2024.8.30
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.0.0
deepmerge==2.0
deprecated==1.2.14
frozenlist==1.4.1
fs==2.4.16
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
httpx-ws==0.6.0
idna==3.8
importlib-metadata==6.11.0
inflection==0.5.1
inquirerpy==0.3.4
jinja2==3.1.4
markdown-it-py==3.0.0
markupsafe==2.1.5
mdurl==0.1.2
multidict==6.1.0
numpy==2.1.1
nvidia-ml-py==11.525.150
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
packaging==24.1
pathspec==0.12.1
pfzy==0.3.4
pip-requirements-parser==32.0.1
prometheus-client==0.20.0
prompt-toolkit==3.0.47
psutil==6.0.0
pydantic==2.8.2
pydantic-core==2.20.1
pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
python-multipart==0.0.9
pyyaml==6.0.2
pyzmq==26.2.0
rich==13.8.1
ruff==0.6.4
schema==0.7.7
setuptools==74.1.2
simple-di==0.1.5
six==1.16.0
sniffio==1.3.1
starlette==0.38.5
tomli-w==1.0.0
tornado==6.4.1
typing-extensions==4.12.2
uv==0.4.9
uvicorn==0.30.6
watchfiles==0.24.0
wcwidth==0.2.13
wrapt==1.16.0
wsproto==1.2.0
yarl==1.11.1
zipp==3.20.1
```

</details>

**Comment by frostming** [comment]
The previous behavior is to **implicitly** patch pydantic to serialize numpy arrays which are not supported by `pydantic.BaseModel`. That is not optimal and may lead to [suprises](https://github.com/bentoml/BentoML/issues/4728)

So in the new version, users should use `bentoml.IODescriptor` instead of `pydantic.BaseModel` if there exist non-standard data types in field annotations:


```python
class MyModelInput(bentoml.IODescriptor):
    data: Annotated[np.ndarray, Shape((-1, 2)), DType("float32")] = Field(
        default=[[[1, 2], [2, 4]]], description="A (-1, 2) np.ndarray"
    )
```

@adamliter tell me if that works for you

**Comment by lucasew** [comment]
Can replicate this on latest version available in Conda

**Comment by lucasew** [comment]
Pinning `pydantic=2.8.2` solved here
