### ISSUE TITLE
bug: the server of new sdk is unresponsive when SSL is enabled ‼️

### ISSUE THREAD

**Issue by justachillguy1** [bentoml/BentoML#5113]
### Describe the bug

When using the `bentoml.serve` context manager (as used in `tests/e2e/bento_new_sdk`), if the service is configured with SSL enabled, i.e., `@bentoml.service(ssl={"enabled": True})`, the `bentoml.serve` fails to start the server properly, resulting in a hang and unresponsive state.

The error message: `bentoml.exceptions.ServiceUnavailable: Server is not ready after 100 seconds`

### To reproduce

make sure the requirements are installed.

1. Configure the service of `examples/quickstart/service.py` to enable SSL. (directly edit the file)

  ```python
# file: examples/quickstart/service.py
from __future__ import annotations  # I001

import bentoml

@bentoml.service(ssl={"enabled": True}) # enable SSL
class Summarization:
    def __init__(self) -> None:
        import torch
        from transformers import pipeline

        device = "cuda" if torch.cuda.is_available() else "cpu"
        self.pipeline = pipeline("summarization", device=device)

    @bentoml.api(batchable=True)
    def summarize(self, texts: list[str]) -> list[str]:
        results = self.pipeline(texts)
        return [item["summary_text"] for item in results]
```

2. Use `bentoml.serve` context manager to start the server: create `test.py` in the root folder, then execute it.

  ```python
# file: test.py
import bentoml

with bentoml.serve(
    ".", working_dir="examples/quickstart", port=5000
) as server:
    with bentoml.SyncHTTPClient(server.url, server_ready_timeout=100) as client:
            result = client.summarize(["test"])[0]
            print(result)
```

3. or just execute the command `pytest tests/e2e/bento_new_sdk`, to see the same results.

### Expected behavior

The server is hanging and unresponsive, couldn't be ready.

`bentoml.exceptions.ServiceUnavailable: Server is not ready after 100 seconds`

```
Traceback (most recent call last):
  File "/home/user/test/test.py", line 6, in <module>
    with bentoml.SyncHTTPClient(server.url, server_ready_timeout=100) as client:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.12/site-packages/_bentoml_impl/client/__init__.py", line 50, in __init__
    super().__init__(
  File "/home/user/miniconda3/lib/python3.12/site-packages/_bentoml_impl/client/http.py", line 181, in __init__
    self.wait_until_server_ready(server_ready_timeout)
  File "/home/user/miniconda3/lib/python3.12/site-packages/_bentoml_impl/client/http.py", line 293, in wait_until_server_ready
    raise ServiceUnavailable(f"Server is not ready after {timeout} seconds")
bentoml.exceptions.ServiceUnavailable: Server is not ready after 100 seconds
```

However, If SSL is disabled, this code works well.

### Environment

Using Python 3.12.4 environment at: /home/user/miniconda3
#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.3.15
`python`: 3.12.4
`platform`: Linux-6.8.0-49-generic-x86_64-with-glibc2.35
`uid_gid`: 1004:1004
`conda`: 24.7.1
`in_conda_env`: True
<details><summary><code>conda_packages</code></summary>

<br>

```yaml
name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py312hfc0e8ea_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=23.0.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=24.7.1=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=24.7.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py312h06a4308_0
  - conda-package-streaming=0.10.0=py312h06a4308_0
  - cryptography=42.0.5=py312hdda0065_1
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=hfab0078_4
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py312h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - menuinst=2.1.2=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_0
  - ruamel.yaml=0.17.21=py312h5eee18b_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.66.4=py312he106c6f_0
  - truststore=0.8.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py312h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - a2wsgi==1.10.7
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - annotated-types==0.7.0
      - anyio==4.7.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - attrs==24.2.0
      - bentoml==1.3.15
      - cattrs==23.1.2
      - circus==0.18.0
      - click==8.1.7
      - click-option-group==0.5.6
      - cloudpickle==3.1.0
      - deepmerge==2.0
      - deprecated==1.2.15
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fs==2.4.16
      - fsspec==2024.10.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-ws==0.6.2
      - huggingface-hub==0.26.3
      - importlib-metadata==6.11.0
      - inflection==0.5.1
      - jinja2==3.1.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opentelemetry-api==1.20.0
      - opentelemetry-instrumentation==0.41b0
      - opentelemetry-instrumentation-aiohttp-client==0.41b0
      - opentelemetry-instrumentation-asgi==0.41b0
      - opentelemetry-sdk==1.20.0
      - opentelemetry-semantic-conventions==0.41b0
      - opentelemetry-util-http==0.41b0
      - pathspec==0.12.1
      - pip-requirements-parser==32.0.1
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.36
      - propcache==0.2.1
      - psutil==6.1.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.19
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - questionary==2.0.1
      - regex==2024.11.6
      - rich==13.9.4
      - safetensors==0.4.5
      - schema==0.7.7
      - simple-di==0.1.5
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - sympy==1.13.1
      - tokenizers==0.21.0
      - tomli-w==1.1.0
      - torch==2.5.1
      - tornado==6.4.2
      - transformers==4.47.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - uv==0.5.6
      - uvicorn==0.32.1
      - watchfiles==1.0.0
      - wcwidth==0.2.13
      - wrapt==1.17.0
      - wsproto==1.2.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/user/miniconda3
```

</details>

<details><summary><code>pip_packages</code></summary>

<br>

```
a2wsgi==1.10.7
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.1
aiosqlite==0.20.0
anaconda-anon-usage @ file:///croot/anaconda-anon-usage_1710965072196/work
annotated-types==0.7.0
anyio==4.7.0
appdirs==1.4.4
archspec @ file:///croot/archspec_1709217642129/work
asgiref==3.8.1
attrs==24.2.0
bentoml==1.3.15
boltons @ file:///work/perseverance-python-buildout/croot/boltons_1698851177130/work
brotli @ file:///croot/brotli-split_1714483155106/work
cattrs==23.1.2
certifi @ file:///croot/certifi_1720453481653/work/certifi
cffi @ file:///croot/cffi_1714483155441/work
charset-normalizer @ file:///croot/charset-normalizer_1721748349566/work
circus==0.18.0
click==8.1.7
click-option-group==0.5.6
cloudpickle==3.1.0
conda @ file:///croot/conda_1722004606466/work
conda-content-trust @ file:///croot/conda-content-trust_1714483159009/work
conda-libmamba-solver @ file:///croot/conda-libmamba-solver_1721662679737/work/src
conda-package-handling @ file:///croot/conda-package-handling_1718138267740/work
conda-package-streaming @ file:///croot/conda-package-streaming_1718136078615/work
cryptography @ file:///croot/cryptography_1714660666131/work
deepmerge==2.0
deprecated==1.2.15
distro @ file:///croot/distro_1714488253808/work
filelock==3.16.1
frozendict @ file:///croot/frozendict_1713194832637/work
frozenlist==1.5.0
fs==2.4.16
fsspec==2024.10.0
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
httpx-ws==0.6.2
huggingface-hub==0.26.3
idna @ file:///croot/idna_1714398848350/work
importlib-metadata==6.11.0
inflection==0.5.1
jinja2==3.1.4
jsonpatch @ file:///croot/jsonpatch_1714483231291/work
jsonpointer==2.1
libmambapy @ file:///croot/mamba-split_1714483352891/work/libmambapy
markdown-it-py==3.0.0
markupsafe==3.0.2
mdurl==0.1.2
menuinst @ file:///croot/menuinst_1723567589013/work
mpmath==1.3.0
multidict==6.1.0
networkx==3.4.2
numpy==2.1.3
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-ml-py==12.560.30
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
opentelemetry-api==1.20.0
opentelemetry-instrumentation==0.41b0
opentelemetry-instrumentation-aiohttp-client==0.41b0
opentelemetry-instrumentation-asgi==0.41b0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
opentelemetry-util-http==0.41b0
packaging @ file:///croot/packaging_1720101850331/work
pathspec==0.12.1
pip @ file:///croot/pip_1723484598856/work
pip-requirements-parser==32.0.1
platformdirs @ file:///work/perseverance-python-buildout/croot/platformdirs_1701732573265/work
pluggy @ file:///work/perseverance-python-buildout/croot/pluggy_1698805497733/work
prometheus-client==0.21.1
prompt-toolkit==3.0.36
propcache==0.2.1
psutil==6.1.0
pycosat @ file:///croot/pycosat_1714510623388/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==2.10.3
pydantic-core==2.27.1
pygments==2.18.0
pyparsing==3.2.0
pysocks @ file:///work/perseverance-python-buildout/croot/pysocks_1698845478203/work
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
python-multipart==0.0.19
pyyaml==6.0.2
pyzmq==26.2.0
questionary==2.0.1
regex==2024.11.6
requests @ file:///croot/requests_1721410876868/work
rich==13.9.4
ruamel-yaml @ file:///work/perseverance-python-buildout/croot/ruamel.yaml_1698863605521/work
safetensors==0.4.5
schema==0.7.7
setuptools==72.1.0
simple-di==0.1.5
six==1.17.0
sniffio==1.3.1
starlette==0.41.3
sympy==1.13.1
tokenizers==0.21.0
tomli-w==1.1.0
torch==2.5.1
tornado==6.4.2
tqdm @ file:///croot/tqdm_1716395931952/work
transformers==4.47.0
triton==3.1.0
truststore @ file:///work/perseverance-python-buildout/croot/truststore_1701735771625/work
typing-extensions==4.12.2
urllib3 @ file:///croot/urllib3_1718912636303/work
uv==0.5.6
uvicorn==0.32.1
watchfiles==1.0.0
wcwidth==0.2.13
wheel==0.43.0
wrapt==1.17.0
wsproto==1.2.0
yarl==1.18.3
zipp==3.21.0
zstandard @ file:///croot/zstandard_1714677652653/work
```

</details>

**Comment by frostming** [comment]
You must at least provide the keyfile and certfile as well:

```python
@bentoml.service(
    ssl={"enabled": True, "keyfile": "private.key", "certfile": "cert.pem"}
)
```

Also if the key pairs are self-signed, turn on the `insecure` mode on the client. But since the bentoml built-in client doesn't support insecure mode, you will need to use your own client instead.
