### ISSUE TITLE
Error in execution of "bentoml get" cli command

### ISSUE THREAD

**Issue by jesudasvf** [bentoml/BentoML#662]
**Describe the bug**
just started to use bentoml 0.7.6 / bentoml 0.7.5 on Windows 10, with Python 3.6.8, TensorFlow-GPU 1.14.0 and Keras 2.2.4. Facing issue in using bentoml cli commands.

**To Reproduce**
1. Created a bentoml service with a working model which was trained with Keras and TensorFlow-GPU 1.14.0
2. The created service was saved to the default location
3. Wanted to get the details of the saved service using cli command "bentoml get servicename"
4. On execution of the command the error occurs which indicates that a particular python package "fnctl" is not found

**Expected behavior**
The bentoml cli command get should have displayed the details of the saved service 

**Screenshots/Logs**
(spemoenv) C:\SL_Projects\SpeechEmotionRecognition\SpeechEmoReco_HireAi>bentoml get SpeechEmoClassificationService
Traceback (most recent call last):
  File "C:\Python368\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python368\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\SL_Projects\SpeechEmotionRecognition\spemoenv\Scripts\bentoml.exe\__main__.py", line 4, in <module>
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\bentoml\cli\__init__.py", line 42, in <module>
    from bentoml.server.marshal_server import MarshalService, GunicornMarshalServer
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\bentoml\server\marshal_server.py", line 20, in <module>
    from gunicorn.app.base import Application
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

(spemoenv) C:\SL_Projects\SpeechEmotionRecognition\SpeechEmoReco_HireAi>

The same error occurs for bentoml version 0.7.6/ 0.7.5/ 0.7.4

Is there any dependent package which needs to be version specific? 
[bentoml_cli_issue_packages.txt](https://github.com/bentoml/BentoML/files/4638014/bentoml_cli_issue_packages.txt)

**Environment:**
 - OS: Windows 10 Pro ver 1909 
 - Python 3.6.8. /BentoML Version 0.7.6 / 0.7.5 / 0.7.4

**Additional context**
The problem occurs with bentoml version 07.6 , 0.7.5 and 0.7.4

The list of the python packages installed in the python project environment is attached for reference. 

Thanks !

**Comment by parano** [comment]
Looks like this is duplicated with https://github.com/bentoml/BentoML/issues/663, closing this one in favor of the other ticket now. Thanks @jesudasvf !
