### ISSUE TITLE
got an error  while trying to delete a bentoml sagemaker deployment

### ISSUE THREAD

**Issue by palver7** [bentoml/BentoML#732]
**Describe the bug**
I tried to delete a deployment  but my attempt failed with this error message "delete() got an unexpected keyword argument 'n__namespace' " 

**To Reproduce**
1. Run the aws configure command and  change the default region name field to ap-southeast-1
2. Follow the instructions in https://docs.bentoml.org/en/latest/deployment/aws_sagemaker.html 
3. Run bentoml sagemaker delete _deployment name_

**Expected behavior**
BentoML should delete the deployment without error messages. 

**Screenshots/Logs**

Traceback (most recent call last):
  File "/home/daniel/anaconda3/bin/bentoml", line 10, in <module>
    sys.exit(cli())
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/anaconda3/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'n__namespace'

**Environment:**
 - OS: [linux Mint 19.3 Tricia ]
 - Python/BentoML Version [e.g. Python 3.7.4, BentoML 0.7.8]

**Comment by parano** [comment]
Hi @palver7, what is the `click` version installed in your environment? You should be able to find that by running `pip freeze | grep click`

**Comment by palver7** [comment]
@parano I copied your command to my terminal and ran it but it did not show anything. Looking into the __init__.py file inside the click directory showed the version as 7.0

**Comment by parano** [comment]
@palver7 you can also find the version from python `python -c "import click; print(click.__version__)"`

Could you try to update click to the latest version and try the `delete` command again and see if this error goes away?

You can update click with `pip install -U click`

**Comment by palver7** [comment]
@parano I updated to the latest click version 7.1.2 and the I still get the same error message. `Traceback (most recent call last):
File "/home/daniel/anaconda3/bin/bentoml", line 10, in
sys.exit(cli())
File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/daniel/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/home/daniel/anaconda3/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 94, in wrapper
return func(*args, **kwargs)
TypeError: delete() got an unexpected keyword argument 'n__namespace'`

The difference is that some of the line numbers are changed from version 7.0

**Comment by yubozhao** [comment]
Thank you for discovering this bug! @palver7 

The issue was caused by a missing comma between two option names `-n`, `--namespace` for the namespace param.  It is fixed in #741.

**Comment by palver7** [comment]
@yubozhao Thank you for telling me this. I inserted the comma as you said and it fixed the problem. Closing this issue now.
