### ISSUE TITLE
nginx.conf seems to be missing in 0.8.1

### ISSUE THREAD

**Issue by HenryDashwood** [bentoml/BentoML#832]
Error happens immediately after calling `bentoml sagemaker deploy`, specifically in a Sagemaker notebook instance. I installed 0.8.1 locally as well and the nginx.conf file wasn't there either. Not sure at what point the file should be created. The problem doesn't occur in 0.7.8.
```
Deploying Sagemaker deployment \[2020-06-23 22:26:20,726] ERROR - URPC ERROR ApplyDeployment: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/deployment/sagemaker/nginx.conf'
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/yatai_service_impl.py", line 114, in ApplyDeployment
    response = operator.add(request.deployment)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/deployment/sagemaker/operator.py", line 455, in add
    return self._add(deployment_pb, bento_pb, bento_pb.bento.uri.uri)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/deployment/sagemaker/operator.py", line 485, in _add
    bento_pb.bento.bento_service_metadata.env.docker_base_image,
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/deployment/sagemaker/operator.py", line 330, in _init_sagemaker_project
    shutil.copy(nginx_conf_path, os.path.join(sagemaker_project_dir, 'nginx.conf'))
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/deployment/sagemaker/nginx.conf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/myenv/bin/bentoml", line 8, in <module>
    sys.exit(cli())
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/cli/aws_sagemaker.py", line 154, in deploy
    wait=wait,
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/client/deployment_api.py", line 262, in create_sagemaker_deployment
    return self.create(deployment_pb, wait)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/client/deployment_api.py", line 143, in create
    ApplyDeploymentRequest(deployment=deployment_pb)
  File "/home/ec2-user/anaconda3/envs/myenv/lib/python3.7/site-packages/bentoml/yatai/yatai_service_impl.py", line 151, in ApplyDeployment
    return ApplyDeploymentResponse(status=status_pb2.Status.INTERNAL)
TypeError: Parameter to MergeFrom() must be instance of same class: expected bentoml.Status got int.
```

**Comment by parano** [comment]
This got fixed in #834, it will be in the release 0.8.2
