### ISSUE TITLE
When I built a H2O-based image, the following error occurred

### ISSUE THREAD

**Issue by hechangqin** [bentoml/BentoML#920]
**Describe the bug**
When I built a H2O-based image, the following error occurred. From the Dockerfile generated by BentoML, the base image is bentoml/model-server:0.8.1, and JRE is indeed not installed

I used service.py to build a bentoML bundle
```python
import bentoml
from bentoml.adapters import DataframeInput
from bentoml.artifact import H2oModelArtifact
from customize import preprocessing, postprocessing


@bentoml.env(auto_pip_dependencies=True)
@bentoml.artifacts([H2oModelArtifact('model')])
class LoanDefaultPrediction(bentoml.BentoService):
    @bentoml.api(input=DataframeInput())
    def predict(self, df):
        model_input = preprocessing(df)
        model_output = self.artifacts.model.predict(model_input)
        return postprocessing(model_output)


if __name__ == "__main__":
    import h2o
    h2o.init(strict_version_check=False)
    model = h2o.load_model('H2O_AutoML_20200720_153457')

    model_service = LoanDefaultPrediction()
    model_service.pack("model", model)

    saved_path = model_service.save()
```
And another customize.py to pre process
```python
import h2o

def preprocessing(model_input):
    return h2o.H2OFrame(model_input, na_strings=['NaN'])


def postprocessing(model_output):
    return model_output.as_data_frame()
```

Finally, After I build service image with this bundle, I run this docker image with below log:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.7/site-packages/bentoml/server/gunicorn_server.py", line 92, in load
    bento_service = load(self.bento_service_bundle_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/saved_bundle/loader.py", line 179, in load
    svc = svc_cls()
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service.py", line 526, in __init__
    self._load_artifacts(self._bento_service_bundle_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service.py", line 734, in _load_artifacts
    packed_artifact = artifact.load(artifacts_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/artifact/h2o_model_artifact.py", line 79, in load
    h2o.init()
  File "/opt/conda/lib/python3.7/site-packages/h2o/h2o.py", line 307, in init
    bind_to_localhost=bind_to_localhost)
  File "/opt/conda/lib/python3.7/site-packages/h2o/backend/server.py", line 143, in start
    bind_to_localhost=bind_to_localhost, log_dir=log_dir, log_level=log_level, max_log_file_size=max_log_file_size)
  File "/opt/conda/lib/python3.7/site-packages/h2o/backend/server.py", line 276, in _launch_server
    java = self._find_java()
  File "/opt/conda/lib/python3.7/site-packages/h2o/backend/server.py", line 441, in _find_java
    raise H2OStartupError("Cannot find Java. Please install the latest JRE from\n"
h2o.exceptions.H2OStartupError: Cannot find Java. Please install the latest JRE from
http://www.oracle.com/technetwork/java/javase/downloads/index.html
```

**Comment by parano** [comment]
Hi @hechangqin - you will need to add h2o conda dependency for the docker build to install h2o properly. You may refer to the h2o example notebooks found in the BentoML gallery: https://github.com/bentoml/gallery#h2o

e.g.:
```
import h2o

from bentoml import api, env, artifacts, BentoService
from bentoml.artifact import H2oModelArtifact
from bentoml.adapters import DataframeInput

@env(
    pip_dependencies=['h2o==3.24.0.2', 'pandas'],
    conda_channels=['h2oai'],
    conda_dependencies=['h2o==3.24.0.2']
)
@artifacts([H2oModelArtifact('model')])
class LoanPrediction(BentoService):
    
    @api(input=DataframeInput())
    def predict(self, df):
        h2o_frame = h2o.H2OFrame(df, na_strings=['NaN'])
        predictions = self.artifacts.model.predict(h2o_frame)
        return predictions.as_data_frame()
```

**Comment by hechangqin** [comment]
@parano I add h2o conda dependency for the docker build and the problem still exists. The Dockerfile generated by BentoML as below:

**Comment by parano** [comment]
@hechangqin could you share the environment.yml file in your saved bundle directory?

**Comment by hechangqin** [comment]
@parano As below

**Comment by yubozhao** [comment]
@hechangqin I had a chance to look into this today.  We need to add `openjdk` as part of the `condo_dependencies`.  I will update the h2o notebook to correct this issue.

**Comment by hechangqin** [comment]
@yubozhao OK. Thank you very much. If you have done this job, please share me to know.

**Comment by parano** [comment]
@yubozhao any updates on this?

Btw, with the new `set_dependencies` API in `BentoArtifact` class, we should be able to add the conda dependencies for the user by default, when using H2O artifact.

**Comment by yubozhao** [comment]
@parano I can't wait for the new `set_dependencies` API, it would make H2o Artifact a lot more user friendly to use.

For now, the quickest work around is user manually add `openjdk` as part of the `conda_dependencies` when they write the BentoService definition.

I think I am also going to create a PR that address this for the users that want to use H2o now.

**Comment by hechangqin** [comment]
@parano When can this fix be released?

**Comment by parano** [comment]
@hechangqin the release is coming out in a day or two. You can also just add OpenJDK to conda dependencies list as a workaround in current BentoML version.

**Comment by hechangqin** [comment]
@parano Got it. Thank you very much.
