### ISSUE TITLE
TypeError: 'TfKerasModelArtifact' object is not iterable

### ISSUE THREAD

**Issue by sayakpaul** [bentoml/BentoML#94]
Hi there. Here's my packaging code:
```python
%%writefile text_classification_service.py
import pandas as pd
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from string import digits
from bentoml import api, env, BentoService, artifacts
from bentoml.artifact import TfKerasModelArtifact
from bentoml.handlers import JsonHandler

@artifacts([TfKerasModelArtifact('model')])
@env(conda_dependencies=['tensorflow', 'pandas', 'scikit-learn'])
class TextClassificationService(BentoService):
    
    def vectorizer():
        vectorizer = CountVectorizer(stop_words=None, lowercase=True,
                             ngram_range=(1, 1), min_df=2, binary=True)
        
        train = pd.read_csv('https://raw.githubusercontent.com/Nilabhra/kolkata_nlp_workshop_2019/master/data/train.csv')
        vectorizer.fit_transform(train['text'])
        return vectorizer
    
    def remove_digits(s):
        remove_digits = str.maketrans('', '', digits)
        res = s.translate(remove_digits)
        return res
    
    @api(JsonHandler)
    def predict(self, parsed_json):
        text = parsed_json['text']
        text = remove_digits(text)
        vectorizer = vectorizer()
        text = vectorizer.transform(text)
        prediction =  self.artifacts.model.predict_classes(text)
        response = {'Sentiment': prediction}
        return response
```

And when I am building the archive using - 
```python
from text_classification_service import TextClassificationService

svc = TextClassificationService.pack(model=model)
saved_path = svc.save('/tmp/bento')
print(saved_path)
```

It gives me the following error (with trace):
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-39d1075ec116> in <module>
      1 from text_classification_service import TextClassificationService
      2 
----> 3 svc = TextClassificationService.pack(model=model)
      4 saved_path = svc.save('/tmp/bento')
      5 print(saved_path)

/miniconda3/lib/python3.7/site-packages/bentoml/service.py in pack(cls, *args, **kwargs)
    320         artifacts = ArtifactCollection()
    321 
--> 322         for artifact_spec in cls._artifacts_spec:
    323             if artifact_spec.name in kwargs:
    324                 artifact_instance = artifact_spec.pack(kwargs[artifact_spec.name])

TypeError: 'TfKerasModelArtifact' object is not iterable
```

Here is the code for model building, compilation and fitting:
```python
model = keras.Sequential()

model.add(Dropout(rate=0.2, input_shape=features.shape[1:]))
for _ in range(2):
        model.add(Dense(units=64, activation='relu'))
        model.add(Dropout(rate=0.2))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['acc'])

es_cb = keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)

model.fit(features,
                    labels,
                    epochs=15,
                    batch_size=512,
                    validation_data=(test_features, test_labels),
                    callbacks=[es_cb],
                    verbose=1)
```

Is there any `ArtiFact` I am missing here?

**Comment by parano** [comment]
Thanks for reporting the issue, @sayakpaul, I ran your BentoService definition code with the model from our tf-keras example https://github.com/bentoml/BentoML/blob/master/examples/tf-keras-text-classification/tf-keras-text-classification.ipynb  but cannot reproduce this issue.

The only way I can reproduce the exact error, is by changing the `@artifacts([TfKerasModelArtifact('model')])` to `@artifacts(TfKerasModelArtifact('model'))`. Note that `@artifacts` takes a list of Artifacts definition. We should add a better error message here or just make it work when providing one single artifact.

**Comment by parano** [comment]
On a related note, you can also put vectorizer into the list of artifacts, that way you don't need to re-train in on every API call. For example:

```python
@artifacts([
  TfKerasModelArtifact('model'),
  PickleArtifact('vectorizer')
])
@env(conda_dependencies=['tensorflow', 'pandas', 'scikit-learn'])
class TextClassificationService(BentoService):
  
    def remove_digits(s):
        remove_digits = str.maketrans('', '', digits)
        res = s.translate(remove_digits)
        return res
    
    @api(JsonHandler)
    def predict(self, parsed_json):
        text = parsed_json['text']
        text = remove_digits(text)
        text = self.artifacts.vectorizer.transform(text)
        prediction =  self.artifacts.model.predict_classes(text)
        response = {'Sentiment': prediction}
        return response
```

```python

model = keras.Sequential()
model.fit(...)

vectorizer = CountVectorizer(stop_words=None, lowercase=True,
                             ngram_range=(1, 1), min_df=2, binary=True)
train = pd.read_csv('https://raw.githubusercontent.com/Nilabhra/kolkata_nlp_workshop_2019/master/data/train.csv')
vectorizer.fit_transform(train['text'])

svc = TextClassificationService.pack(model=model,vectorizer=vectorizer)
```

**Comment by sayakpaul** [comment]
Hi @parano it has worked now. Thank you very much especially for the second suggestion regarding adding the `vectorizer` as the `PickleArtifact`. I am able to make inference using the following way - 
```
svc.predict({"text": "I had a wonderful experience eating their chicken noodles! Also loved the ambience."})
```
However, after I serve the model as a REST API using the `bentoml serve`, It starts to behave weirdly - 
```\Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda3/lib/python3.7/site-packages/bentoml/server/bento_api_server.py", line 104, in wrapper
    response = api.handle_request(request)
  File "/miniconda3/lib/python3.7/site-packages/bentoml/service.py", line 85, in handle_request
    return self.handler.handle_request(request, self.func)
  File "/miniconda3/lib/python3.7/site-packages/bentoml/handlers/json_handler.py", line 45, in handle_request
    output = func(parsed_json)
  File "./text_classification/TextClassificationService/0.0.2019_04_19_c1c58d4d/TextClassificationService/text_classification_service.py", line 22, in predict
    prediction =  self.artifacts.model.predict_classes(text)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 311, in predict_classes
    proba = self.predict(x, batch_size=batch_size, verbose=verbose)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1113, in predict
    self, x, batch_size=batch_size, verbose=verbose, steps=steps)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 195, in model_iteration
    f = _make_execution_function(model, mode)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 122, in _make_execution_function
    return model._make_execution_function(mode)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1989, in _make_execution_function
    self._make_predict_function()
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1979, in _make_predict_function
    **kwargs)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3201, in function
    return GraphExecutionFunction(inputs, outputs, updates=updates, **kwargs)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 2939, in __init__
    with ops.control_dependencies(self.outputs):
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 5028, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 4528, in control_dependencies
    c = self.as_graph_element(c)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3557, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("dense_2/Sigmoid:0", shape=(?, 1), dtype=float32) is not an element of this graph.
```

I have tried the suggestions as mentioned in [this](https://github.com/keras-team/keras/issues/6462) and [this](https://github.com/tensorflow/tensorflow/issues/14356) issues. But still, they do not seem to work. Here's the [notebook](https://github.com/sayakpaul/BentoML-Explorations/blob/master/Model%20Training%20%2B%20Saving%20(tf-keras).ipynb) for your convenience.

**Comment by yubozhao** [comment]
@sayakpaul hi, I will check out your notebook and see what I can find out. I will ping you once I have more info

**Comment by sayakpaul** [comment]
Hey @yubozhao sure.  Thanks.

**Comment by yubozhao** [comment]
Hi @sayakpaul, This is pretty interesting. I was able to reproduce this error only in REST api server.  I ran both `bentoml.load` method and cli predict command, both works as you expected.  I will research this problem a little bit more then I will get back to you on this.

**Comment by yubozhao** [comment]
I think this is where the issue is 
> Flask uses multiple threads. The problem you are running into is because the tensorflow model is not loaded and used in the same thread. One workaround is to force tensorflow to use the gloabl default graph .

I will test couple thing during TfKeraHandler loading, if that works, it should solve this issue.

**Comment by yubozhao** [comment]
Link of the issue comment: https://github.com/tensorflow/tensorflow/issues/14356#issuecomment-447588953

**Comment by sayakpaul** [comment]
Yeah,  I studied bout it yesterday. I think you will have to include the global graph part in the section where BentoML loads the model.  Let me know about that. @yubozhao

**Comment by yubozhao** [comment]
Yes. I think I am going to try to do that and see how it goes.  Will keep you updated.

Thank you for finding this issue for us in BentoML @sayakpaul

**Comment by sayakpaul** [comment]
Always welcome @yubozhao. You guys are doing pretty wonderful job.  Serving machine learning models as API endpoints has never been this easier.

**Comment by yubozhao** [comment]
@sayakpaul Hey, I create a quick solution that will solve this.  

What I did is a create a TF model wrapper that will load and predict with the same session and graph.  I am not sure this is a good long term solution for this problem.  I think a good long term solution might be separate the handle request layer (flask/other front end) and inferencing server(tensorflow serving/etc). 

I test the patch locally with your notebook.  I will do few more test and then merge this PR.  If you are able to test the your notebook with this branch and find any issues, please ping me.

Thank you for reporting bug.  Have a good weekend!

**Comment by sayakpaul** [comment]
@yubozhao on it. Will update once done.

**Comment by parano** [comment]
@sayakpaul yes and you can build BentoML locally by:

```
git clone https://github.com/bentoml/BentoML.git
cd BentoML

# fetch the remote branch pull request #97 
git fetch origin pull/97/head:pr-97

# switch to branch
git checkout pr-97

# install bentoML with local changes
pip install .
```

I will also add a local development document next week to make it easier for people who want to contribute to BentoML.

**Comment by sayakpaul** [comment]
@yubozhao @parano it works as expected now. Here is the [repository](https://github.com/sayakpaul/BentoML-Explorations) all updated.
